// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

asheep.wad
models/azuresheep/fiona.mdl
models/azuresheep/hev_barney.mdl
models/azuresheep/myself.mdl
models/azuresheep/p_chub.mdl
models/azuresheep/p_poolstick.mdl
models/azuresheep/sslave.mdl
models/azuresheep/w_blue_suit.mdl
models/azuresheep/w_poolstick.mdl
models/barneyhands/v_357.mdl
models/barneyhands/v_9mmar.mdl
models/barneyhands/v_crossbow.mdl
models/barneyhands/v_desert_eagle.mdl
models/barneyhands/v_displacer.mdl
models/barneyhands/v_egon.mdl
models/barneyhands/v_gauss.mdl
models/barneyhands/v_glock.mdl
models/barneyhands/v_grenade.mdl
models/barneyhands/v_m16a2.mdl
models/barneyhands/v_m40a1.mdl
models/barneyhands/v_medkit.mdl
models/barneyhands/v_pipe_wrench.mdl
models/barneyhands/v_poolstick.mdl
models/barneyhands/v_rpg.mdl
models/barneyhands/v_satchel.mdl
models/barneyhands/v_satchel_radio.mdl
models/barneyhands/v_saw.mdl
models/barneyhands/v_shotgun.mdl
models/barneyhands/v_spore_launcher.mdl
models/barneyhands/v_toad.mdl
models/barneyhands/v_tripmine.mdl
models/barneyhands/v_uzi.mdl
sound/azuresheep/barney/goon.wav
sound/azuresheep/barniel/_comma.wav
sound/azuresheep/barniel/aimforhead.wav
sound/azuresheep/barniel/badfeeling.wav
sound/azuresheep/barniel/bequiet.wav
sound/azuresheep/barniel/bn_another.wav
sound/azuresheep/barniel/bn_attack1.wav
sound/azuresheep/barniel/bn_bring.wav
sound/azuresheep/barniel/bn_close.wav
sound/azuresheep/barniel/bn_dontdothat.wav
sound/azuresheep/barniel/bn_dontmake.wav
sound/azuresheep/barniel/bn_endline.wav
sound/azuresheep/barniel/bn_firepl.wav
sound/azuresheep/barniel/bn_friends.wav
sound/azuresheep/barniel/bn_gotone.wav
sound/azuresheep/barniel/bn_iwish.wav
sound/azuresheep/barniel/bn_onelessh.wav
sound/azuresheep/barniel/bn_post.wav
sound/azuresheep/barniel/bn_seethat.wav
sound/azuresheep/barniel/bn_somuch.wav
sound/azuresheep/barniel/bn_stepoff.wav
sound/azuresheep/barniel/bn_tomb.wav
sound/azuresheep/barniel/bn_uwish.wav
sound/azuresheep/barniel/bn_whatyou.wav
sound/azuresheep/barniel/diegreenthing.wav
sound/azuresheep/barniel/dontagree.wav
sound/azuresheep/barniel/dontknow.wav
sound/azuresheep/barniel/drinktopside.wav
sound/azuresheep/barniel/hearsomething.wav
sound/azuresheep/barniel/hevno.wav
sound/azuresheep/barniel/hi.wav
sound/azuresheep/barniel/hitbad.wav
sound/azuresheep/barniel/humm.wav
sound/azuresheep/barniel/imhit.wav
sound/azuresheep/barniel/movietv.wav
sound/azuresheep/barniel/nosir.wav
sound/azuresheep/barniel/openfire.wav
sound/azuresheep/barniel/rightway.wav
sound/azuresheep/barniel/seelater.wav
sound/azuresheep/barniel/seeya.wav
sound/azuresheep/barniel/slimything.wav
sound/azuresheep/barniel/somethingmoves.wav
sound/azuresheep/barniel/stop1.wav
sound/azuresheep/barniel/teamup1.wav
sound/azuresheep/barniel/teamup2.wav
sound/azuresheep/barniel/thinking.wav
sound/azuresheep/barniel/waitin.wav
sound/azuresheep/barniel/whatsgoingon.wav
sound/azuresheep/barniel/yessir.wav
sound/azuresheep/barniel/youneedmedic.wav
sound/azuresheep/gordon/aimforhead.wav
sound/azuresheep/gordon/aintscared.wav
sound/azuresheep/gordon/ambush.wav
sound/azuresheep/gordon/bigmess.wav
sound/azuresheep/gordon/checkwounds.wav
sound/azuresheep/gordon/diebloodsucker.wav
sound/azuresheep/gordon/dobettertogether.wav
sound/azuresheep/gordon/dontbet.wav
sound/azuresheep/gordon/donthurtem.wav
sound/azuresheep/gordon/getanyworse.wav
sound/azuresheep/gordon/gladof38.wav
sound/azuresheep/gordon/gladtolendhand.wav
sound/azuresheep/gordon/go_another.wav
sound/azuresheep/gordon/go_bring.wav
sound/azuresheep/gordon/go_buttugly.wav
sound/azuresheep/gordon/go_close.wav
sound/azuresheep/gordon/go_dontmake.wav
sound/azuresheep/gordon/go_dotoyou.wav
sound/azuresheep/gordon/go_endline.wav
sound/azuresheep/gordon/go_firepl.wav
sound/azuresheep/gordon/go_friends.wav
sound/azuresheep/gordon/go_gotone.wav
sound/azuresheep/gordon/go_iwish.wav
sound/azuresheep/gordon/go_pain2.wav
sound/azuresheep/gordon/go_seethat.wav
sound/azuresheep/gordon/go_somuch.wav
sound/azuresheep/gordon/go_stepoff.wav
sound/azuresheep/gordon/go_tomb.wav
sound/azuresheep/gordon/go_uwish.wav
sound/azuresheep/gordon/go_watchit.wav
sound/azuresheep/gordon/go_whatyou.wav
sound/azuresheep/gordon/go_whoathere.wav
sound/azuresheep/gordon/hearsomething.wav
sound/azuresheep/gordon/hearsomething2.wav
sound/azuresheep/gordon/hellonicesuit.wav
sound/azuresheep/gordon/hitbad.wav
sound/azuresheep/gordon/imdead.wav
sound/azuresheep/gordon/imhit.wav
sound/azuresheep/gordon/leavealone.wav
sound/azuresheep/gordon/luckwillturn.wav
sound/azuresheep/gordon/noway.wav
sound/azuresheep/gordon/seeya.wav
sound/azuresheep/gordon/slowingyoudown.wav
sound/azuresheep/gordon/somethingdied.wav
sound/azuresheep/gordon/somethingmoves.wav
sound/azuresheep/gordon/soundsright.wav
sound/azuresheep/gordon/standback.wav
sound/azuresheep/gordon/standguard.wav
sound/azuresheep/gordon/stench.wav
sound/azuresheep/gordon/stop1.wav
sound/azuresheep/gordon/stop2.wav
sound/azuresheep/gordon/targetpractice.wav
sound/azuresheep/gordon/teamup1.wav
sound/azuresheep/gordon/yougotit.wav
sound/azuresheep/gordon/youhearthat.wav
sound/azuresheep/gordon/youneedmedic.wav
sound/azuresheep/gordon/yup.wav
sound/azuresheep/kate/aimforhead.wav
sound/azuresheep/kate/anotherdown.wav
sound/azuresheep/kate/badfelling.wav
sound/azuresheep/kate/bequiet.wav
sound/azuresheep/kate/bigeye.wav
sound/azuresheep/kate/bringitone.wav
sound/azuresheep/kate/close.wav
sound/azuresheep/kate/correctway.wav
sound/azuresheep/kate/cupoftie.wav
sound/azuresheep/kate/didntwantthis.wav
sound/azuresheep/kate/didseeshot.wav
sound/azuresheep/kate/dieslimy.wav
sound/azuresheep/kate/dinnerend.wav
sound/azuresheep/kate/dontagree.wav
sound/azuresheep/kate/dontdothat.wav
sound/azuresheep/kate/dontdothis.wav
sound/azuresheep/kate/dontknow.wav
sound/azuresheep/kate/dontwantlive.wav
sound/azuresheep/kate/freebarney.wav
sound/azuresheep/kate/friendslikeyou.wav
sound/azuresheep/kate/gotanother.wav
sound/azuresheep/kate/gotone.wav
sound/azuresheep/kate/hearsomething.wav
sound/azuresheep/kate/hevno.wav
sound/azuresheep/kate/hi.wav
sound/azuresheep/kate/hitbad.wav
sound/azuresheep/kate/hitbad2.wav
sound/azuresheep/kate/hoyes.wav
sound/azuresheep/kate/hummm.wav
sound/azuresheep/kate/iamkate.wav
sound/azuresheep/kate/ka_attack1.wav
sound/azuresheep/kate/muchmore.wav
sound/azuresheep/kate/notatall.wav
sound/azuresheep/kate/oneless.wav
sound/azuresheep/kate/openfire.wav
sound/azuresheep/kate/resquedatlast.wav
sound/azuresheep/kate/seelater.wav
sound/azuresheep/kate/seeyoulater.wav
sound/azuresheep/kate/somethingmove.wav
sound/azuresheep/kate/staypost.wav
sound/azuresheep/kate/stepoff.wav
sound/azuresheep/kate/stop1.wav
sound/azuresheep/kate/teamup1.wav
sound/azuresheep/kate/teamup2.wav
sound/azuresheep/kate/thinking.wav
sound/azuresheep/kate/waithere.wav
sound/azuresheep/kate/waithere2.wav
sound/azuresheep/kate/welcome.wav
sound/azuresheep/kate/whatgoingon.wav
sound/azuresheep/kate/whatgoingon2.wav
sound/azuresheep/kate/whatyoudoing.wav
sound/azuresheep/kate/yesbarn.wav
sound/azuresheep/kate/youaredead.wav
sound/azuresheep/kate/youneedmedic.wav
sound/azuresheep/kate/youwish.wav
sound/scientist/noopen.wav
sound/scientist/sci_alone2.wav
sound/scientist/wareh.wav
sound/weapons/glock_sliderelease1.wav
