// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

cg_bigl.wad
gfx/env/britbk.tga
gfx/env/britdn.tga
gfx/env/britft.tga
gfx/env/britlf.tga
gfx/env/britrt.tga
gfx/env/britup.tga
models/biglolly_coop/agibs.mdl
models/biglolly_coop/boid.mdl
models/biglolly_coop/cg_bltbase01.mdl
models/biglolly_coop/cg_bltbase02.mdl
models/biglolly_coop/cg_cane01.mdl
models/biglolly_coop/cg_cane02.mdl
models/biglolly_coop/cg_cane03.mdl
models/biglolly_coop/cg_gum01.mdl
models/biglolly_coop/cg_lolly1.mdl
models/biglolly_coop/cg_lolly2.mdl
models/biglolly_coop/cg_lolly3.mdl
models/biglolly_coop/cg_lolly4.mdl
models/biglolly_coop/cg_lolly5.mdl
models/biglolly_coop/cg_sucker01.mdl
models/biglolly_coop/cg_sucker03.mdl
models/biglolly_coop/headcrab.mdl
models/biglolly_coop/headcrabt.mdl
models/biglolly_coop/houndeye.mdl
models/biglolly_coop/houndeyet.mdl
models/biglolly_coop/p_9mmhandgun.mdl
models/biglolly_coop/p_crowbar.mdl
models/biglolly_coop/p_grenade.mdl
models/biglolly_coop/p_squeak.mdl
models/biglolly_coop/roach.mdl
models/biglolly_coop/shell.mdl
models/biglolly_coop/v_9mmhandgun.mdl
models/biglolly_coop/v_crowbar.mdl
models/biglolly_coop/v_grenade.mdl
models/biglolly_coop/v_squeak.mdl
models/biglolly_coop/w_9mmarclip.mdl
models/biglolly_coop/w_9mmarclipt.mdl
models/biglolly_coop/w_9mmhandgun.mdl
models/biglolly_coop/w_9mmhandgunt.mdl
models/biglolly_coop/w_battery.mdl
models/biglolly_coop/w_batteryt.mdl
models/biglolly_coop/w_crowbar.mdl
models/biglolly_coop/w_crowbart.mdl
models/biglolly_coop/w_grenade.mdl
models/biglolly_coop/w_grenadet.mdl
models/biglolly_coop/w_medkit.mdl
models/biglolly_coop/w_medkitt.mdl
models/biglolly_coop/w_sqknest.mdl
models/biglolly_coop/w_sqknestt.mdl
models/biglolly_coop/w_squeak.mdl
models/biglolly_coop/w_squeakt.mdl
models/biglolly_coop/w_weaponbox.mdl
models/biglolly_coop/zombie.mdl
models/biglolly_coop/zombie01.mdl
models/biglolly_coop/zombie02.mdl
models/biglolly_coop/zombie03.mdl
models/biglolly_coop/zombiet.mdl
sound/biglolly_coop/ambience/wind2.wav
sound/biglolly_coop/boid/boid_alert1.wav
sound/biglolly_coop/boid/boid_alert2.wav
sound/biglolly_coop/boid/boid_idle1.wav
sound/biglolly_coop/boid/boid_idle2.wav
sound/biglolly_coop/boid/boid_idle3.wav
sound/biglolly_coop/common/wpn_denyselect.wav
sound/biglolly_coop/common/wpn_hudoff.wav
sound/biglolly_coop/common/wpn_hudon.wav
sound/biglolly_coop/common/wpn_moveselect.wav
sound/biglolly_coop/common/wpn_select.wav
sound/biglolly_coop/headcrab/hc_alert1.wav
sound/biglolly_coop/headcrab/hc_alert2.wav
sound/biglolly_coop/headcrab/hc_attack1.wav
sound/biglolly_coop/headcrab/hc_attack2.wav
sound/biglolly_coop/headcrab/hc_attack3.wav
sound/biglolly_coop/headcrab/hc_die1.wav
sound/biglolly_coop/headcrab/hc_die2.wav
sound/biglolly_coop/headcrab/hc_headbite.wav
sound/biglolly_coop/headcrab/hc_idle3.wav
sound/biglolly_coop/headcrab/hc_idle4.wav
sound/biglolly_coop/headcrab/hc_idle5.wav
sound/biglolly_coop/headcrab/hc_pain1.wav
sound/biglolly_coop/headcrab/hc_pain2.wav
sound/biglolly_coop/headcrab/hc_pain3.wav
sound/biglolly_coop/items/9mmclip3.wav
sound/biglolly_coop/items/9mmclip4.wav
sound/biglolly_coop/items/smallmedkit1.wav
sound/biglolly_coop/roach/rch_die.wav
sound/biglolly_coop/roach/rch_smash.wav
sound/biglolly_coop/roach/rch_walk.wav
sound/biglolly_coop/voiceo/bl_lollyout.wav
sound/biglolly_coop/zombie/zo_alert10.wav
sound/biglolly_coop/zombie/zo_alert20.wav
sound/biglolly_coop/zombie/zo_alert30.wav
sound/biglolly_coop/zombie/zo_attack1.wav
sound/biglolly_coop/zombie/zo_attack2.wav
sound/biglolly_coop/zombie/zo_idle1.wav
sound/biglolly_coop/zombie/zo_idle2.wav
sound/biglolly_coop/zombie/zo_idle3.wav
sound/biglolly_coop/zombie/zo_idle4.wav
sound/biglolly_coop/zombie/zo_pain1.wav
sound/biglolly_coop/zombie/zo_pain2.wav
