// Created with resguy v8 (September 2018)
// https://github.com/wootguy/resguy

models/player/uboa/uboa.bmp
models/player/uboa/uboa.mdl
models/player/uboa2/uboa2.bmp
models/player/uboa2/uboa2.mdl
models/player/uboa2b/uboa2b.bmp
models/player/uboa2b/uboa2b.mdl
models/prturi4/agentgrunt.mdl
models/turr/scicotic.mdl
models/uboa/akagonome.mdl
models/uboa/aogonome.mdl
models/uboa/babygarg.mdl
models/uboa/babygargt.mdl
models/uboa/bluedragon.mdl
models/uboa/g_bigmassn.mdl
models/uboa/gamesaba.mdl
models/uboa/gamesabat.mdl
models/uboa/greendragon.mdl
models/uboa/gyudon.mdl
models/uboa/headcrab.mdl
models/uboa/helmet.mdl
models/uboa/hone.mdl
models/uboa/kanateko.mdl
models/uboa/miniblue.mdl
models/uboa/minigreen.mdl
models/uboa/minigrey.mdl
models/uboa/minired.mdl
models/uboa/miniyellow.mdl
models/uboa/mrkimo.mdl
models/uboa/mrkimot.mdl
models/uboa/otete.mdl
models/uboa/taraba.mdl
models/uboa/usagim.mdl
models/uboa/usagir.mdl
models/uboa/whitemassn.mdl
models/uboa/wrench.mdl
sound/uboa/bigredbutton.wav
sound/uboa/gonorego.wav
sound/uboa/gonorego2.wav
sound/uboa/iyaaa.wav
