// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

bts_rc.wad
developer_plates-1.wad
models/bts_rc/barney.mdl
models/bts_rc/furniture/5ton.mdl
models/bts_rc/furniture/a4_pipework1.mdl
models/bts_rc/furniture/a4_pipework2.mdl
models/bts_rc/furniture/admin_console.mdl
models/bts_rc/furniture/barrel.mdl
models/bts_rc/furniture/barrel2.mdl
models/bts_rc/furniture/barrel3.mdl
models/bts_rc/furniture/bed.mdl
models/bts_rc/furniture/bigdoor.mdl
models/bts_rc/furniture/book_black.mdl
models/bts_rc/furniture/book_blue.mdl
models/bts_rc/furniture/book_red.mdl
models/bts_rc/furniture/bookshelf.mdl
models/bts_rc/furniture/bts_sign1.mdl
models/bts_rc/furniture/bts_sign2.mdl
models/bts_rc/furniture/cafeteria_chair.mdl
models/bts_rc/furniture/cafeteria_table.mdl
models/bts_rc/furniture/coffee_machine.mdl
models/bts_rc/furniture/couch.mdl
models/bts_rc/furniture/couch_station.mdl
models/bts_rc/furniture/dorms_table.mdl
models/bts_rc/furniture/eye_scanner_broken.mdl
models/bts_rc/furniture/floodlight.mdl
models/bts_rc/furniture/forklift_static.mdl
models/bts_rc/furniture/gear.mdl
models/bts_rc/furniture/kitchen_pot.mdl
models/bts_rc/furniture/ladders.mdl
models/bts_rc/furniture/lambda.mdl
models/bts_rc/furniture/microwave.mdl
models/bts_rc/furniture/misc_billboard1.mdl
models/bts_rc/furniture/misc_billboard2.mdl
models/bts_rc/furniture/misc_billboard3.mdl
models/bts_rc/furniture/misc_billboard4.mdl
models/bts_rc/furniture/misc_billboard5.mdl
models/bts_rc/furniture/misc_fireext.mdl
models/bts_rc/furniture/misc_fusebox.mdl
models/bts_rc/furniture/misc_healthstation1.mdl
models/bts_rc/furniture/misc_healthstation2.mdl
models/bts_rc/furniture/misc_map.mdl
models/bts_rc/furniture/misc_propaganda1.mdl
models/bts_rc/furniture/misc_suitcharger1.mdl
models/bts_rc/furniture/misc_toolchest.mdl
models/bts_rc/furniture/misc_vendingmachine1.mdl
models/bts_rc/furniture/misc_vendingmachine2.mdl
models/bts_rc/furniture/misc_vendingmachine3.mdl
models/bts_rc/furniture/misc_vendingmachine4.mdl
models/bts_rc/furniture/misc_walkway.mdl
models/bts_rc/furniture/misc_wallcomp1.mdl
models/bts_rc/furniture/misc_wallcomp2.mdl
models/bts_rc/furniture/misc_wallcomp3.mdl
models/bts_rc/furniture/misc_wallcomp4.mdl
models/bts_rc/furniture/misc_wallcomp5.mdl
models/bts_rc/furniture/office_cabinet.mdl
models/bts_rc/furniture/office_cabinet2.mdl
models/bts_rc/furniture/office_cabinet3.mdl
models/bts_rc/furniture/office_cabinet4.mdl
models/bts_rc/furniture/office_computer1.mdl
models/bts_rc/furniture/office_computer2.mdl
models/bts_rc/furniture/office_computer3.mdl
models/bts_rc/furniture/office_partition.mdl
models/bts_rc/furniture/office_table.mdl
models/bts_rc/furniture/office_table_long.mdl
models/bts_rc/furniture/paper_note1.mdl
models/bts_rc/furniture/paper_page1.mdl
models/bts_rc/furniture/paper_page2.mdl
models/bts_rc/furniture/paper_page3.mdl
models/bts_rc/furniture/paper_page4.mdl
models/bts_rc/furniture/paper_page5.mdl
models/bts_rc/furniture/pool_table.mdl
models/bts_rc/furniture/pushcart.mdl
models/bts_rc/furniture/restroom_stalls.mdl
models/bts_rc/furniture/retina_component.mdl
models/bts_rc/furniture/shelf.mdl
models/bts_rc/furniture/shelf_short.mdl
models/bts_rc/furniture/shelf_storage1.mdl
models/bts_rc/furniture/shelf_storage2.mdl
models/bts_rc/furniture/shelf_storage3.mdl
models/bts_rc/furniture/shelf_storage4.mdl
models/bts_rc/furniture/shelf_storage5.mdl
models/bts_rc/furniture/sofa.mdl
models/bts_rc/furniture/storage_crate1.mdl
models/bts_rc/furniture/storage_crate2.mdl
models/bts_rc/furniture/storage_crate4.mdl
models/bts_rc/furniture/storage_crate5.mdl
models/bts_rc/furniture/storage_crate6.mdl
models/bts_rc/furniture/storage_crate7.mdl
models/bts_rc/furniture/studycart.mdl
models/bts_rc/furniture/suv1.mdl
models/bts_rc/furniture/suv2.mdl
models/bts_rc/furniture/table.mdl
models/bts_rc/furniture/terrain_cliffs2.mdl
models/bts_rc/furniture/terrain_cliffs4.mdl
models/bts_rc/furniture/terrain_cliffs5.mdl
models/bts_rc/furniture/tower.mdl
models/bts_rc/furniture/tram_bigdoor.mdl
models/bts_rc/furniture/trashcan.mdl
models/bts_rc/furniture/truck_research.mdl
models/bts_rc/furniture/tv.mdl
models/bts_rc/furniture/tv_unit.mdl
models/bts_rc/furniture/valve.mdl
models/bts_rc/furniture/warehouse_shelf.mdl
models/bts_rc/furniture/wires1.mdl
models/bts_rc/furniture/wires2.mdl
models/bts_rc/items/w_medkits.mdl
models/bts_rc/items/w_medkitst.mdl
models/bts_rc/monsters/barney.mdl
models/bts_rc/monsters/gonome.mdl
models/bts_rc/monsters/gonome_barney.mdl
models/bts_rc/monsters/gonome_soldier.mdl
models/bts_rc/monsters/hassassin_uzi.mdl
models/bts_rc/monsters/headcrab.mdl
models/bts_rc/monsters/hgrunt.mdl
models/bts_rc/monsters/hgrunt_medic.mdl
models/bts_rc/monsters/hgrunt_opfor.mdl
models/bts_rc/monsters/hgrunt_torch.mdl
models/bts_rc/monsters/holo.mdl
models/bts_rc/monsters/hwgrunt.mdl
models/bts_rc/monsters/massn.mdl
models/bts_rc/monsters/otis.mdl
models/bts_rc/monsters/otis2.mdl
models/bts_rc/monsters/rgrunt.mdl
models/bts_rc/monsters/scientist.mdl
models/bts_rc/monsters/scientist2.mdl
models/bts_rc/monsters/scientist3.mdl
models/bts_rc/monsters/sentry_blkops.mdl
models/bts_rc/monsters/sentry_blkopst.mdl
models/bts_rc/monsters/snapbug.mdl
models/bts_rc/monsters/zombie.mdl
models/bts_rc/monsters/zombie_barney.mdl
models/bts_rc/monsters/zombie_blackops.mdl
models/bts_rc/monsters/zombie_construction.mdl
models/bts_rc/monsters/zombie_engineer.mdl
models/bts_rc/monsters/zombie_hev.mdl
models/bts_rc/monsters/zombie_worker.mdl
models/bts_rc/ska/hgrunt.mdl
models/bts_rc/ska/hgruntf.mdl
models/bts_rc/weapons/barney_helmet.mdl
models/bts_rc/weapons/barney_vest.mdl
models/bts_rc/weapons/p_crowbar.mdl
models/bts_rc/weapons/p_crowbarb.mdl
models/bts_rc/weapons/p_crowbaro.mdl
models/bts_rc/weapons/v_crowbar.mdl
models/bts_rc/weapons/v_crowbarb.mdl
models/bts_rc/weapons/v_crowbaro.mdl
models/bts_rc/weapons/w_9mmar.mdl
models/bts_rc/weapons/w_9mmarGL.mdl
models/bts_rc/weapons/w_9mmclip.mdl
models/bts_rc/weapons/w_9mmhandgun.mdl
models/bts_rc/weapons/w_9mmhandgunsd.mdl
models/bts_rc/weapons/w_9mmhandgunsdt.mdl
models/bts_rc/weapons/w_axe.mdl
models/bts_rc/weapons/w_beretta.mdl
models/bts_rc/weapons/w_crowbar.mdl
models/bts_rc/weapons/w_crowbarb.mdl
models/bts_rc/weapons/w_crowbaro.mdl
models/bts_rc/weapons/w_desert_eagle.mdl
models/bts_rc/weapons/w_flaregun.mdl
models/bts_rc/weapons/w_m16.mdl
models/bts_rc/weapons/w_m4.mdl
models/bts_rc/weapons/w_m4sd.mdl
models/bts_rc/weapons/w_m79.mdl
models/bts_rc/weapons/w_medkit.mdl
models/bts_rc/weapons/w_pipe.mdl
models/bts_rc/weapons/w_pmedkit.mdl
models/bts_rc/weapons/w_poolstick.mdl
models/bts_rc/weapons/w_saw.mdl
models/bts_rc/weapons/w_sbshotgun.mdl
models/bts_rc/weapons/w_screwdriver.mdl
models/bts_rc/weapons/w_screwdrivert.mdl
models/bts_rc/weapons/w_shotgun.mdl
models/bts_rc/weapons/w_uzi.mdl
models/player/bts_barney/bts_barney.mdl
models/player/bts_barney3/bts_barney3.mdl
models/player/bts_construction/bts_construction.mdl
models/player/bts_helmet/bts_helmet.mdl
models/player/bts_scientist/bts_scientist.mdl
models/snd/rock_L1.mdl
models/snd/rock_L2.mdl
models/sp_portal/construction.mdl
models/sp_portal/ginsengavenger/gins_papersmags.mdl
models/sp_portal/piranha.mdl
models/the303/domecam.mdl
sound/bts_rc/ambience/d0_bigwarning.wav
sound/bts_rc/ambience/d0_blast.wav
sound/bts_rc/ambience/d1_radio.wav
sound/bts_rc/ambience/d2_radio.wav
sound/bts_rc/ambience/d4_radio.wav
sound/bts_rc/ambience/d4_water.wav
sound/bts_rc/ambience/d5_radio.wav
sound/bts_rc/ambience/d5_warning.wav
sound/bts_rc/ambience/d5_warning_alt.wav
sound/bts_rc/ambience/hecu_ambience1.wav
sound/bts_rc/ambience/hecu_ambience2.wav
sound/bts_rc/ambience/hecu_ambience3.wav
sound/bts_rc/ambience/hecu_ambience4.wav
sound/bts_rc/ambience/hecu_ambience5.wav
sound/bts_rc/ambience/ospreyflyby.wav
sound/bts_rc/ambience/vent_ambience.wav
sound/bts_rc/fgrunt/gr_area5.wav
sound/bts_rc/fmbw.wav
sound/bts_rc/fvox/hev_logon.wav
sound/bts_rc/gonome_hecu/gonome_idle2.wav
sound/bts_rc/interference.wav
sound/bts_rc/items/barrier.wav
sound/bts_rc/items/battery_pickup1.wav
sound/bts_rc/items/d3_sink.wav
sound/bts_rc/items/mag_flip.wav
sound/bts_rc/items/medcharge4.wav
sound/bts_rc/items/medshotno1.wav
sound/bts_rc/items/power_fail.wav
sound/bts_rc/items/power_online.wav
sound/bts_rc/items/repair_snd1.wav
sound/bts_rc/items/repair_snd2.wav
sound/bts_rc/items/repair_snd3.wav
sound/bts_rc/items/repair_snd4.wav
sound/bts_rc/items/repair_snd5.wav
sound/bts_rc/music/bts_rc_checkpoint.ogg
sound/bts_rc/music/bts_rc_credits.ogg
sound/bts_rc/music/bts_rc_credits_alt.ogg
sound/bts_rc/music/bts_rc_credits_alt2.ogg
sound/bts_rc/music/bts_rc_credits_alt3.ogg
sound/bts_rc/music/bts_rc_intro.ogg
sound/bts_rc/music/Hostiles_Detected.ogg
sound/bts_rc/music/Military_dread.ogg
sound/bts_rc/music/Operators_dread.ogg
sound/bts_rc/music/resonance.wav
sound/bts_rc/music/sewers.wav
sound/bts_rc/rgas.ogg
sound/bts_rc/rgrunt/rg_step1.wav
sound/bts_rc/rgrunt/rg_step2.wav
sound/bts_rc/rosenberg/ro_intro1.wav
sound/bts_rc/rosenberg/ro_intro2.wav
sound/bts_rc/scientist/ns/sci_3gear.wav
sound/bts_rc/scientist/ns/sci_area12.wav
sound/bts_rc/scientist/ns/sci_completed.wav
sound/bts_rc/scientist/ns/sci_end.wav
sound/bts_rc/scientist/ns/sci_halfmark.wav
sound/bts_rc/scientist/ns/sci_intro.wav
sound/bts_rc/scientist/ns/sci_issues.wav
sound/bts_rc/scientist/ns/sci_keyitems.wav
sound/bts_rc/scientist/ns/sci_largeseed.wav
sound/bts_rc/scientist/ns/sci_overclock.wav
sound/bts_rc/scientist/ns/sci_runfine.wav
sound/bts_rc/scientist/sci_intro.wav
sound/bts_rc/scientist/sci_simulation.wav
sound/bts_rc/tride/a1_arrive.wav
sound/bts_rc/tride/a1_inbound.wav
sound/bts_rc/tride/a4_arrive.wav
sound/bts_rc/tride/a4_inbound.wav
sound/bts_rc/tride/tr_announcement1.wav
sound/bts_rc/tride/tr_announcement2.wav
sound/bts_rc/tride/tr_announcement3.wav
sound/bts_rc/tride/tr_announcement4.wav
sound/bts_rc/tride/tr_announcement5.wav
sound/bts_rc/tride/tr_arriving.wav
sound/bts_rc/tride/tr_leaving.wav
sound/bts_rc/ts4e.ogg
sound/bts_rc/vox/blackops_announcement.wav
sound/bts_rc/vox/blackops_sentrychange.wav
sound/bts_rc/vox/d0_warning.wav
sound/bts_rc/vox/d1_lockdown_offline.wav
sound/bts_rc/vox/d1_lockdown_online.wav
sound/bts_rc/vox/d1_retina.wav
sound/bts_rc/vox/d1_sentries_offline.wav
sound/bts_rc/vox/d1_sentries_online.wav
sound/bts_rc/vox/d1d4_tram_online.wav
sound/bts_rc/vox/d2_generatorpwr.wav
sound/bts_rc/vox/d2_generatorpwr2.wav
sound/bts_rc/vox/d3_bridge.wav
sound/bts_rc/vox/d3_power_off.wav
sound/bts_rc/vox/d3_power_on.wav
sound/bts_rc/vox/d4_chemical.wav
sound/bts_rc/vox/d4_lockdown_online.wav
sound/bts_rc/vox/intro.wav
sound/bts_rc/vox/military_announcement.wav
sound/bts_rc/vox/military_sentrychange.wav
sound/bts_rc/vox/rgrunts_announcement.wav
sound/bts_rc/vox/rgrunts_sentrychange.wav
sound/bts_rc/zombie_hev/zo_death1.wav
sound/bts_rc/zombie_hev/zo_death2.wav
sound/bts_rc/zombie_hev/zo_death3.wav
sprites/bts_rc/inv_card_maint.spr
sprites/bts_rc/inv_card_research.spr
sprites/bts_rc/inv_card_security.spr
sprites/bts_rc/objectives/obj_gear.spr
sprites/bts_rc/objectives/obj_gear_c1.spr
sprites/bts_rc/objectives/obj_gear_c2.spr
sprites/bts_rc/objectives/obj_gear_c3.spr
sprites/bts_rc/objectives/obj_gear_c4.spr
sprites/bts_rc/objectives/objective1.spr
sprites/bts_rc/objectives/objective10.spr
sprites/bts_rc/objectives/objective11.spr
sprites/bts_rc/objectives/objective2.spr
sprites/bts_rc/objectives/objective3.spr
sprites/bts_rc/objectives/objective4.spr
sprites/bts_rc/objectives/objective5.spr
sprites/bts_rc/objectives/objective6.spr
sprites/bts_rc/objectives/objective7.spr
sprites/bts_rc/objectives/objective8.spr
sprites/bts_rc/objectives/objective9.spr
