// e1e.res - created with RESGen v2.0.2.
// RESGen is made by Jeroen "ShadowLord" Bogers,
// with serveral improvements and additions by Zero3Cool.
// For more info go to http://resgen.hltools.com

// .res entries (118):
escape.wad
Half-Life Escape Mod Sven Co-op v1.0 Read Me.txt
maps/e1e.bsp
maps/e1e.cfg
maps/e1e.res
maps/hlescape.gmr
maps/hlescape.grs
models/hlescape/barney.mdl
models/hlescape/barney01.mdl
models/hlescape/barney02.mdl
models/hlescape/barney03.mdl
models/hlescape/barney04.mdl
models/hlescape/barney05.mdl
models/hlescape/barney06.mdl
models/hlescape/barney07.mdl
models/hlescape/barneyt.mdl
models/hlescape/hgrunt.mdl
models/hlescape/hgrunt01.mdl
models/hlescape/hgrunt02.mdl
models/hlescape/otis.mdl
models/hlescape/otis01.mdl
models/hlescape/otis02.mdl
models/hlescape/otis03.mdl
models/hlescape/p_chub.mdl
models/hlescape/qmeal.mdl
models/hlescape/rgrunt.mdl
models/hlescape/rgruntt.mdl
models/hlescape/scientist.mdl
models/hlescape/scientist01.mdl
models/hlescape/scientist02.mdl
models/hlescape/scientist03.mdl
models/hlescape/scientist04.mdl
models/hlescape/scientist05.mdl
models/hlescape/scientist06.mdl
models/hlescape/scientist07.mdl
models/hlescape/scientist08.mdl
models/hlescape/scientist09.mdl
models/hlescape/scientist10.mdl
models/hlescape/scientist11.mdl
models/hlescape/scientist_cower.mdl
models/hlescape/scientist_cower01.mdl
models/hlescape/tool_box.mdl
models/hlescape/W_9mmAR.mdl
models/hlescape/w_9mmARclip.mdl
models/hlescape/w_9mmhandgun.mdl
models/hlescape/w_ARgrenade.mdl
models/hlescape/w_chub.mdl
models/hlescape/w_grenade.mdl
models/hlescape/w_satchel.mdl
models/hlescape/w_shotbox.mdl
models/hlescape/W_shotgun.mdl
models/hlescape/weapons/v_9mmAR.mdl
models/hlescape/weapons/v_9mmhandgun.mdl
models/hlescape/weapons/v_crowbar.mdl
models/hlescape/weapons/v_grenade.mdl
models/hlescape/weapons/v_satchel.mdl
models/hlescape/weapons/v_satchel_radio.mdl
models/hlescape/weapons/v_shotgun.mdl
models/hlescape/zombie.mdl
models/hlescape/zombie01.mdl
models/hlescape/zombie02.mdl
models/hlescape/zombie03.mdl
models/hlescape/zombie04.mdl
models/hlescape/zombie_barney.mdl
models/hlescape/zombie_barney01.mdl
models/hlescape/zombie_barney02.mdl
models/hlescape/zombie_barney03.mdl
models/hlescape/zombie_soldier.mdl
models/hlescape/zombieT.mdl
sound/hlescape/ambience/blip.wav
sound/hlescape/ambience/experiment.wav
sound/hlescape/ambience/musik.wav
sound/hlescape/ambience/teleport.wav
sound/hlescape/barney/ba_becareful1.wav
sound/hlescape/barney/badoor.wav
sound/hlescape/barney/badoor3.wav
sound/hlescape/hlescapesentences.txt
sound/hlescape/scientist/ahfreeman.wav
sound/hlescape/scientist/dk_01_cascade.wav
sound/hlescape/scientist/dk_01_failed.wav
sound/hlescape/scientist/dk_01_survived.wav
sound/hlescape/scientist/freeman.wav
sound/hlescape/scientist/freemanalive.wav
sound/hlescape/scientist/hellofreeman.wav
sound/hlescape/scientist/ot05_toilet1.wav
sound/hlescape/scientist/ot06_gorman1.wav
sound/hlescape/scientist/ot07_gorman2.wav
sound/hlescape/scientist/ot09_toilet2.wav
sound/hlescape/scientist/ot10_buttons.wav
sound/hlescape/scientist/ot11_buttons2.wav
sound/hlescape/scientist/ot12_gorman3.wav
sound/hlescape/scientist/ot14_toilet3.wav
sound/hlescape/scientist/ot15_gorman4.wav
sound/hlescape/scientist/ro_01_alive.wav
sound/hlescape/scientist/ro_01_callhelp.wav
sound/hlescape/scientist/ro_01_dampen.wav
sound/hlescape/scientist/ro_01_touch.wav
sound/hlescape/speak/barney1.wav
sound/hlescape/speak/barney2.wav
sound/hlescape/speak/barney3.wav
sound/hlescape/speak/barney4.wav
sound/hlescape/speak/barney5.wav
sound/hlescape/speak/rosenberg1.wav
sound/hlescape/speak/rosenberg2.wav
sound/hlescape/speak/rosenberg3.wav
sound/hlescape/speak/scientist1.wav
sound/hlescape/speak/scientist2.wav
sound/hlescape/speak/smith2.wav
sound/hlescape/weapons/dbarrel1.wav
sound/hlescape/weapons/haufire.wav
sound/hlescape/weapons/hks1.wav
sound/hlescape/weapons/hks2.wav
sound/hlescape/weapons/hks3.wav
sound/hlescape/weapons/sbarrel1.wav
sound/hlescape/weapons/scock1.wav
sprites/hlescape/bazookapuff.spr
sprites/hlescape/fog5.spr
sprites/hlescape/fog6.spr




