maps/it_has_leaks.cfg
maps/it_has_leaks.res
models/it_has_leaks/rotfish.mdl
models/it_has_leaks/wizard.mdl
sound/it_has_leaks/drip1.wav
sound/it_has_leaks/fire1.wav
sound/it_has_leaks/jumppad.wav
sound/it_has_leaks/lava.WAV
sound/it_has_leaks/power.wav
sound/it_has_leaks/q_secret.wav
sound/it_has_leaks/runeuse.wav
sound/it_has_leaks/wind2.wav
sound/it_has_leaks/windfly.wav
sound/it_has_leaks/teleport.wav
sprites/it_has_leaks/fixflame.spr
sprites/it_has_leaks/light_globe2.spr