// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

events/muzzle_hgrunt_handgun.txt
events/muzzle_hgrunt_m16.txt
events/muzzle_hgrunt_m40a1.txt
events/muzzle_hgrunt_mp5.txt
events/muzzle_hgrunt_sg.txt
gfx/env/xen9bk.tga
gfx/env/xen9dn.tga
gfx/env/xen9ft.tga
gfx/env/xen9lf.tga
gfx/env/xen9rt.tga
gfx/env/xen9up.tga
halflife.wad
liquids.wad
media/valve.mp3
models/chubby.mdl
models/common/lambda.mdl
models/concrete_gibs.mdl
models/kezaeiv/icons/mk_logo_cyan.mdl
models/kezaeiv/kof/npc/agrunt.mdl
models/kezaeiv/kof/npc/agruntf.mdl
models/kezaeiv/kof/npc/apache.mdl
models/kezaeiv/kof/npc/apachef.mdl
models/kezaeiv/kof/npc/baby_voltigore.mdl
models/kezaeiv/kof/npc/babygarg.mdl
models/kezaeiv/kof/npc/babygargf.mdl
models/kezaeiv/kof/npc/barnabushev.mdl
models/kezaeiv/kof/npc/barneyhev.mdl
models/kezaeiv/kof/npc/bgman.mdl
models/kezaeiv/kof/npc/bullsquid.mdl
models/kezaeiv/kof/npc/chubby.mdl
models/kezaeiv/kof/npc/chumtoad.mdl
models/kezaeiv/kof/npc/controller.mdl
models/kezaeiv/kof/npc/gonome.mdl
models/kezaeiv/kof/npc/hassassin.mdl
models/kezaeiv/kof/npc/hassassinf.mdl
models/kezaeiv/kof/npc/headcrab.mdl
models/kezaeiv/kof/npc/hgrunt.mdl
models/kezaeiv/kof/npc/hgrunt_medic.mdl
models/kezaeiv/kof/npc/hgrunt_medicf.mdl
models/kezaeiv/kof/npc/hgrunt_opfor.mdl
models/kezaeiv/kof/npc/hgrunt_opforf.mdl
models/kezaeiv/kof/npc/hgrunt_torch.mdl
models/kezaeiv/kof/npc/hgruntf.mdl
models/kezaeiv/kof/npc/houndeye.mdl
models/kezaeiv/kof/npc/hwgrunt.mdl
models/kezaeiv/kof/npc/hwgruntf.mdl
models/kezaeiv/kof/npc/islave.mdl
models/kezaeiv/kof/npc/islavef.mdl
models/kezaeiv/kof/npc/kingpin.mdl
models/kezaeiv/kof/npc/massn.mdl
models/kezaeiv/kof/npc/massnf.mdl
models/kezaeiv/kof/npc/osprey.mdl
models/kezaeiv/kof/npc/ospreyf.mdl
models/kezaeiv/kof/npc/otis.mdl
models/kezaeiv/kof/npc/otisf.mdl
models/kezaeiv/kof/npc/p_minigunidle.mdl
models/kezaeiv/kof/npc/p_minigunspin.mdl
models/kezaeiv/kof/npc/pit_drone.mdl
models/kezaeiv/kof/npc/rgrunt.mdl
models/kezaeiv/kof/npc/rgruntf.mdl
models/kezaeiv/kof/npc/strooper.mdl
models/kezaeiv/kof/npc/tor.mdl
models/kezaeiv/kof/npc/torf.mdl
models/kezaeiv/kof/npc/v_minigun.mdl
models/kezaeiv/kof/npc/v_minigunblueshift.mdl
models/kezaeiv/kof/npc/v_minigunopfor.mdl
models/kezaeiv/kof/npc/voltigore.mdl
models/kezaeiv/kof/npc/w_minigun.mdl
models/kezaeiv/kof/npc/zombie.mdl
models/kezaeiv/kof/npc/zombie_barney.mdl
models/kezaeiv/kof/npc/zombie_soldier.mdl
models/oghs/cm/wep/p_2uzis.mdl
models/oghs/cm/wep/p_2uzis_gold.mdl
models/oghs/cm/wep/p_bgrap.mdl
models/oghs/cm/wep/p_displacer.mdl
models/oghs/cm/wep/p_pipe_wrench.mdl
models/oghs/cm/wep/p_shock.mdl
models/oghs/cm/wep/p_spore_launcher.mdl
models/oghs/cm/wep/p_uzi.mdl
models/oghs/cm/wep/p_uzi_gold.mdl
models/oghs/cm/wep/v_bgrap.mdl
models/oghs/cm/wep/v_displacer.mdl
models/oghs/cm/wep/v_pipe_wrench.mdl
models/oghs/cm/wep/v_spore_launcher.mdl
models/oghs/cm/wep/v_uzi.mdl
models/oghs/cm/wep/w_2uzis.mdl
models/oghs/cm/wep/w_2uzis_gold.mdl
models/oghs/cm/wep/w_bgrap.mdl
models/oghs/cm/wep/w_m40a1clip.mdl
models/oghs/cm/wep/w_pipe_wrench.mdl
models/oghs/cm/wep/w_saw_clip.mdl
models/oghs/cm/wep/w_shock.mdl
models/oghs/cm/wep/w_shock_rifle.mdl
models/oghs/cm/wep/w_spore_launcher.mdl
models/oghs/cm/wep/w_uzi.mdl
models/oghs/cm/wep/w_uzi_clip.mdl
models/oghs/cm/wep/w_uzi_gold.mdl
opfor.wad
sound/agrunt/ag_alert1.wav
sound/agrunt/ag_alert3.wav
sound/ambience/alien_beacon.wav
sound/ambience/aliencave1.wav
sound/ambience/alienwind2.wav
sound/ambience/computalk1.wav
sound/ambience/computalk2.wav
sound/ambience/particle_suck1.wav
sound/ambience/particle_suck2.wav
sound/ambience/port_suckout1.wav
sound/aslave/slv_word3.wav
sound/aslave/slv_word4.wav
sound/aslave/slv_word5.wav
sound/aslave/slv_word7.wav
sound/babygarg/gar_attack1.wav
sound/barney/ba_pain1.wav
sound/barney/ba_pain2.wav
sound/bullchicken/bc_attackgrowl2.wav
sound/bullchicken/bc_attackgrowl3.wav
sound/bullchicken/bc_idle1.wav
sound/bullchicken/bc_idle3.wav
sound/buttons/blip1.wav
sound/buttons/button7.wav
sound/buttons/latchunlocked1.wav
sound/buttons/latchunlocked2.wav
sound/common/npc_step1.wav
sound/common/npc_step2.wav
sound/common/npc_step3.wav
sound/common/npc_step4.wav
sound/debris/beamstart15.wav
sound/debris/beamstart2.wav
sound/debris/beamstart4.wav
sound/debris/beamstart7.wav
sound/debris/bustcrate1.wav
sound/debris/bustflesh1.wav
sound/debris/bustflesh2.wav
sound/fgrunt/torch_cut_loop.wav
sound/fgrunt/torch_light.wav
sound/gonome/gonome_eat.wav
sound/gonome/gonome_idle1.wav
sound/gonome/gonome_melee2.wav
sound/gonome/gonome_pain1.wav
sound/gonome/gonome_pain4.wav
sound/hgrunt/gr_die1.wav
sound/hgrunt/gr_die2.wav
sound/hgrunt/gr_pain4.wav
sound/items/clipinsert1.wav
sound/items/cliprelease1.wav
sound/kingpin/kingpin_move.wav
sound/kingpin/kingpin_moveslow.wav
sound/misc/metal5.wav
sound/misc/spark1.wav
sound/misc/spark3.wav
sound/misc/spark4.wav
sound/oghs/cs06/a!.wav
sound/oghs/cs06/badbone.wav
sound/oghs/cs06/bell.wav
sound/oghs/cs06/boing.wav
sound/oghs/cs06/crit.wav
sound/oghs/cs06/csm.wav
sound/oghs/cs06/cum.wav
sound/oghs/cs06/dross.wav
sound/oghs/cs06/fart.wav
sound/oghs/cs06/gay.wav
sound/oghs/cs06/headshot.wav
sound/oghs/cs06/pipe.wav
sound/oghs/cs06/pui.wav
sound/oghs/cs06/slip.wav
sound/oghs/cs06/tom2.wav
sound/oghs/cs06/wrong.wav
sound/oghs/cs06/zzz.wav
sound/otis/candy.wav
sound/otis/stupidmachines.wav
sound/pitdrone/pit_drone_attack_spike1.wav
sound/pitdrone/pit_drone_die1.wav
sound/pitdrone/pit_drone_die2.wav
sound/pitdrone/pit_drone_die3.wav
sound/pitdrone/pit_drone_eat.wav
sound/pitdrone/pit_drone_hunt3.wav
sound/pitdrone/pit_drone_melee_attack1.wav
sound/pitdrone/pit_drone_melee_attack2.wav
sound/scientist/sci_pain4.wav
sound/shockroach/shock_angry.wav
sound/shockroach/shock_die.wav
sound/shockroach/shock_flinch.wav
sound/shockroach/shock_idle1.wav
sound/shockroach/shock_idle2.wav
sound/shockroach/shock_idle3.wav
sound/shockroach/shock_jump1.wav
sound/shockroach/shock_jump2.wav
sound/shockroach/shock_walk.wav
sound/singularity/misc/cp_nod_reinf.mp3
sound/singularity/misc/teleport.wav
sound/singularity/music/ss1_fight01.ogg
sound/singularity/npc/csgo_deag_shot.wav
sound/singularity/npc/dusk_shotgun_shot.wav
sound/singularity/npc/exp1.wav
sound/singularity/npc/exp3.wav
sound/singularity/npc/exp5.wav
sound/singularity/npc/hgrunt_3shot.wav
sound/singularity/npc/hl2_flesh_hit1.wav
sound/singularity/npc/hl2_flesh_hit2.wav
sound/singularity/npc/hl2_flesh_hit3.wav
sound/singularity/npc/igi2_dragunov_shot.wav
sound/singularity/npc/igi2_g36_shot.wav
sound/singularity/npc/quake3_grenade_shot.wav
sound/singularity/npc/quake4_plasma_shot.wav
sound/singularity/npc/starcraft_ghost_rifle.wav
sound/voltigore/voltigore_attack_melee1.wav
sound/voltigore/voltigore_attack_melee2.wav
sound/voltigore/voltigore_attack_shock.wav
sound/voltigore/voltigore_communicate3.wav
sound/voltigore/voltigore_die1.wav
sound/voltigore/voltigore_die2.wav
sound/voltigore/voltigore_die3.wav
sound/voltigore/voltigore_eat.wav
sound/voltigore/voltigore_footstep1.wav
sound/voltigore/voltigore_footstep2.wav
sound/voltigore/voltigore_footstep3.wav
sound/voltigore/voltigore_pain1.wav
sound/voltigore/voltigore_pain2.wav
sound/voltigore/voltigore_run_grunt1.wav
sound/voltigore/voltigore_run_grunt2.wav
sound/vox/_comma.wav
sound/vox/buzwarn.wav
sound/vox/detected.wav
sound/vox/dimensional.wav
sound/vox/distortion.wav
sound/vox/energy.wav
sound/vox/in.wav
sound/vox/kilo.wav
sound/vox/lol.wav
sound/vox/power.wav
sound/vox/sector.wav
sound/vox/warning.wav
sound/weapons/alienweap_draw.wav
sound/weapons/bullet_hit1.wav
sound/weapons/bullet_hit2.wav
sound/weapons/electro4.wav
sound/weapons/reload1.wav
sound/weapons/reload3.wav
sound/weapons/scock1.wav
sound/weapons/uzi/akimbo_deploy.wav
sound/weapons/uzi/akimbo_pull1.wav
sound/weapons/uzi/akimbo_pull2.wav
sound/weapons/uzi/deploy.wav
sound/weapons/uzi/deploy1.wav
sound/weapons/uzi/reload1.wav
sound/weapons/uzi/reload2.wav
sound/weapons/uzi/reload3.wav
sound/weapons/uzi/reload_left1.wav
sound/weapons/uzi/reload_left2.wav
sound/weapons/uzi/reload_right1.wav
sound/weapons/uzi/reload_right2.wav
sound/zombie/claw_strike3.wav
sound/zombie/zo_attack1.wav
sprites/enter1.spr
sprites/exit1.spr
sprites/Fexplo1.spr
sprites/level_change_opfor.spr
sprites/lgtning.spr
sprites/MP5Flash.spr
sprites/muzzleflash3.spr
sprites/SAWFlash.spr
sprites/SGFlash.spr
sprites/XFlare1.spr
sprites/xspark2.spr
xeno.wad
