// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/snglrt_outspace_bk.tga
gfx/env/snglrt_outspace_dn.tga
gfx/env/snglrt_outspace_ft.tga
gfx/env/snglrt_outspace_lf.tga
gfx/env/snglrt_outspace_rt.tga
gfx/env/snglrt_outspace_up.tga
kez_singularity.wad
kz_snglrt_sky.wad
models/kezaeiv/icons/mk_logo_cyan.mdl
models/kezaeiv/kof/npc/agrunt.mdl
models/kezaeiv/kof/npc/agruntf.mdl
models/kezaeiv/kof/npc/apache.mdl
models/kezaeiv/kof/npc/apachef.mdl
models/kezaeiv/kof/npc/baby_voltigore.mdl
models/kezaeiv/kof/npc/babygarg.mdl
models/kezaeiv/kof/npc/babygargf.mdl
models/kezaeiv/kof/npc/barnabushev.mdl
models/kezaeiv/kof/npc/barneyhev.mdl
models/kezaeiv/kof/npc/bgman.mdl
models/kezaeiv/kof/npc/bullsquid.mdl
models/kezaeiv/kof/npc/chubby.mdl
models/kezaeiv/kof/npc/chumtoad.mdl
models/kezaeiv/kof/npc/controller.mdl
models/kezaeiv/kof/npc/gonome.mdl
models/kezaeiv/kof/npc/hassassin.mdl
models/kezaeiv/kof/npc/hassassinf.mdl
models/kezaeiv/kof/npc/hgrunt.mdl
models/kezaeiv/kof/npc/hgrunt_medic.mdl
models/kezaeiv/kof/npc/hgrunt_medicf.mdl
models/kezaeiv/kof/npc/hgrunt_opfor.mdl
models/kezaeiv/kof/npc/hgrunt_opforf.mdl
models/kezaeiv/kof/npc/hgrunt_torch.mdl
models/kezaeiv/kof/npc/hgruntf.mdl
models/kezaeiv/kof/npc/houndeye.mdl
models/kezaeiv/kof/npc/hwgrunt.mdl
models/kezaeiv/kof/npc/hwgruntf.mdl
models/kezaeiv/kof/npc/islavef.mdl
models/kezaeiv/kof/npc/kingpin.mdl
models/kezaeiv/kof/npc/massn.mdl
models/kezaeiv/kof/npc/massnf.mdl
models/kezaeiv/kof/npc/osprey.mdl
models/kezaeiv/kof/npc/ospreyf.mdl
models/kezaeiv/kof/npc/otis.mdl
models/kezaeiv/kof/npc/otisf.mdl
models/kezaeiv/kof/npc/p_minigunidle.mdl
models/kezaeiv/kof/npc/p_minigunspin.mdl
models/kezaeiv/kof/npc/pit_drone.mdl
models/kezaeiv/kof/npc/ragh_aknah.mdl
models/kezaeiv/kof/npc/rgrunt.mdl
models/kezaeiv/kof/npc/rgruntf.mdl
models/kezaeiv/kof/npc/strooper.mdl
models/kezaeiv/kof/npc/tor.mdl
models/kezaeiv/kof/npc/torf.mdl
models/kezaeiv/kof/npc/v_minigun.mdl
models/kezaeiv/kof/npc/v_minigunblueshift.mdl
models/kezaeiv/kof/npc/v_minigunopfor.mdl
models/kezaeiv/kof/npc/voltigore.mdl
models/kezaeiv/kof/npc/w_minigun.mdl
models/kezaeiv/kof/npc/zombie.mdl
models/kezaeiv/kof/npc/zombie_barney.mdl
models/kezaeiv/kof/npc/zombie_soldier.mdl
models/oghs/cm/wep/p_2uzis.mdl
models/oghs/cm/wep/p_2uzis_gold.mdl
models/oghs/cm/wep/p_bgrap.mdl
models/oghs/cm/wep/p_displacer.mdl
models/oghs/cm/wep/p_pipe_wrench.mdl
models/oghs/cm/wep/p_shock.mdl
models/oghs/cm/wep/p_spore_launcher.mdl
models/oghs/cm/wep/p_uzi.mdl
models/oghs/cm/wep/p_uzi_gold.mdl
models/oghs/cm/wep/v_bgrap.mdl
models/oghs/cm/wep/v_displacer.mdl
models/oghs/cm/wep/v_pipe_wrench.mdl
models/oghs/cm/wep/v_spore_launcher.mdl
models/oghs/cm/wep/v_uzi.mdl
models/oghs/cm/wep/w_2uzis.mdl
models/oghs/cm/wep/w_2uzis_gold.mdl
models/oghs/cm/wep/w_bgrap.mdl
models/oghs/cm/wep/w_m40a1clip.mdl
models/oghs/cm/wep/w_pipe_wrench.mdl
models/oghs/cm/wep/w_saw_clip.mdl
models/oghs/cm/wep/w_shock.mdl
models/oghs/cm/wep/w_shock_rifle.mdl
models/oghs/cm/wep/w_spore_launcher.mdl
models/oghs/cm/wep/w_uzi.mdl
models/oghs/cm/wep/w_uzi_clip.mdl
models/oghs/cm/wep/w_uzi_gold.mdl
models/singularity/c_weps/misc/laser_stick_bl.mdl
models/singularity/c_weps/misc/laser_stick_bl2.mdl
models/singularity/c_weps/misc/laser_stick_grn.mdl
models/singularity/c_weps/misc/laser_stick_prpl.mdl
models/singularity/kz_npcs/islave_dammned.mdl
models/singularity/kz_npcs/pitcrab.mdl
models/singularity/misc/kz_mxa_box.mdl
models/singularity/misc/rockgibs_lightrock.mdl
sound/kezaeiv/misc/cp_nod_reinf.mp3
sound/kezaeiv/music/trbslsh_drug.ogg
sound/kezaeiv/music/trbslsh_lostconnection.ogg
sound/oghs/cs06/a!.wav
sound/oghs/cs06/badbone.wav
sound/oghs/cs06/bell.wav
sound/oghs/cs06/boing.wav
sound/oghs/cs06/crit.wav
sound/oghs/cs06/csm.wav
sound/oghs/cs06/cum.wav
sound/oghs/cs06/dross.wav
sound/oghs/cs06/fart.wav
sound/oghs/cs06/gay.wav
sound/oghs/cs06/headshot.wav
sound/oghs/cs06/pipe.wav
sound/oghs/cs06/pui.wav
sound/oghs/cs06/slip.wav
sound/oghs/cs06/tom2.wav
sound/oghs/cs06/wrong.wav
sound/oghs/cs06/zzz.wav
sound/singularity/c_wep/ammo/pku_ammo4.wav
sound/singularity/c_wep/ehve/roach_blast.wav
sound/singularity/c_wep/hblst/hb_beam_shot.wav
sound/singularity/c_wep/misc/enrg_hit.wav
sound/singularity/c_wep/xl2/xl2_shot.wav
sound/singularity/door/keyinserted.wav
sound/singularity/kof/ragh_aknah/atack1.wav
sound/singularity/kof/ragh_aknah/hurt2.wav
sound/singularity/kof/ragh_aknah/hurt3.wav
sound/singularity/kof/ragh_aknah/hurt4.wav
sound/singularity/kof/ragh_aknah/taunt.wav
sound/singularity/misc/kleerofski_laugh2.wav
sound/singularity/misc/kleerofski_laugh3.wav
sound/singularity/misc/kleerofski_laugh5.wav
sound/singularity/misc/nova_charge.wav
sound/singularity/misc/shockwave.wav
sound/singularity/misc/ss2_nade.wav
sound/singularity/misc/victory.wav
sound/singularity/npc/csgo_deag_shot.wav
sound/singularity/npc/dusk_shotgun_shot.wav
sound/singularity/npc/exp1.wav
sound/singularity/npc/exp3.wav
sound/singularity/npc/exp5.wav
sound/singularity/npc/hgrunt_3shot.wav
sound/singularity/npc/hl2_flesh_hit1.wav
sound/singularity/npc/hl2_flesh_hit2.wav
sound/singularity/npc/hl2_flesh_hit3.wav
sound/singularity/npc/igi2_dragunov_shot.wav
sound/singularity/npc/igi2_g36_shot.wav
sound/singularity/npc/quake3_grenade_shot.wav
sound/singularity/npc/quake4_plasma_shot.wav
sound/singularity/npc/starcraft_ghost_rifle.wav
sound/singularity/npc_pitcrab/hc_alert1.wav
sound/singularity/npc_pitcrab/hc_alert2.wav
sound/singularity/npc_pitcrab/hc_attack1.wav
sound/singularity/npc_pitcrab/hc_attack2.wav
sound/singularity/npc_pitcrab/hc_attack3.wav
sound/singularity/npc_pitcrab/hc_die1.wav
sound/singularity/npc_pitcrab/hc_die2.wav
sound/singularity/npc_pitcrab/hc_headbite.wav
sound/singularity/npc_pitcrab/hc_idle1.wav
sound/singularity/npc_pitcrab/hc_idle2.wav
sound/singularity/npc_pitcrab/hc_idle3.wav
sound/singularity/npc_pitcrab/hc_idle4.wav
sound/singularity/npc_pitcrab/hc_idle5.wav
sound/singularity/npc_pitcrab/hc_pain1.wav
sound/singularity/npc_pitcrab/hc_pain2.wav
sound/singularity/npc_pitcrab/hc_pain3.wav
sound/singularity/null.wav
sprites/singularity/fx/b-tele_prpl_bl.spr
sprites/singularity/fx/b-tele_prpl_pk.spr
sprites/singularity/fx/laser_crshr.spr
sprites/singularity/fx/strchs_sr_exp.spr
sprites/singularity/prtl/kz_exit2.spr
sprites/singularity/prtl/kz_exit4.spr
sprites/singularity/prtl/kz_exit6.spr
