// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

models/opm/astra.mdl
models/opm/barney_ak47.mdl
models/opm/barney_grunt.mdl
models/opm/barney_uzi.mdl
models/opm/blackjeep.mdl
models/opm/blackvan.mdl
models/opm/couch.mdl
models/opm/hevgrunt.mdl
models/opm/hydrant.mdl
models/opm/kosobar.mdl
models/opm/otis_m3.mdl
models/opm/p_knife.mdl
models/opm/p_uzi.mdl
models/opm/superrobo.mdl
models/opm/toyo.mdl
models/opm/tree4.mdl
models/opm/v_knife.mdl
models/opm/v_pipe_wrench.mdl
models/opm/v_uzi.mdl
models/opm/w_knife.mdl
models/opm/w_uzi.mdl
op_blackmesa.wad
sound/opm/intro.wav
sound/opm/pwrench_big_hitbod1.wav
sound/opm/pwrench_big_hitbod2.wav
sound/opm/pwrench_big_miss.wav
sound/opm/pwrench_hit1.wav
sound/opm/pwrench_hit2.wav
sound/opm/pwrench_hitbod1.wav
sound/opm/pwrench_hitbod2.wav
sound/opm/pwrench_hitbod3.wav
sound/opm/pwrench_miss1.wav
sound/opm/pwrench_miss2.wav
sound/opm/sci1_audio1.wav
sound/opm/sci2_audio1.wav
sound/opm/sci2_audio2.wav
sound/opm/sci3_audio1.wav
sound/opm/sci4_audio1.wav
sound/opm/sci4_audio2.wav
sound/weapons/ak47_magin.wav
sound/weapons/ak47_magout.wav
