// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

models/opm/astra.mdl
models/opm/barney_grunt.mdl
models/opm/blackjeep.mdl
models/opm/couch.mdl
models/opm/hgibs.mdl
models/opm/hydrant.mdl
models/opm/kosobar.mdl
models/opm/out/rock_japan.mdl
models/opm/out/rock_japan_rocks2.mdl
models/opm/out/xen_smallgrass1.mdl
models/opm/out/xen_smallgrass2.mdl
models/opm/p_knife.mdl
models/opm/p_uzi.mdl
models/opm/props/bathroom_toilet.mdl
models/opm/props/bottle_brown.mdl
models/opm/props/coffee_maker.mdl
models/opm/props/coffee_props-can.mdl
models/opm/props/coffee_props-cup.mdl
models/opm/props/coffee_props-sugar.mdl
models/opm/props/fan_ceiling.mdl
models/opm/props/hessi_heizung.mdl
models/opm/props/sink_small.mdl
models/opm/props/soda_fountain.mdl
models/opm/tree4.mdl
models/opm/v_knife.mdl
models/opm/v_pipe_wrench.mdl
models/opm/v_uzi.mdl
models/opm/w_knife.mdl
models/opm/w_uzi.mdl
op_blackmesa.wad
sound/opm/bling.wav
sound/opm/pwrench_big_hitbod1.wav
sound/opm/pwrench_big_hitbod2.wav
sound/opm/pwrench_big_miss.wav
sound/opm/pwrench_hit1.wav
sound/opm/pwrench_hit2.wav
sound/opm/pwrench_hitbod1.wav
sound/opm/pwrench_hitbod2.wav
sound/opm/pwrench_hitbod3.wav
sound/opm/pwrench_miss1.wav
sound/opm/pwrench_miss2.wav
sound/opm/water1.wav
sound/weapons/ak47_magin.wav
sound/weapons/ak47_magout.wav
