// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

apache.wad
models/opm/astra.mdl
models/opm/blackjeep.mdl
models/opm/blackvan.mdl
models/opm/couch.mdl
models/opm/hydrant.mdl
models/opm/p_knife.mdl
models/opm/robocontroller/controller.mdl
models/opm/robocontroller/controllert.mdl
models/opm/stukabat.mdl
models/opm/toyo.mdl
models/opm/tree4.mdl
models/opm/v_knife.mdl
models/opm/v_pipe_wrench.mdl
models/opm/vaz-2104.mdl
models/opm/w_knife.mdl
op_blackmesa.wad
sound/opm/pwrench_big_hitbod1.wav
sound/opm/pwrench_big_hitbod2.wav
sound/opm/pwrench_big_miss.wav
sound/opm/pwrench_hit1.wav
sound/opm/pwrench_hit2.wav
sound/opm/pwrench_hitbod1.wav
sound/opm/pwrench_hitbod2.wav
sound/opm/pwrench_hitbod3.wav
sound/opm/pwrench_miss1.wav
sound/opm/pwrench_miss2.wav
sound/stukabat/stkb_alert1.wav
sound/stukabat/stkb_alert2.wav
sound/stukabat/stkb_attack1.wav
sound/stukabat/stkb_attack2.wav
sound/stukabat/stkb_die1.wav
sound/stukabat/stkb_die2.wav
sound/stukabat/stkb_idle1.wav
sound/stukabat/stkb_idle2.wav
sound/stukabat/stkb_idle3.wav
sound/stukabat/stkb_idle4.wav
sound/stukabat/stkb_idle5.wav
