// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

models/opm/astra.mdl
models/opm/blackjeep.mdl
models/opm/blackvan.mdl
models/opm/couch.mdl
models/opm/hydrant.mdl
models/opm/kosobar.mdl
models/opm/out/bush1.mdl
models/opm/out/xen_smallgrass1.mdl
models/opm/out/xen_smallgrass2.mdl
models/opm/p_knife.mdl
models/opm/p_uzi.mdl
models/opm/scigrunt.mdl
models/opm/scislave/scislave.mdl
models/opm/toyo.mdl
models/opm/tree4.mdl
models/opm/v_knife.mdl
models/opm/v_pipe_wrench.mdl
models/opm/v_uzi.mdl
models/opm/vaz-2104.mdl
models/opm/w_knife.mdl
models/opm/w_uzi.mdl
models/opm/zombie/crowbar_slick.mdl
models/opm/zombie/wrench_luther.mdl
op_blackmesa.wad
sound/opm/map3/sci1_audio1.wav
sound/opm/map3/sci1_audio2.wav
sound/opm/map3/sci2_audio1.wav
sound/opm/pwrench_big_hitbod1.wav
sound/opm/pwrench_big_hitbod2.wav
sound/opm/pwrench_big_miss.wav
sound/opm/pwrench_hit1.wav
sound/opm/pwrench_hit2.wav
sound/opm/pwrench_hitbod1.wav
sound/opm/pwrench_hitbod2.wav
sound/opm/pwrench_hitbod3.wav
sound/opm/pwrench_miss1.wav
sound/opm/pwrench_miss2.wav
sound/scislave/slv_alert1.wav
sound/scislave/slv_alert3.wav
sound/scislave/slv_alert4.wav
sound/scislave/slv_die1.wav
sound/scislave/slv_die2.wav
sound/scislave/slv_pain1.wav
sound/scislave/slv_pain2.wav
sound/scislave/slv_word1.wav
sound/scislave/slv_word2.wav
sound/scislave/slv_word3.wav
sound/scislave/slv_word4.wav
sound/scislave/slv_word5.wav
sound/scislave/slv_word6.wav
sound/scislave/slv_word7.wav
sound/scislave/slv_word8.wav
sound/weapons/ak47_magin.wav
sound/weapons/ak47_magout.wav
