halflife.wad
liquids.wad
ra_quad.wad
models/quad_f/maiten/maiten_counter.mdl
models/quad_f/maiten/maiten_counter_players.mdl
models/quad_f/maiten/sig.mdl
models/quad_f/maiten/top.mdl
sound/buttons/button3.wav
sound/plats/talkmove2.wav
sound/plats/talkstop1.wav
sound/Angel/ra_alarm.mp3
sound/ra_quad/music01.mp3
sound/ra_quad/music02.ogg
sound/ra_quad/music03.mp3
sound/ra_quad/music04.mp3
sound/ra_quad/lonely.mp3
sound/ra_quad/alarm-clock-1.wav
sound/ra_quad/clock-ticking-1.wav
sound/ra_quad/portal_enter.wav
sound/ra_quad/portal_exit.wav
sound/ra_quad/portal_open.wav
sound/ra_quad/portal_shoot.wav
sprites/laserbeam.spr
