// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

events/muzzle_hgrunt_m16.txt
events/muzzle_hgrunt_m40a1.txt
events/muzzle_hgrunt_mp5.txt
events/muzzle_hgrunt_sg.txt
halflife.wad
liquids.wad
models/bigrat.mdl
models/error.mdl
models/hgibs.mdl
models/hlclassic/rpgrocket.mdl
models/hlclassic/w_chainammo.mdl
models/hlclassic/w_chainammot.mdl
models/hlclassic/w_shotbox.mdl
models/hlclassic/w_shotboxt.mdl
models/p_grenade.mdl
models/ragemap2023/alexc/coin_1.mdl
models/ragemap2023/alexc/coin_10.mdl
models/ragemap2023/alexc/coin_100.mdl
models/ragemap2023/alexc/coin_2.mdl
models/ragemap2023/alexc/coin_20.mdl
models/ragemap2023/alexc/coin_5.mdl
models/ragemap2023/alexc/coin_50.mdl
models/ragemap2023/gauna/hat_sun.mdl
models/ragemap2023/gauna/salt_wizard.mdl
models/ragemap2023/hezus/hat_alarm.mdl
models/ragemap2023/hezus/hat_box.mdl
models/ragemap2023/hezus/hat_bunny.mdl
models/ragemap2023/hezus/hat_fez.mdl
models/ragemap2023/hezus/hat_leprechaun.mdl
models/ragemap2023/hezus/hat_miner.mdl
models/ragemap2023/hezus/hat_pan.mdl
models/ragemap2023/hezus/hat_propellor.mdl
models/ragemap2023/hezus/hat_salt.mdl
models/ragemap2023/hezus/hat_sombrero.mdl
models/ragemap2023/hezus/hat_sun.mdl
models/ragemap2023/hezus/hat_tophat.mdl
models/ragemap2023/hezus/hat_trafficcone.mdl
models/ragemap2023/hezus/hat_ushanka.mdl
models/ragemap2023/hezus/hat_viking.mdl
models/ragemap2023/hezus/hat_wizard.mdl
models/ragemap2023/kezaeiv/ammo/energy.mdl
models/ragemap2023/kezaeiv/ammo/rockets.mdl
models/ragemap2023/kezaeiv/ammo/sniper.mdl
models/ragemap2023/kezaeiv/biomechanoid.mdl
models/ragemap2023/kezaeiv/controller.mdl
models/ragemap2023/kezaeiv/houndeye.mdl
models/ragemap2023/kezaeiv/kamikaze.mdl
models/ragemap2023/kezaeiv/kleer.mdl
models/ragemap2023/kezaeiv/knife/p_knife.mdl
models/ragemap2023/kezaeiv/knife/v_knife.mdl
models/ragemap2023/kezaeiv/knife/w_knife.mdl
models/ragemap2023/kezaeiv/limitless_potential.mdl
models/ragemap2023/kezaeiv/minigun/p_minigun.mdl
models/ragemap2023/kezaeiv/minigun/v_minigun.mdl
models/ragemap2023/kezaeiv/minigun/w_minigun.mdl
models/ragemap2023/kezaeiv/raptor/p_raptor.mdl
models/ragemap2023/kezaeiv/raptor/v_raptor.mdl
models/ragemap2023/kezaeiv/raptor/w_raptor.mdl
models/ragemap2023/kezaeiv/schofield/p_schofield.mdl
models/ragemap2023/kezaeiv/schofield/v_schofield.mdl
models/ragemap2023/kezaeiv/schofield/w_schofield.mdl
models/ragemap2023/kezaeiv/shotgun/p_shotgun.mdl
models/ragemap2023/kezaeiv/shotgun/v_shotgun.mdl
models/ragemap2023/kezaeiv/shotgun/w_shotgun.mdl
models/ragemap2023/kezaeiv/strooper.mdl
models/ragemap2023/kezaeiv/tommy/p_tommy.mdl
models/ragemap2023/kezaeiv/tommy/v_tommy.mdl
models/ragemap2023/kezaeiv/tommy/w_tommy.mdl
models/ragemap2023/kezaeiv/xl2/laser.mdl
models/ragemap2023/kezaeiv/xl2/p_xl2.mdl
models/ragemap2023/kezaeiv/xl2/v_xl2.mdl
models/ragemap2023/kezaeiv/xl2/w_xl2.mdl
models/ragemap2023/kezaeiv/xpml21/p_xpml21.mdl
models/ragemap2023/kezaeiv/xpml21/v_xpml21.mdl
models/ragemap2023/kezaeiv/xpml21/w_xpml21.mdl
models/v_grenade.mdl
models/w_357ammobox.mdl
models/w_grenade.mdl
nw.wad
sound/ambience/alien_builder.wav
sound/ambience/dronemachine1.wav
sound/ambience/dronemachine2.wav
sound/ambience/flameburst1.wav
sound/ambience/port_suckin1.wav
sound/ambience/siren.wav
sound/ambience/warn3.wav
sound/ambience/zapmachine.wav
sound/buttons/blip3.wav
sound/buttons/button1.wav
sound/buttons/button8.wav
sound/buttons/lightswitch2.wav
sound/common/bodysplat.wav
sound/common/null.wav
sound/debris/beamstart11.wav
sound/debris/beamstart6.wav
sound/debris/bustflesh1.wav
sound/hgrunt/gr_die1.wav
sound/hgrunt/gr_die2.wav
sound/hgrunt/gr_pain4.wav
sound/hlclassic/weapons/debris1.wav
sound/hlclassic/weapons/debris2.wav
sound/hlclassic/weapons/debris3.wav
sound/items/9mmclip1.wav
sound/items/clipinsert1.wav
sound/items/cliprelease1.wav
sound/items/gunpickup2.wav
sound/items/suitchargeok1.wav
sound/pitdrone/pit_drone_attack_spike1.wav
sound/pitdrone/pit_drone_die1.wav
sound/pitdrone/pit_drone_die2.wav
sound/pitdrone/pit_drone_die3.wav
sound/pitdrone/pit_drone_eat.wav
sound/pitdrone/pit_drone_hunt3.wav
sound/pitdrone/pit_drone_melee_attack1.wav
sound/pitdrone/pit_drone_melee_attack2.wav
sound/ragemap2023/alexc/dot.ogg
sound/ragemap2023/alexc/fill.ogg
sound/ragemap2023/alexc/pezz_-_star_paws.xm
sound/ragemap2023/Half-Life11.mp3
sound/ragemap2023/kezaeiv/colt.wav
sound/ragemap2023/kezaeiv/colt_rel.wav
sound/ragemap2023/kezaeiv/double.wav
sound/ragemap2023/kezaeiv/double_rel.wav
sound/ragemap2023/kezaeiv/expl.wav
sound/ragemap2023/kezaeiv/freedom.ogg
sound/ragemap2023/kezaeiv/knife.wav
sound/ragemap2023/kezaeiv/mini.wav
sound/ragemap2023/kezaeiv/mini_rtdn.wav
sound/ragemap2023/kezaeiv/mini_rtup.wav
sound/ragemap2023/kezaeiv/nade.wav
sound/ragemap2023/kezaeiv/nade_bounce.wav
sound/ragemap2023/kezaeiv/rocket.wav
sound/ragemap2023/kezaeiv/sam/am_i.ogg
sound/ragemap2023/kezaeiv/sam/doorman.ogg
sound/ragemap2023/kezaeiv/sam/fist.ogg
sound/ragemap2023/kezaeiv/sam/lets.ogg
sound/ragemap2023/kezaeiv/sam/ready_for_battle.ogg
sound/ragemap2023/kezaeiv/sam/yeehaw.ogg
sound/ragemap2023/kezaeiv/shotgun.wav
sound/ragemap2023/kezaeiv/sniper.wav
sound/ragemap2023/kezaeiv/thepit_fight.ogg
sound/ragemap2023/kezaeiv/thepit_peace.ogg
sound/ragemap2023/kezaeiv/tommy.wav
sound/ragemap2023/kezaeiv/wizard/wiz_applause.ogg
sound/ragemap2023/kezaeiv/wizard/wiz_boom.ogg
sound/ragemap2023/kezaeiv/wizard/wiz_levitate.ogg
sound/ragemap2023/kezaeiv/wizard/wiz_spawn.ogg
sound/ragemap2023/kezaeiv/wizard/wiz_spores.ogg
sound/ragemap2023/kezaeiv/wizard/wiz_taunt.ogg
sound/ragemap2023/kezaeiv/wizard/wiz_tp.ogg
sound/ragemap2023/kezaeiv/wizard/wiz_tpend.ogg
sound/ragemap2023/kezaeiv/xl2.wav
sound/ragemap2023/saltshaking_angry.mp3
sound/weapons/electro4.wav
sound/weapons/grenade_hit1.wav
sound/weapons/grenade_hit2.wav
sound/weapons/grenade_hit3.wav
sound/weapons/reload1.wav
sound/weapons/reload3.wav
sound/weapons/scock1.wav
sprites/640hud1.spr
sprites/640hud2.spr
sprites/640hud3.spr
sprites/640hud4.spr
sprites/640hud5.spr
sprites/640hud6.spr
sprites/640hud7.spr
sprites/640hudof01_displacer.spr
sprites/640hudof02_displacer.spr
sprites/640hudof03.spr
sprites/640hudof04.spr
sprites/640hudsc2.spr
sprites/animglow01.spr
sprites/blood.spr
sprites/bloodspray.spr
sprites/bubble.spr
sprites/exit1.spr
sprites/fire.spr
sprites/flare6.spr
sprites/glow01.spr
sprites/glow03.spr
sprites/hotglow.spr
sprites/laserbeam.spr
sprites/level_change.spr
sprites/lgtning.spr
sprites/MP5Flash.spr
sprites/muzzleflash3.spr
sprites/ragemap2023/channelicon_intro.spr
sprites/ragemap2023/channelicon_outro.spr
sprites/ragemap2023/ika/ika_silo1_l.spr
sprites/ragemap2023/ika/ika_silo1_r.spr
sprites/ragemap2023/ika/ika_silo2_l.spr
sprites/ragemap2023/ika/ika_silo2_r.spr
sprites/ragemap2023/ika/ika_silo3_l.spr
sprites/ragemap2023/ika/ika_silo3_r.spr
sprites/ragemap2023/ika/ika_silo4_l.spr
sprites/ragemap2023/ika/ika_silo4_r.spr
sprites/ragemap2023/ika/ika_silo_nav1a.spr
sprites/ragemap2023/ika/ika_silo_nav1b.spr
sprites/ragemap2023/ika/ika_silo_nav1c.spr
sprites/ragemap2023/ika/ika_silo_nav1d.spr
sprites/ragemap2023/ika/ika_silo_nav2a.spr
sprites/ragemap2023/ika/ika_silo_nav2b.spr
sprites/ragemap2023/ika/ika_silo_nav2c.spr
sprites/ragemap2023/ika/ika_silo_nav2d.spr
sprites/ragemap2023/ika_weapons/weapon_noisemaker.txt
sprites/ragemap2023/ika_weapons/weapon_noisenoreg.txt
sprites/ragemap2023/kezaeiv/640tfcminigun.spr
sprites/ragemap2023/kezaeiv/kezammo.spr
sprites/ragemap2023/kezaeiv/kezcrosshairs.spr
sprites/ragemap2023/kezaeiv/kezsniper.spr
sprites/ragemap2023/kezaeiv/weapon_kezaeiv_srs_knife.txt
sprites/ragemap2023/kezaeiv/weapon_kezaeiv_srs_minigun.txt
sprites/ragemap2023/kezaeiv/weapon_kezaeiv_srs_raptor.txt
sprites/ragemap2023/kezaeiv/weapon_kezaeiv_srs_schofield.txt
sprites/ragemap2023/kezaeiv/weapon_kezaeiv_srs_shotgun.txt
sprites/ragemap2023/kezaeiv/weapon_kezaeiv_srs_tommy.txt
sprites/ragemap2023/kezaeiv/weapon_kezaeiv_srs_xl2.txt
sprites/ragemap2023/kezaeiv/weapon_kezaeiv_srs_xpml21.txt
sprites/ragemap2023/kezaeiv/weapon_knife.spr
sprites/ragemap2023/ragemap2023.spr
sprites/SAWFlash.spr
sprites/SGFlash.spr
sprites/smoke.spr
sprites/steam1.spr
sprites/WXplo1.spr
sprites/yelflare1.spr
sprites/zbeam6.spr
sprites/zerogxplode.spr
xeno.wad
