// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

events/Muzzle_gluongun.txt
models/custom_weapons/biorifle/p_biorifle.mdl
models/custom_weapons/biorifle/v_biorifle.mdl
models/custom_weapons/biorifle/w_biomass.mdl
models/custom_weapons/gluongun/p_gluongun.mdl
models/custom_weapons/gluongun/v_gluongun.mdl
models/custom_weapons/gluongun/w_clip_gluoncell.mdl
models/custom_weapons/gluongun/w_gluongun.mdl
models/custom_weapons/hlwe/projectiles.mdl
models/custom_weapons/hlwe/w_clips_all.mdl
models/custom_weapons/rcshotgun/crate.mdl
models/custom_weapons/rcshotgun/miniforklift.mdl
models/custom_weapons/rcshotgun/shotgunsci.mdl
models/custom_weapons/rcshotgun/shotgunscit.mdl
models/custom_weapons/rcshotgun/shotgunsuit.mdl
models/custom_weapons/redeemer/p_redeemer.mdl
models/custom_weapons/redeemer/v_redeemer.mdl
models/custom_weapons/rg6/p_rg6.mdl
models/custom_weapons/rg6/v_rg6.mdl
models/custom_weapons/rg6/w_rg6.mdl
models/custom_weapons/rg6/w_rg6_grenade.mdl
models/custom_weapons/scipg/sci_rocket.mdl
models/custom_weapons/scipg/sci_rockett.mdl
models/ragemap2016/bananagarg.mdl
models/ragemap2016/Bananammo.mdl
models/ragemap2016/Bananammot.mdl
models/ragemap2016/bigbanana.mdl
models/ragemap2016/bunny.mdl
models/ragemap2016/cg_bantree01.mdl
models/ragemap2016/cg_bantree02.mdl
models/ragemap2016/nero/turret_sentry.mdl
models/ragemap2016/p_357.mdl
models/ragemap2016/p_crowbar.mdl
models/ragemap2016/v_357.mdl
models/ragemap2016/v_crowbar.mdl
models/ragemap2016/w_357.mdl
models/ragemap2016/w_crowbar.mdl
sound/custom_weapons/biorifle/biomass_exp.wav
sound/custom_weapons/biorifle/biorifle_dryfire.wav
sound/custom_weapons/biorifle/biorifle_fire.wav
sound/custom_weapons/biorifle/biorifle_magin.wav
sound/custom_weapons/biorifle/biorifle_magout.wav
sound/custom_weapons/biorifle/bustflesh1.wav
sound/custom_weapons/biorifle/bustflesh2.wav
sound/custom_weapons/gluongun/gluon_hitwall.wav
sound/custom_weapons/gluongun/gluon_hitwall2.wav
sound/custom_weapons/gluongun/gluongun_charge.wav
sound/custom_weapons/gluongun/gluongun_fire.wav
sound/custom_weapons/gluongun/gluongun_reload.wav
sound/custom_weapons/gluongun/gluongun_zap.wav
sound/custom_weapons/redeemer/redeemer_draw.wav
sound/custom_weapons/redeemer/redeemer_fire.wav
sound/custom_weapons/redeemer/redeemer_reload.wav
sound/custom_weapons/redeemer/redeemer_WH_explode.wav
sound/custom_weapons/redeemer/redeemer_WH_fly.wav
sound/custom_weapons/rg6/end.wav
sound/custom_weapons/rg6/fire1.wav
sound/custom_weapons/rg6/grenload.wav
sound/custom_weapons/rg6/next.wav
sound/custom_weapons/rg6/start.wav
sound/custom_weapons/scipg/kill.wav
sound/custom_weapons/scipg/sci_scream.wav
sound/ragemap2016/coin.wav
sound/ragemap2016/nero/aa.mp3
sound/ragemap2016/nero/aieou01.mp3
sound/ragemap2016/nero/aieou05.mp3
sound/ragemap2016/nero/cp01.mp3
sound/ragemap2016/nero/cp02.mp3
sound/ragemap2016/nero/football01.mp3
sound/ragemap2016/nero/football02.mp3
sound/ragemap2016/nero/football03.mp3
sound/ragemap2016/nero/football04.mp3
sound/ragemap2016/nero/gasthescis.mp3
sprites/custom_weapons/anim_spr2.spr
sprites/custom_weapons/anim_spr4.spr
sprites/custom_weapons/anim_spr6.spr
sprites/custom_weapons/biorifle.spr
sprites/custom_weapons/biorifle_crosshairs.spr
sprites/custom_weapons/gluongun.spr
sprites/custom_weapons/gluongun_crosshairs.spr
sprites/custom_weapons/gluongun_ring.spr
sprites/custom_weapons/gluongun_trail.spr
sprites/custom_weapons/redeemer.spr
sprites/custom_weapons/redeemer_crosshairs.spr
sprites/custom_weapons/rg6_cross.spr
sprites/custom_weapons/rg6_flame.spr
sprites/custom_weapons/rg6_weapon.spr
sprites/custom_weapons/scientist.spr
sprites/custom_weapons/spinning_coin.spr
sprites/custom_weapons/weapon_biorifle.txt
sprites/custom_weapons/weapon_gluongun.txt
sprites/custom_weapons/weapon_rcshotgun.txt
sprites/custom_weapons/weapon_redeemer.txt
sprites/custom_weapons/weapon_rg6.txt
sprites/custom_weapons/weapon_scientist.txt
sprites/gluon_muzzle.spr
sprites/ragemap2016/picardcoin.spr
