// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

models/REvil/Furnature/arcade5.mdl
models/REvil/Furnature/bed_empty-wood.mdl
models/REvil/Furnature/butts.mdl
models/REvil/Furnature/by_barrels_pallet.mdl
models/REvil/Furnature/cafetable.mdl
models/REvil/Furnature/car_police.mdl
models/REvil/Furnature/cashregister.mdl
models/REvil/Furnature/chair_cafe.mdl
models/REvil/Furnature/chair_office.mdl
models/REvil/Furnature/coat_rack.mdl
models/REvil/Furnature/coffee_maker.mdl
models/REvil/Furnature/corpse_male1.mdl
models/REvil/Furnature/corpse_male2.mdl
models/REvil/Furnature/couch_leather-black.mdl
models/REvil/Furnature/CrashedChopper.mdl
models/REvil/Furnature/dolly.mdl
models/REvil/Furnature/dresser3.mdl
models/REvil/Furnature/dumpster_lidclosed.mdl
models/REvil/Furnature/dumpster_lidclosed_green.mdl
models/REvil/Furnature/fh.mdl
models/REvil/Furnature/fmrx.mdl
models/REvil/Furnature/forklift.mdl
models/REvil/Furnature/generator.mdl
models/REvil/Furnature/machinery.mdl
models/REvil/Furnature/pallet_stack.mdl
models/REvil/Furnature/pc.mdl
models/REvil/Furnature/phone_pay-US.mdl
models/REvil/Furnature/refrigerator.mdl
models/REvil/Furnature/rubbish.mdl
models/REvil/Furnature/scaffold.mdl
models/REvil/Furnature/scaffold_short.mdl
models/REvil/Furnature/shower.mdl
models/REvil/Furnature/sink_small.mdl
models/REvil/Furnature/soda_fountain.mdl
models/REvil/Furnature/swat.mdl
models/REvil/Furnature/trash1.mdl
models/REvil/Furnature/trash3.mdl
models/REvil/Furnature/trash4.mdl
models/REvil/Furnature/trash_heap.mdl
models/REvil/Furnature/trash_trashcan.mdl
models/REvil/Furnature/vat_charlie.mdl
models/REvil/Furnature/wreckcar1.mdl
models/REvil/Furnature/wreckcar2.mdl
models/REvil/Furnature/wreckcar4.mdl
models/REvil/Furnature/wreckcar6.mdl
models/REvil/IModels/forkey.mdl
models/REvil/IModels/gascan.mdl
models/revil/IModels/healspray.mdl
models/revil/IModels/healsprayt.mdl
models/REvil/IModels/mo_disk.mdl
models/REvil/IModels/nailgun.mdl
models/REvil/IModels/toolbox.mdl
models/REvil/IModels/w_Security.mdl
models/revil/IModels/walkytalky.mdl
models/REvil/monsters/birkin.mdl
models/REvil/monsters/Civilian.mdl
models/REvil/monsters/Civilian2.mdl
models/REvil/monsters/Civilian3.mdl
models/REvil/monsters/czombie2.mdl
models/REvil/monsters/fcrimson.mdl
models/REvil/monsters/hunteralpha.mdl
models/REvil/monsters/lpz.mdl
models/REvil/monsters/lpzt.mdl
models/REvil/monsters/mrx.mdl
models/REvil/monsters/spider.mdl
models/REvil/monsters/tactical.mdl
models/REvil/monsters/zombie.mdl
models/REvil/WModels/1911/p_9mmhandgun.mdl
models/REvil/WModels/1911/v_9mmhandgun.mdl
models/REvil/WModels/357/v_357_v2.mdl
models/REvil/WModels/beretta/v_9mmhandgun.mdl
models/REvil/WModels/combatshotgun/p_shotgun.mdl
models/REvil/WModels/combatshotgun/v_shotgun.mdl
models/REvil/WModels/combatshotgun/w_shotgun.mdl
models/REvil/WModels/deagle/p_357.mdl
models/REvil/WModels/deagle/w_357.mdl
models/REvil/WModels/gauss/p_displacer.mdl
models/REvil/WModels/gauss/v_displacer.mdl
models/REvil/WModels/gauss/w_displacer.mdl
models/REvil/WModels/Grenade/p_grenade.mdl
models/REvil/WModels/Grenade/v_grenade_v2.mdl
models/REvil/WModels/Grenade/w_grenade.mdl
models/REvil/WModels/kick/p_null.mdl
models/REvil/WModels/kick/v_kick.mdl
models/REvil/WModels/m4/p_9mmar.mdl
models/REvil/WModels/m4/v_9mmar.mdl
models/REvil/WModels/m4/w_9mmar.mdl
models/REvil/WModels/Pump/p_shotgun.mdl
models/REvil/WModels/Pump/v_shotgun.mdl
models/REvil/WModels/Pump/w_shotgun.mdl
revil.wad
sound/hunter/alert.wav
sound/hunter/die.wav
sound/hunter/hit.wav
sound/hunter/null.wav
sound/hunter/pain.wav
sound/REsuperzombie/_period.wav
sound/REsuperzombie/claw_miss1.wav
sound/REsuperzombie/claw_miss2.wav
sound/REsuperzombie/claw_strike1.wav
sound/REsuperzombie/claw_strike2.wav
sound/REsuperzombie/claw_strike3.wav
sound/REsuperzombie/zo_alert10.wav
sound/REsuperzombie/zo_alert20.wav
sound/REsuperzombie/zo_alert30.wav
sound/REsuperzombie/zo_attack1.wav
sound/REsuperzombie/zo_attack2.wav
sound/REsuperzombie/zo_idle1.wav
sound/REsuperzombie/zo_idle2.wav
sound/REsuperzombie/zo_idle3.wav
sound/REsuperzombie/zo_idle4.wav
sound/REsuperzombie/zo_pain1.wav
sound/REsuperzombie/zo_pain2.wav
sound/revil/ambient/engine1.WAV
sound/revil/ambient/escapealarm.wav
sound/revil/ambient/fire2.WAV
sound/revil/ambient/gmonster_scream_1.wav
sound/revil/ambient/gmonster_scream_2.wav
sound/revil/ambient/machinepowerup.WAV
sound/revil/ambient/outambient.WAV
sound/revil/ambient/Sewer_Ambient.WAV
sound/revil/ambient/voxescapemessage.wav
sound/revil/music/contemplation1.WAV
sound/revil/music/finalboss.wav
sound/revil/music/finale.wav
sound/revil/music/mrx.wav
sound/revil/music/sewer1.WAV
sound/revil/music/suspense1.wav
sound/revil/music/suspense4.WAV
sound/revil/music/title.wav
sound/will/null.wav
