// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

events/devastator/muzzle_dev1.txt
events/devastator/muzzle_dev2.txt
events/devastator/muzzle_dev3.txt
events/devastator/muzzle_dev4.txt
events/muzzle_m41a.txt
events/muzzle_sentry_uzi.txt
gfx/env/3dmspacebk.tga
gfx/env/3dmspacedn.tga
gfx/env/3dmspaceft.tga
gfx/env/3dmspacelf.tga
gfx/env/3dmspacert.tga
gfx/env/3dmspaceup.tga
gfx/env/mars2invbk.tga
gfx/env/mars2invdn.tga
gfx/env/mars2invft.tga
gfx/env/mars2invlf.tga
gfx/env/mars2invrt.tga
gfx/env/mars2invup.tga
gfx/env/space_01bk.tga
gfx/env/space_01dn.tga
gfx/env/space_01ft.tga
gfx/env/space_01lf.tga
gfx/env/space_01rt.tga
gfx/env/space_01up.tga
gg_ng_hyperblast.wad
models/altoverride/p_deagle.mdl
models/altoverride/w_deagle.mdl
models/arcticescape/crate.mdl
models/arcticescape/oxygen.mdl
models/bbqwittehbear/items/bbqbox.mdl
models/biglolly_coop/w_weaponbox.mdl
models/caged/cg_spkrwire01.mdl
models/caged/cg_spkrwire_b_02.mdl
models/caged/cg_spkrwire_d_03.mdl
models/caged/cg_vatswire01.mdl
models/chan_space_escape/items/new_battery.mdl
models/chan_space_escape/items/new_obs.mdl
models/con3/crate2.mdl
models/con3/d3_shipping_crates.mdl
models/crimecity/props/coke_box.mdl
models/crimecity/props/crate.mdl
models/crystal_mission/box_apdd.mdl
models/crystal_mission/box_apdd2.mdl
models/crystal_mission/box_lab.mdl
models/davtrain/doughnut_box.mdl
models/decay/pizza_box.mdl
models/fi/props/electrical_box-closed.mdl
models/gunmanchronicles/dmlammo.mdl
models/gunshop/aa_breakerboxgroup_09_tch_smesh.mdl
models/gunshop/box_cod4_01.mdl
models/gunshop/box_cod4_02.mdl
models/hats/svencoop.mdl
models/infected/xcrate10d.mdl
models/lostmaze/furnitures/box_cardboard-group04.mdl
models/lostmaze/furnitures/box_x2_01.mdl
models/lostmaze/furnitures/crates02.mdl
models/lostmaze/furnitures/fnv_controlpanel.mdl
models/lostmaze/furnitures/girlbot.mdl
models/lostmaze/furnitures/hospitalpanel.mdl
models/lostmaze/furnitures/optable.mdl
models/lostmaze/furnitures/static_crate_40.mdl
models/lostmaze/furnitures/static_crate_48.mdl
models/lostmaze/furnitures/zps_crate.mdl
models/mustard/ingredientsbox.mdl
models/rede/isotopebox.mdl
models/rede/w_battery.mdl
models/rngstuff/kuilu/k_crate.mdl
models/sc_russian/128_fuse_set02.mdl
models/sc_russian/cc_oscilator.mdl
models/sc_russian/f3_boombox.mdl
models/sc_russian/medical/armbox.mdl
models/sc_russian/s_toolbox.mdl
models/scmod/alab/sven_cleansuit.mdl
models/scmod/alab/svensci.mdl
models/scmod/boderbot/3dsky/sky_earth_far.mdl
models/scmod/boderbot/3dsky/sky_facingworlds.mdl
models/scmod/boderbot/3dsky/sky_mars_far.mdl
models/scmod/boderbot/3dsky/sky_milky.mdl
models/scmod/boderbot/agrunt_robo.mdl
models/scmod/boderbot/apache_vger.mdl
models/scmod/boderbot/aphex.mdl
models/scmod/boderbot/cbarney.mdl
models/scmod/boderbot/controller_drone.mdl
models/scmod/boderbot/flagship.mdl
models/scmod/boderbot/guardian.mdl
models/scmod/boderbot/hev_opfor.mdl
models/scmod/boderbot/hevgeo.mdl
models/scmod/boderbot/hwgrunt_space.mdl
models/scmod/boderbot/items/w_weaponbox.mdl
models/scmod/boderbot/items/xanhead.mdl
models/scmod/boderbot/keendrugbox.mdl
models/scmod/boderbot/massn_hoverbike1.mdl
models/scmod/boderbot/massn_hoverbike2.mdl
models/scmod/boderbot/massnbomb.mdl
models/scmod/boderbot/medikit3.mdl
models/scmod/boderbot/miniguardian.mdl
models/scmod/boderbot/miniguardian_stand.mdl
models/scmod/boderbot/miniturret_360.mdl
models/scmod/boderbot/mothership.mdl
models/scmod/boderbot/props/af_gauges_box.mdl
models/scmod/boderbot/props/c2a1a_generator.mdl
models/scmod/boderbot/props/c3a2e_console.mdl
models/scmod/boderbot/props/cableindus.mdl
models/scmod/boderbot/props/cf_powercore.mdl
models/scmod/boderbot/props/console_large_01.mdl
models/scmod/boderbot/props/consolebay.mdl
models/scmod/boderbot/props/d3_maincontrol.mdl
models/scmod/boderbot/props/dissection_array01.mdl
models/scmod/boderbot/props/dropship_04.mdl
models/scmod/boderbot/props/eclt8.mdl
models/scmod/boderbot/props/f3_console01.mdl
models/scmod/boderbot/props/f3_console02.mdl
models/scmod/boderbot/props/gunrack1.mdl
models/scmod/boderbot/props/hl2_genconsole.mdl
models/scmod/boderbot/props/inventorystation.mdl
models/scmod/boderbot/props/monitor_four_side_post.mdl
models/scmod/boderbot/props/monitor_two_withkeyboard.mdl
models/scmod/boderbot/props/monitor_wall.mdl
models/scmod/boderbot/props/qe_console_large.mdl
models/scmod/boderbot/props/qe_console_tall.mdl
models/scmod/boderbot/props/qe_console_wide.mdl
models/scmod/boderbot/props/qe_console_wide2.mdl
models/scmod/boderbot/props/qe_primarylaser.mdl
models/scmod/boderbot/props/s_mainframe.mdl
models/scmod/boderbot/props/silo_monitor.mdl
models/scmod/boderbot/props/snark_pen_console.mdl
models/scmod/boderbot/props/tophat.mdl
models/scmod/boderbot/props/ut2k4_screen.mdl
models/scmod/boderbot/props/ut2k4_tank.mdl
models/scmod/boderbot/props/vgership.mdl
models/scmod/boderbot/props/wall_monitor.mdl
models/scmod/boderbot/props/xandead.mdl
models/scmod/boderbot/pvrobo.mdl
models/scmod/boderbot/richard_boderplane.mdl
models/scmod/boderbot/robobug2.mdl
models/scmod/boderbot/robocontroller.mdl
models/scmod/boderbot/robogarg.mdl
models/scmod/boderbot/robogibs.mdl
models/scmod/boderbot/rvrobo.mdl
models/scmod/boderbot/sebas.mdl
models/scmod/boderbot/turret_square.mdl
models/scmod/boderbot/ut2hfighter.mdl
models/scmod/boderbot/ut2k4_dropship.mdl
models/scmod/boderbot/ut2k4_raptor.mdl
models/scmod/boderbot/ut2k4_turret.mdl
models/scmod/boderbot/ut2sfighter.mdl
models/scmod/boderbot/vgergrunt.mdl
models/scmod/boderbot/vgersentry.mdl
models/scmod/boderbot/weapons/hornet.mdl
models/scmod/boderbot/weapons/p_grenade.mdl
models/scmod/boderbot/weapons/p_kamikaze_bomb.mdl
models/scmod/boderbot/weapons/p_saw.mdl
models/scmod/boderbot/weapons/spore_bean.mdl
models/scmod/boderbot/weapons/v_grenade.mdl
models/scmod/boderbot/weapons/v_saw.mdl
models/scmod/boderbot/weapons/w_grenade.mdl
models/scmod/boderbot/weapons/w_saw.mdl
models/scmod/boderbot/zombie_hev.mdl
models/scmod/exodus/robocontroller.mdl
models/scmod/hl2alpha/w_battery_usable.mdl
models/scmod/item_oxygen.mdl
models/scmod/jed/tfc_pyro.mdl
models/scmod/mduty/128_fuse_set01_b.mdl
models/scmod/phouse/w_battery_supercharge.mdl
models/scmod/secretcity/w_picardbox.mdl
models/scmod/sledge/p_squeak.mdl
models/scmod/sledge/robonest.mdl
models/scmod/sledge/robosnark.mdl
models/scmod/sledge/v_squeak.mdl
models/scmod/spaceprisoner/robozombie.mdl
models/scmod/weapons/aliens/m41a/p_m16.mdl
models/scmod/weapons/aliens/m41a/v_m16a2.mdl
models/scmod/weapons/aliens/m41a/w_m16.mdl
models/scmod/weapons/aliens/smartgun/p_minigunidle.mdl
models/scmod/weapons/aliens/smartgun/p_minigunspin.mdl
models/scmod/weapons/aliens/smartgun/v_minigun.mdl
models/scmod/weapons/aliens/smartgun/w_minigun.mdl
models/scmod/weapons/dmc/w_battery.mdl
models/scmod/weapons/tfc/glauncher/p_spore_launcher.mdl
models/scmod/weapons/tfc/glauncher/v_spore_launcher.mdl
models/scmod/weapons/tfc/glauncher/w_spore_launcher.mdl
models/scmod/weapons/ut99/pulsegun/v_egon.mdl
models/scmod/weapons/ut99/rocket/v_rpg.mdl
models/scmod/weapons/ut99/sniper/p_sniperrifle.mdl
models/scmod/weapons/ut99/sniper/v_sniperrifle.mdl
models/scmod/weapons/ut99/sniper/w_sniperrifle.mdl
models/scmod/weapons/ut99/ut2k4shock/v_gauss.mdl
models/scmod/weapons/ut99/w_battery.mdl
models/scmod/weapons/ut99/w_chainammo.mdl
models/scmod/weapons/ut99/w_medkit.mdl
models/scmod/weapons/ut99/w_rpgammo.mdl
models/scmod/weapons/ut99/w_shotbox.mdl
models/scmod/weapons/ut99/w_suit.mdl
models/scmod/weapons/ut99/w_weaponbox_sniper.mdl
models/scmod/zubben/barnspace.mdl
models/scmod/zubben/hgrunt.mdl
models/scmod/zubben/hgruntf.mdl
models/scmod/zubben/pirate.mdl
models/snarkbunk/monitor4.mdl
models/st_mission1/fuse.mdl
models/tb/pointless/jukebox.mdl
models/tb/pointless/server.mdl
models/tb/tb-maze8/box1.mdl
models/tb/tb-maze8/electrical-box.mdl
models/tb/tb-maze8/oxygen-bottle.mdl
models/toolbox.mdl
models/Trempler/industry2/crates.mdl
models/tucumanos/s-box.mdl
models/vendetta/items/w_medibox.mdl
models/xad_zubben/v_deagle.mdl
sound/_oxysound/uberlaser1.wav
sound/decay/colette/colette_attack1.wav
sound/mustardf/factorysounds/drone_loop.wav
sound/mustardf/factorysounds/switch.wav
sound/scmod/boderbot/dialogs/hyperblast/3781cry.ogg
sound/scmod/boderbot/dialogs/hyperblast/3781talk.ogg
sound/scmod/boderbot/dialogs/hyperblast/activatingdriveb.ogg
sound/scmod/boderbot/dialogs/hyperblast/alarm.ogg
sound/scmod/boderbot/dialogs/hyperblast/aphex2.ogg
sound/scmod/boderbot/dialogs/hyperblast/aphex3.ogg
sound/scmod/boderbot/dialogs/hyperblast/aphex4.ogg
sound/scmod/boderbot/dialogs/hyperblast/autopilot.ogg
sound/scmod/boderbot/dialogs/hyperblast/breach.ogg
sound/scmod/boderbot/dialogs/hyperblast/breakfromorbit.ogg
sound/scmod/boderbot/dialogs/hyperblast/clearfortakeoff.ogg
sound/scmod/boderbot/dialogs/hyperblast/countdown.ogg
sound/scmod/boderbot/dialogs/hyperblast/countdown2b.ogg
sound/scmod/boderbot/dialogs/hyperblast/danger.ogg
sound/scmod/boderbot/dialogs/hyperblast/docking.ogg
sound/scmod/boderbot/dialogs/hyperblast/evacuate.ogg
sound/scmod/boderbot/dialogs/hyperblast/forcefield0.ogg
sound/scmod/boderbot/dialogs/hyperblast/forcefield100.ogg
sound/scmod/boderbot/dialogs/hyperblast/forcefield25.ogg
sound/scmod/boderbot/dialogs/hyperblast/forcefield50.ogg
sound/scmod/boderbot/dialogs/hyperblast/forcefield75.ogg
sound/scmod/boderbot/dialogs/hyperblast/hyperdrive1.ogg
sound/scmod/boderbot/dialogs/hyperblast/hyperdrive2.ogg
sound/scmod/boderbot/dialogs/hyperblast/hyperdrive_off.ogg
sound/scmod/boderbot/dialogs/hyperblast/kanafire.ogg
sound/scmod/boderbot/dialogs/hyperblast/kanahelp1.ogg
sound/scmod/boderbot/dialogs/hyperblast/kanahelp2.ogg
sound/scmod/boderbot/dialogs/hyperblast/pirate2_fire.ogg
sound/scmod/boderbot/dialogs/hyperblast/pirate2_radio.ogg
sound/scmod/boderbot/dialogs/hyperblast/pirate3_cannons.ogg
sound/scmod/boderbot/dialogs/hyperblast/pirate4_avast.ogg
sound/scmod/boderbot/dialogs/hyperblast/pirate5_allyerbase.ogg
sound/scmod/boderbot/dialogs/hyperblast/pirate5_deadmen.ogg
sound/scmod/boderbot/dialogs/hyperblast/pirate5_defeat.ogg
sound/scmod/boderbot/dialogs/hyperblast/pirate5_newcrew.ogg
sound/scmod/boderbot/dialogs/hyperblast/pirate6_abandon.ogg
sound/scmod/boderbot/dialogs/hyperblast/pirateking_1.ogg
sound/scmod/boderbot/dialogs/hyperblast/readyfordeparture.ogg
sound/scmod/boderbot/dialogs/hyperblast/readyfortakeoff.ogg
sound/scmod/boderbot/dialogs/hyperblast/ricoeffects.ogg
sound/scmod/boderbot/dialogs/hyperblast/sebasready.ogg
sound/scmod/boderbot/dialogs/hyperblast/sebasrogue.ogg
sound/scmod/boderbot/dialogs/hyperblast/sebastalk1.ogg
sound/scmod/boderbot/dialogs/hyperblast/vgerradio1.ogg
sound/scmod/boderbot/dialogs/hyperblast/warning.ogg
sound/scmod/boderbot/dialogs/hyperblast/weaponsoff.ogg
sound/scmod/boderbot/dialogs/hyperblast/weaponson.ogg
sound/scmod/boderbot/dialogs/shipsfx.ogg
sound/scmod/boderbot/dialogs/xansay.ogg
sound/scmod/boderbot/foregone_loudspeakerz.ogg
sound/scmod/boderbot/foregone_maynard.ogg
sound/scmod/boderbot/godown16_nectoulin.ogg
sound/scmod/boderbot/godown_arcanedreams.ogg
sound/scmod/boderbot/godown_darkice.ogg
sound/scmod/boderbot/godown_lonniemaynard.ogg
sound/scmod/boderbot/hesapirate_extraterra_intro.ogg
sound/scmod/boderbot/hesapirate_extraterra_loop.ogg
sound/scmod/boderbot/hyperblast_crimzan_nectoulin.ogg
sound/scmod/boderbot/hyperblast_terrabite.ogg
sound/scmod/boderbot/utintro_ut3.ogg
sound/scmod/npcs/barniel/badfeeling.wav
sound/scmod/npcs/barniel/bn_bring.wav
sound/scmod/npcs/barniel/hoyes.wav
sound/scmod/npcs/barniel/humm.wav
sound/scmod/npcs/barniel/rightway.wav
sound/scmod/npcs/barniel/seelater.wav
sound/scmod/npcs/barniel/seeya.wav
sound/scmod/npcs/barniel/seeyoulater.wav
sound/scmod/npcs/barniel/stop1.wav
sound/scmod/npcs/barniel/teamup1.wav
sound/scmod/npcs/barniel/teamup2.wav
sound/scmod/npcs/barniel/waitin.wav
sound/scmod/npcs/barniel/yessir.wav
sound/scmod/npcs/female_massn/of2a5_bo01.ogg
sound/scmod/npcs/female_massn/of2a5_bo02.ogg
sound/scmod/npcs/female_massn/of2a5_bo03.ogg
sound/scmod/npcs/female_massn/of6a2_bo01.ogg
sound/scmod/npcs/female_massn/of6a2_bo02.ogg
sound/scmod/npcs/female_massn/of6a2_bo03.ogg
sound/scmod/npcs/robosnark/sqk_blast1.ogg
sound/scmod/npcs/robosnark/sqk_deploy1.ogg
sound/scmod/npcs/robosnark/sqk_die1.ogg
sound/scmod/npcs/robosnark/sqk_hunt1.ogg
sound/scmod/npcs/robosnark/sqk_hunt2.ogg
sound/scmod/npcs/robosnark/sqk_hunt3.ogg
sound/scmod/weapons/ut99/357_shot1.wav
sound/scmod/weapons/ut99/5health.wav
sound/scmod/weapons/ut99/5healthres.wav
sound/scmod/weapons/ut99/hks2.wav
sound/scmod/weapons/ut99/smallmedkit1.wav
sound/unreal_vox/vox_firstblood.ogg
sound/unreal_vox/vox_instagib.ogg
sound/weapons/hydra/activate.wav
sound/weapons/hydra/deploy.wav
sound/weapons/m41a/boltpull.wav
sound/weapons/m41a/magin.wav
sound/weapons/m41a/magout.wav
sound/weapons/m41a/pumpback.wav
sound/weapons/m41a/pumpforth.wav
sound/weapons/m41a_lc/m41a_single.wav
sound/weapons/mgsm_clipin1.wav
sound/weapons/mgsm_clipin2.wav
sound/weapons/mgsm_clipout1.wav
sound/weapons/mgsm_clipout2.wav
sound/weapons/mgsm_draw.wav
sound/xad/oldcocking.wav
sound/xad/oldcocking2.wav
sound/xad/oldshot.wav
sound/xad/uclick.wav
sprites/animsparkx.spr
sprites/chan_space/items/batv2.spr
sprites/chan_space/items/heavy.spr
sprites/custom_weapons/cso/weapon_beamsword.txt
sprites/custom_weapons/cso/weapon_ethereal.txt
sprites/custom_weapons/cso/weapon_qbarrel.txt
sprites/devastator/1.spr
sprites/devastator/2.spr
sprites/devastator/3.spr
sprites/devastator/4.spr
sprites/flame1.spr
sprites/flame3.spr
sprites/flame4.spr
sprites/flame5.spr
sprites/gunmanchronicles/cust_2GaussPistolSniper.txt
sprites/gunmanchronicles/weapon_gausspistol.txt
sprites/gunmanchronicles/weapon_gcminigun.txt
sprites/ins2/cbn/weapon_ins2c96carb.txt
sprites/ins2/hdg/weapon_ins2c96.txt
sprites/nih/mustard/repair.spr
sprites/poke646/levelchange.spr
sprites/quake1/hudlgammo.spr
sprites/ragemap2022/erty_oxygen.spr
sprites/scmod/boderbot/reload.spr
sprites/scmod/boderbot/weapon_hlhornetgun.txt
sprites/scmod/cso/weapon_ofshockrifle.txt
sprites/scmod/phouse/ammo.spr
sprites/scmod/superweapons/weapon_gluongun.txt
sprites/scmod/ut99//weapon_ofeagle.txt
sprites/scmod/ut99/reticle.spr
sprites/scmod/ut99/sniper.spr
sprites/scmod/ut99/weapon_biorifle.txt
sprites/scmod/ut99/weapon_clgauss.txt
sprites/scmod/ut99/weapon_csocrossbow.txt
sprites/scmod/ut99/weapon_cursed_e11.txt
sprites/scmod/ut99/weapon_egon.txt
sprites/scmod/ut99/weapon_elites.txt
sprites/scmod/ut99/weapon_hlmp5.txt
sprites/scmod/ut99/weapon_hlnuked_rpg.txt
sprites/scmod/ut99/weapon_hlshotgun.txt
sprites/scmod/ut99/weapon_plasmagun.txt
sprites/scmod/ut99/weapon_redeemer.txt
sprites/scmod/ut99/weapon_shuriken.txt
sprites/scmod/ut99/weapon_sniperrifle.txt
sprites/uexplo.spr
sprites/wpn/weapon_dualkriss.txt
sprites/wpn/weapon_hkmp5.txt
torntextures.wad
