// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

events/devastator/muzzle_dev1.txt
events/devastator/muzzle_dev2.txt
events/devastator/muzzle_dev3.txt
events/devastator/muzzle_dev4.txt
events/muzzle_m41a.txt
events/muzzle_sentry_uzi.txt
gfx/env/space_01bk.tga
gfx/env/space_01dn.tga
gfx/env/space_01ft.tga
gfx/env/space_01lf.tga
gfx/env/space_01rt.tga
gfx/env/space_01up.tga
models/altoverride/p_deagle.mdl
models/altoverride/w_deagle.mdl
models/chan_space_escape/items/new_obs.mdl
models/cnc/infectgonome.mdl
models/crimecity/rgrunt.mdl
models/custom_weapons/cso/w_sfsword.mdl
models/decay/health_charger_body.mdl
models/gunmanchronicles/dmlammo.mdl
models/gunmanchronicles/guassammo.mdl
models/gunmanchronicles/mechammo.mdl
models/gunmanchronicles/w_gauss.mdl
models/gunmanchronicles/w_mechagun.mdl
models/ragemap2016/friendlygonome2.mdl
models/residuallife/gonome.mdl
models/ressya_no_tabi/dorobo_massn.mdl
models/scmod/alab/sven_cleansuit.mdl
models/scmod/alab/svensci.mdl
models/scmod/boderbot/3dsky/sky_mars_far.mdl
models/scmod/boderbot/3dsky/vikingship2.mdl
models/scmod/boderbot/agrunt_robo.mdl
models/scmod/boderbot/agruntf_robo.mdl
models/scmod/boderbot/bean_sentry_mk2.mdl
models/scmod/boderbot/bgman.mdl
models/scmod/boderbot/cbarney.mdl
models/scmod/boderbot/dino1_fixed.mdl
models/scmod/boderbot/dino2_fixed.mdl
models/scmod/boderbot/fartasaur.mdl
models/scmod/boderbot/flagship.mdl
models/scmod/boderbot/garg_flamerbot.mdl
models/scmod/boderbot/hev_hgrunt.mdl
models/scmod/boderbot/hev_opfor.mdl
models/scmod/boderbot/hevgeo.mdl
models/scmod/boderbot/hwgrunt_robofix.mdl
models/scmod/boderbot/hwgrunt_space.mdl
models/scmod/boderbot/hwrobo.mdl
models/scmod/boderbot/items/w_weaponbox.mdl
models/scmod/boderbot/massnbomb.mdl
models/scmod/boderbot/medikit3.mdl
models/scmod/boderbot/microturret_360.mdl
models/scmod/boderbot/miniturret_360.mdl
models/scmod/boderbot/props/crystalut.mdl
models/scmod/boderbot/props/gunrack1.mdl
models/scmod/boderbot/props/ladder_120.mdl
models/scmod/boderbot/props/pipe2.mdl
models/scmod/boderbot/props/pipe5.mdl
models/scmod/boderbot/props/pipe6.mdl
models/scmod/boderbot/props/robotcobra.mdl
models/scmod/boderbot/props/ut2k4_powernode.mdl
models/scmod/boderbot/props/wall_scan.mdl
models/scmod/boderbot/props/ze_light.mdl
models/scmod/boderbot/props/ze_packspace_v3.mdl
models/scmod/boderbot/pvrobo.mdl
models/scmod/boderbot/robobug2.mdl
models/scmod/boderbot/robogarg.mdl
models/scmod/boderbot/robogibs.mdl
models/scmod/boderbot/runethunder.mdl
models/scmod/boderbot/rvrobo.mdl
models/scmod/boderbot/sentry.mdl
models/scmod/boderbot/tank_turret.mdl
models/scmod/boderbot/tank_turret_only.mdl
models/scmod/boderbot/tankwheels_rgrunt.mdl
models/scmod/boderbot/turret_square.mdl
models/scmod/boderbot/vgergrunt.mdl
models/scmod/boderbot/vgersentry.mdl
models/scmod/boderbot/weapons/hornet.mdl
models/scmod/boderbot/weapons/p_grenade.mdl
models/scmod/boderbot/weapons/p_kamikaze_bomb.mdl
models/scmod/boderbot/weapons/p_saw.mdl
models/scmod/boderbot/weapons/spore_bean.mdl
models/scmod/boderbot/weapons/v_grenade.mdl
models/scmod/boderbot/weapons/v_saw.mdl
models/scmod/boderbot/weapons/w_grenade.mdl
models/scmod/boderbot/weapons/w_saw.mdl
models/scmod/boderbot/xvenwing.mdl
models/scmod/boderbot/zombie_hev.mdl
models/scmod/exodus/robocontroller.mdl
models/scmod/item_security.mdl
models/scmod/jed/tfc_pyro.mdl
models/scmod/npcs/garg/aperture.mdl
models/scmod/npcs/hwgr/sixcentgeorge.mdl
models/scmod/npcs/zombie/crouchsoft.mdl
models/scmod/npcs/zombie/ezbakeoven.mdl
models/scmod/npcs/zombie/thebard.mdl
models/scmod/npcs/zombie/wolf.mdl
models/scmod/opbt/hwgrunt_robofix.mdl
models/scmod/opbt/w_dispenser.mdl
models/scmod/sledge/p_squeak.mdl
models/scmod/sledge/robonest.mdl
models/scmod/sledge/robosnark.mdl
models/scmod/sledge/v_squeak.mdl
models/scmod/spaceprisoner/robozombie.mdl
models/scmod/weapons/aliens/m41a/p_m16.mdl
models/scmod/weapons/aliens/m41a/v_m16a2.mdl
models/scmod/weapons/aliens/m41a/w_m16.mdl
models/scmod/weapons/aliens/smartgun/p_minigunidle.mdl
models/scmod/weapons/aliens/smartgun/p_minigunspin.mdl
models/scmod/weapons/aliens/smartgun/v_minigun.mdl
models/scmod/weapons/aliens/smartgun/w_minigun.mdl
models/scmod/weapons/tfc/glauncher/p_spore_launcher.mdl
models/scmod/weapons/tfc/glauncher/v_spore_launcher.mdl
models/scmod/weapons/tfc/glauncher/w_spore_launcher.mdl
models/scmod/weapons/ut99/biorifle/w_biomass.mdl
models/scmod/weapons/ut99/biorifle/w_biorifle.mdl
models/scmod/weapons/ut99/pulsegun/v_egon.mdl
models/scmod/weapons/ut99/rocket/v_rpg.mdl
models/scmod/weapons/ut99/sniper/p_sniperrifle.mdl
models/scmod/weapons/ut99/sniper/v_sniperrifle.mdl
models/scmod/weapons/ut99/sniper/w_sniperrifle.mdl
models/scmod/weapons/ut99/ut2k4shock/v_gauss.mdl
models/scmod/weapons/ut99/w_battery.mdl
models/scmod/weapons/ut99/w_chainammo.mdl
models/scmod/weapons/ut99/w_medkit.mdl
models/scmod/weapons/ut99/w_rpgammo.mdl
models/scmod/weapons/ut99/w_shotbox.mdl
models/scmod/weapons/ut99/w_suit.mdl
models/scmod/weapons/ut99/w_weaponbox_sniper.mdl
models/scmod/zubben/barnspace.mdl
models/scmod/zubben/hgrunt.mdl
models/scmod/zubben/hgruntf.mdl
models/scmod/zubben/pirate.mdl
models/scmod/zubben/rgrunt.mdl
models/stream/rgrunt.mdl
models/stream/rgrunt_blue.mdl
models/toolbox.mdl
models/xad_zubben/v_deagle.mdl
ng_deck16.wad
richard_boderbot.wad
sound/jzombie/rex/alert1.wav
sound/jzombie/rex/alert2.wav
sound/jzombie/rex/alert3.wav
sound/jzombie/rex/attack1.wav
sound/jzombie/rex/attack2.wav
sound/jzombie/rex/attack3.wav
sound/jzombie/rex/breathe1.wav
sound/jzombie/rex/breathe2.wav
sound/jzombie/rex/breathe3.wav
sound/jzombie/rex/die1.wav
sound/jzombie/rex/die2.wav
sound/jzombie/rex/idle1.wav
sound/jzombie/rex/idle2.wav
sound/jzombie/rex/idle3.wav
sound/jzombie/rex/idle4.wav
sound/jzombie/rex/idle5.wav
sound/jzombie/rex/pain1.wav
sound/jzombie/rex/pain2.wav
sound/jzombie/rex/pain3.wav
sound/jzombie/rex/step1.wav
sound/jzombie/rex/step2.wav
sound/jzombie/zombie/alert.wav
sound/jzombie/zombie/attack.wav
sound/jzombie/zombie/attack2.wav
sound/jzombie/zombie/attack3.wav
sound/jzombie/zombie/chew.wav
sound/jzombie/zombie/idle.wav
sound/jzombie/zombie/idle2.wav
sound/mustardf/factorysounds/drone_loop.wav
sound/scmod/boderbot/deck16/aslime2.wav
sound/scmod/boderbot/deck16/down.wav
sound/scmod/boderbot/deck16/up.wav
sound/scmod/boderbot/dialogs/dropship_robotradio.ogg
sound/scmod/boderbot/dialogs/gooboss.ogg
sound/scmod/boderbot/dialogs/hyperblast/autopilot.ogg
sound/scmod/boderbot/dialogs/hyperblast/pirate1_board.ogg
sound/scmod/boderbot/dialogs/intruder1.ogg
sound/scmod/boderbot/dialogs/intruder2.ogg
sound/scmod/boderbot/dialogs/intruder3.ogg
sound/scmod/boderbot/dialogs/miniboss_taunt1.ogg
sound/scmod/boderbot/dialogs/sniper_go.ogg
sound/scmod/boderbot/dialogs/sniper_r0.ogg
sound/scmod/boderbot/dialogs/trashmobs/kamikazes.ogg
sound/scmod/boderbot/dialogs/trashmobs/vger_taunt1.ogg
sound/scmod/boderbot/dialogs/trashmobs/vger_taunt2.ogg
sound/scmod/boderbot/dialogs/vger_topirates.ogg
sound/scmod/boderbot/dialogs/vox/vox_1.ogg
sound/scmod/boderbot/dialogs/vox/vox_2.ogg
sound/scmod/boderbot/dialogs/vox/vox_3.ogg
sound/scmod/boderbot/dialogs/vox/vox_4.ogg
sound/scmod/boderbot/dialogs/vox/vox_5.ogg
sound/scmod/boderbot/dialogs/vox/vox_6.ogg
sound/scmod/boderbot/dialogs/vox/vox_7.ogg
sound/scmod/boderbot/dialogs/vox/vox_8.ogg
sound/scmod/boderbot/dialogs/vox/vox_9.ogg
sound/scmod/boderbot/firebreath_darkice.ogg
sound/scmod/boderbot/godown_d3stra.ogg
sound/scmod/boderbot/godown_lix.ogg
sound/scmod/boderbot/razorback_lonniemaynard.ogg
sound/scmod/boderbot/razorback_mloudspeakerz.ogg
sound/scmod/boderbot/saveme_nectoulin.ogg
sound/scmod/boderbot/saveme_tmx.ogg
sound/scmod/boderbot/thecourse_nectoulin.ogg
sound/scmod/boderbot/ze_space/ze_alert.ogg
sound/scmod/boderbot/ze_space/ze_doormove2.ogg
sound/scmod/boderbot/ze_space/ze_gas.ogg
sound/scmod/boderbot/ze_space/ze_pipe.ogg
sound/scmod/boderbot/ze_space/ze_windcycle.ogg
sound/scmod/boderbot/ze_space/ze_windv2.ogg
sound/scmod/npcs/fartasaur/attacking1.wav
sound/scmod/npcs/fartasaur/attacking2.wav
sound/scmod/npcs/fartasaur/flames_run.wav
sound/scmod/npcs/robosnark/sqk_blast1.ogg
sound/scmod/npcs/robosnark/sqk_deploy1.ogg
sound/scmod/npcs/robosnark/sqk_die1.ogg
sound/scmod/npcs/robosnark/sqk_hunt1.ogg
sound/scmod/npcs/robosnark/sqk_hunt2.ogg
sound/scmod/npcs/robosnark/sqk_hunt3.ogg
sound/scmod/weapons/ut99/100health.wav
sound/scmod/weapons/ut99/100healthres.wav
sound/scmod/weapons/ut99/357_shot1.wav
sound/scmod/weapons/ut99/5health.wav
sound/scmod/weapons/ut99/5healthres.wav
sound/scmod/weapons/ut99/hks2.wav
sound/scmod/weapons/ut99/smallmedkit1.wav
sound/unreal_vox/vox_doublekill.ogg
sound/unreal_vox/vox_flakmonkey.ogg
sound/unreal_vox/vox_hattrick.ogg
sound/unreal_vox/vox_killingspree.ogg
sound/unreal_vox/vox_megakill.ogg
sound/unreal_vox/vox_multikill.ogg
sound/unreal_vox/vox_rampage.ogg
sound/unreal_vox/vox_ultrakill.ogg
sound/weapons/hydra/activate.wav
sound/weapons/hydra/deploy.wav
sound/weapons/m41a/boltpull.wav
sound/weapons/m41a/magin.wav
sound/weapons/m41a/magout.wav
sound/weapons/m41a/pumpback.wav
sound/weapons/m41a/pumpforth.wav
sound/weapons/m41a_lc/m41a_single.wav
sound/weapons/mgsm_clipin1.wav
sound/weapons/mgsm_clipin2.wav
sound/weapons/mgsm_clipout1.wav
sound/weapons/mgsm_clipout2.wav
sound/weapons/mgsm_draw.wav
sound/wheelchair/wheelchair_jog.wav
sound/wheelchair/wheelchair_walk.wav
sound/xad/oldcocking.wav
sound/xad/oldcocking2.wav
sound/xad/oldshot.wav
sound/xad/uclick.wav
sprites/custom_weapons/cso/weapon_beamsword.txt
sprites/custom_weapons/cso/weapon_ethereal.txt
sprites/custom_weapons/cso/weapon_qbarrel.txt
sprites/devastator/1.spr
sprites/devastator/2.spr
sprites/devastator/3.spr
sprites/devastator/4.spr
sprites/gunmanchronicles/cust_2GaussPistolSniper.txt
sprites/gunmanchronicles/weapon_gausspistol.txt
sprites/gunmanchronicles/weapon_gcminigun.txt
sprites/ins2/cbn/weapon_ins2c96carb.txt
sprites/ins2/hdg/weapon_ins2c96.txt
sprites/poke646/checkpoint.spr
sprites/poke646/levelchange.spr
sprites/portal_house/hud_of/640hud7of.spr
sprites/portal_house/hud_of/ofch1.spr
sprites/quake1/hudgl.spr
sprites/scmod/aliens/chronosceptor.spr
sprites/scmod/aliens/weapon_minigun.txt
sprites/scmod/boderbot/weapon_hlhornetgun.txt
sprites/scmod/cso/weapon_m249.txt
sprites/scmod/cso/weapon_ofshockrifle.txt
sprites/scmod/cso/wpn_devastator.spr
sprites/scmod/item_keycard.spr
sprites/scmod/phouse/640hudas1.spr
sprites/scmod/phouse/640hudas4.spr
sprites/scmod/phouse/weapon_m16.txt
sprites/scmod/superweapons/weapon_gluongun.txt
sprites/scmod/tfc/weapon_sporelauncher.txt
sprites/scmod/ut99//weapon_ofeagle.txt
sprites/scmod/ut99/reticle.spr
sprites/scmod/ut99/sniper.spr
sprites/scmod/ut99/weapon_biorifle.txt
sprites/scmod/ut99/weapon_clgauss.txt
sprites/scmod/ut99/weapon_csocrossbow.txt
sprites/scmod/ut99/weapon_cursed_e11.txt
sprites/scmod/ut99/weapon_egon.txt
sprites/scmod/ut99/weapon_elites.txt
sprites/scmod/ut99/weapon_gauss.txt
sprites/scmod/ut99/weapon_hlmp5.txt
sprites/scmod/ut99/weapon_hlnuked_rpg.txt
sprites/scmod/ut99/weapon_hlshotgun.txt
sprites/scmod/ut99/weapon_ofeagle.txt
sprites/scmod/ut99/weapon_plasmagun.txt
sprites/scmod/ut99/weapon_redeemer.txt
sprites/scmod/ut99/weapon_shuriken.txt
sprites/scmod/ut99/weapon_sniperrifle.txt
sprites/wpn/weapon_dualkriss.txt
sprites/wpn/weapon_hkmp5.txt
