// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

events/devastator/muzzle_dev1.txt
events/devastator/muzzle_dev2.txt
events/devastator/muzzle_dev3.txt
events/devastator/muzzle_dev4.txt
events/muzzle_m41a.txt
gfx/env/space_01bk.tga
gfx/env/space_01dn.tga
gfx/env/space_01ft.tga
gfx/env/space_01lf.tga
gfx/env/space_01rt.tga
gfx/env/space_01up.tga
models/altoverride/p_deagle.mdl
models/altoverride/w_deagle.mdl
models/chan_space_escape/items/new_obs.mdl
models/greysnake/new/snow_sentry.mdl
models/greysnake/new/snow_turret.mdl
models/gunmanchronicles/dmlammo.mdl
models/ragemap2016/shadow.mdl
models/scmod/alab/sven_cleansuit.mdl
models/scmod/alab/svensci.mdl
models/scmod/boderbot/3dsky/sky_mars_far.mdl
models/scmod/boderbot/3dsky/vikingship.mdl
models/scmod/boderbot/3dsky/vikingship2.mdl
models/scmod/boderbot/agrunt_robo.mdl
models/scmod/boderbot/apache_robot.mdl
models/scmod/boderbot/bigturret.mdl
models/scmod/boderbot/bvrobo.mdl
models/scmod/boderbot/cbarney.mdl
models/scmod/boderbot/flagship.mdl
models/scmod/boderbot/frel20.mdl
models/scmod/boderbot/gvrobo.mdl
models/scmod/boderbot/hev_hgrunt.mdl
models/scmod/boderbot/hev_opfor.mdl
models/scmod/boderbot/hwgrunt_space.mdl
models/scmod/boderbot/hwrobo.mdl
models/scmod/boderbot/items/w_weaponbox.mdl
models/scmod/boderbot/jaegermech.mdl
models/scmod/boderbot/kerncore11037.mdl
models/scmod/boderbot/kvrobo.mdl
models/scmod/boderbot/loader_legs.mdl
models/scmod/boderbot/massnbomb.mdl
models/scmod/boderbot/miniturret_360.mdl
models/scmod/boderbot/omega.mdl
models/scmod/boderbot/parabola.mdl
models/scmod/boderbot/props/menkey_crash.mdl
models/scmod/boderbot/props/sven_keypad.mdl
models/scmod/boderbot/props/ut2k4_powernode.mdl
models/scmod/boderbot/puchi20.mdl
models/scmod/boderbot/pvrobo.mdl
models/scmod/boderbot/robobug2.mdl
models/scmod/boderbot/robocontroller.mdl
models/scmod/boderbot/robocontroller_boss.mdl
models/scmod/boderbot/robogarg.mdl
models/scmod/boderbot/robogibs.mdl
models/scmod/boderbot/rvrobo.mdl
models/scmod/boderbot/soctomv2.mdl
models/scmod/boderbot/turret_square.mdl
models/scmod/boderbot/vgergrunt.mdl
models/scmod/boderbot/vgerholo.mdl
models/scmod/boderbot/vgersentry.mdl
models/scmod/boderbot/weapons/hornet.mdl
models/scmod/boderbot/weapons/p_grenade.mdl
models/scmod/boderbot/weapons/p_kamikaze_bomb.mdl
models/scmod/boderbot/weapons/p_saw.mdl
models/scmod/boderbot/weapons/spore_bean.mdl
models/scmod/boderbot/weapons/v_grenade.mdl
models/scmod/boderbot/weapons/v_saw.mdl
models/scmod/boderbot/weapons/w_grenade.mdl
models/scmod/boderbot/weapons/w_saw.mdl
models/scmod/boderbot/zombie_hev.mdl
models/scmod/exodus/robocontroller.mdl
models/scmod/item_doorjammer.mdl
models/scmod/jed/tfc_pyro.mdl
models/scmod/npcs/barnotis/ambientimpact.mdl
models/scmod/npcs/barnotis/cadaver.mdl
models/scmod/npcs/barnotis/dark4557.mdl
models/scmod/npcs/barnotis/h4wk.mdl
models/scmod/npcs/barnotis/solokiller.mdl
models/scmod/npcs/barnotis/taehl.mdl
models/scmod/npcs/bbgarg/teddybear.mdl
models/scmod/npcs/bbhc/dynamite.mdl
models/scmod/npcs/bsquid/totac.mdl
models/scmod/npcs/hc/jumpybean.mdl
models/scmod/npcs/hgrunt/gore.mdl
models/scmod/npcs/hgrunt/rum.mdl
models/scmod/npcs/houndeye/makaber.mdl
models/scmod/npcs/houndeye/verycoolcat.mdl
models/scmod/npcs/op4/hbandrew.mdl
models/scmod/npcs/op4/hrothunder.mdl
models/scmod/npcs/op4/paladin.mdl
models/scmod/npcs/op4medic/g1l.mdl
models/scmod/npcs/rgrunt/_rc.mdl
models/scmod/npcs/rgrunt/cold_blood3d.mdl
models/scmod/npcs/rgrunt/qwerty.mdl
models/scmod/npcs/scientist/alfredreynolds.mdl
models/scmod/npcs/scientist/andynemer.mdl
models/scmod/npcs/scientist/davidwied.mdl
models/scmod/npcs/scientist/tomtaylor.mdl
models/scmod/npcs/snark/kune.mdl
models/scmod/npcs/zombie/4lt.mdl
models/scmod/npcs/zombie/andras.mdl
models/scmod/npcs/zombie/csmg.mdl
models/scmod/npcs/zombie/game_zombie.mdl
models/scmod/npcs/zombie/rothgelen.mdl
models/scmod/secretcity/sv_bot.mdl
models/scmod/sledge/p_squeak.mdl
models/scmod/sledge/robonest.mdl
models/scmod/sledge/robosnark.mdl
models/scmod/sledge/v_squeak.mdl
models/scmod/spaceprisoner/robozombie.mdl
models/scmod/weapons/aliens/m41a/p_m16.mdl
models/scmod/weapons/aliens/m41a/v_m16a2.mdl
models/scmod/weapons/aliens/m41a/w_m16.mdl
models/scmod/weapons/aliens/smartgun/p_minigunidle.mdl
models/scmod/weapons/aliens/smartgun/p_minigunspin.mdl
models/scmod/weapons/aliens/smartgun/v_minigun.mdl
models/scmod/weapons/aliens/smartgun/w_minigun.mdl
models/scmod/weapons/tfc/glauncher/p_spore_launcher.mdl
models/scmod/weapons/tfc/glauncher/v_spore_launcher.mdl
models/scmod/weapons/tfc/glauncher/w_spore_launcher.mdl
models/scmod/weapons/ut99/pulsegun/v_egon.mdl
models/scmod/weapons/ut99/razor/w_crossbow.mdl
models/scmod/weapons/ut99/rocket/v_rpg.mdl
models/scmod/weapons/ut99/sniper/p_sniperrifle.mdl
models/scmod/weapons/ut99/sniper/v_sniperrifle.mdl
models/scmod/weapons/ut99/sniper/w_sniperrifle.mdl
models/scmod/weapons/ut99/ut2k4shock/v_gauss.mdl
models/scmod/weapons/ut99/w_battery.mdl
models/scmod/weapons/ut99/w_chainammo.mdl
models/scmod/weapons/ut99/w_medkit.mdl
models/scmod/weapons/ut99/w_rpgammo.mdl
models/scmod/weapons/ut99/w_shotbox.mdl
models/scmod/weapons/ut99/w_suit.mdl
models/scmod/weapons/ut99/w_weaponbox_sniper.mdl
models/scmod/zubben/barnspace.mdl
models/scmod/zubben/hgrunt.mdl
models/scmod/zubben/hgruntf.mdl
models/scmod/zubben/pirate.mdl
models/toolbox.mdl
models/xad_zubben/v_deagle.mdl
richard_boderbot.wad
sound/rng/io/misc/pick_armor.ogg
sound/rng/io/npc/delugeman/de_man_die.ogg
sound/rng/io/npc/delugeman/de_man_die2.ogg
sound/rng/io/npc/delugeman/de_man_die3.ogg
sound/rng/io/npc/delugeman/de_man_pain.ogg
sound/rng/io/npc/delugeman/de_man_pain2.ogg
sound/rng/io/npc/delugeman/de_man_pain3.ogg
sound/rng/morass_beta/sounds/npc/condor/condor_attack.ogg
sound/rng/morass_beta/sounds/npc/condor/condor_die.ogg
sound/rng/morass_beta/sounds/npc/condor/condor_die2.ogg
sound/rng/morass_beta/sounds/npc/condor/condor_pain.ogg
sound/rng/morass_beta/sounds/npc/condor/condor_pain2.ogg
sound/rng/morass_beta/sounds/npc/condor/condor_speak.ogg
sound/rng/morass_beta/sounds/npc/condor/condor_speak2.ogg
sound/rng/morass_beta/sounds/npc/condor/condor_speak3.ogg
sound/scmod/boderbot/dialogs/firstboss.ogg
sound/scmod/boderbot/dialogs/frelkerncoreboss/1paladin_s.ogg
sound/scmod/boderbot/dialogs/frelkerncoreboss/2vger_s.ogg
sound/scmod/boderbot/dialogs/frelkerncoreboss/radio_backup.ogg
sound/scmod/boderbot/dialogs/miniboss_roflcopter.ogg
sound/scmod/boderbot/dialogs/miniboss_taunt3.ogg
sound/scmod/boderbot/dialogs/miniboss_taunt4.ogg
sound/scmod/boderbot/dialogs/miniboss_taunt6.ogg
sound/scmod/boderbot/dialogs/miniboss_taunt7.ogg
sound/scmod/boderbot/dialogs/puchisoctomboss/6vger.ogg
sound/scmod/boderbot/dialogs/puchisoctomboss/7puchi.ogg
sound/scmod/boderbot/dialogs/puchisoctomboss/vger_taunt3.ogg
sound/scmod/boderbot/dialogs/tremplerboss/8vger.ogg
sound/scmod/boderbot/dialogs/vger_taunt4.ogg
sound/scmod/boderbot/dialogs/vgermobs/3paladin.ogg
sound/scmod/boderbot/dialogs/vgermobs/3paladin_r.ogg
sound/scmod/boderbot/dialogs/vgermobs/4vger_s.ogg
sound/scmod/boderbot/dialogs/vox/vox_1.ogg
sound/scmod/boderbot/dialogs/vox/vox_2.ogg
sound/scmod/boderbot/dialogs/vox/vox_3.ogg
sound/scmod/boderbot/dialogs/vox/vox_4.ogg
sound/scmod/boderbot/dialogs/vox/vox_5.ogg
sound/scmod/boderbot/dialogs/vox/vox_6.ogg
sound/scmod/boderbot/dialogs/vox/vox_7.ogg
sound/scmod/boderbot/dialogs/vox/vox_8.ogg
sound/scmod/boderbot/dialogs/vox/vox_9.ogg
sound/scmod/boderbot/ending_nectoulin.ogg
sound/scmod/boderbot/organic_nectoulin.ogg
sound/scmod/boderbot/run_arcanedreams.ogg
sound/scmod/boderbot/run_nectoulin.ogg
sound/scmod/boderbot/superfist_nectoulin.ogg
sound/scmod/boderbot/ze_space/cores.wav
sound/scmod/boderbot/ze_space/mzbutton.wav
sound/scmod/boderbot/ze_space/mzlabs.wav
sound/scmod/boderbot/ze_space/mzrunnings.wav
sound/scmod/boderbot/ze_space/mzsirens.wav
sound/scmod/boderbot/ze_space/surfacemetals.wav
sound/scmod/npcs/barniel/aimforhead.wav
sound/scmod/npcs/barniel/badfeeling.wav
sound/scmod/npcs/barniel/bequiet.wav
sound/scmod/npcs/barniel/bn_another.wav
sound/scmod/npcs/barniel/bn_attack1.wav
sound/scmod/npcs/barniel/bn_becarefull.wav
sound/scmod/npcs/barniel/bn_bring.wav
sound/scmod/npcs/barniel/bn_carefull.wav
sound/scmod/npcs/barniel/bn_close.wav
sound/scmod/npcs/barniel/bn_die1.wav
sound/scmod/npcs/barniel/bn_dontdothat.wav
sound/scmod/npcs/barniel/bn_dontmake.wav
sound/scmod/npcs/barniel/bn_endline.wav
sound/scmod/npcs/barniel/bn_firepl.wav
sound/scmod/npcs/barniel/bn_friends.wav
sound/scmod/npcs/barniel/bn_gotone.wav
sound/scmod/npcs/barniel/bn_onelessh.wav
sound/scmod/npcs/barniel/bn_pain1.wav
sound/scmod/npcs/barniel/bn_pain2.wav
sound/scmod/npcs/barniel/bn_post.wav
sound/scmod/npcs/barniel/bn_seethat.wav
sound/scmod/npcs/barniel/bn_stepoff.wav
sound/scmod/npcs/barniel/bn_tomb.wav
sound/scmod/npcs/barniel/bn_whatyou.wav
sound/scmod/npcs/barniel/diegreenthing.wav
sound/scmod/npcs/barniel/dontagree.wav
sound/scmod/npcs/barniel/dontknow.wav
sound/scmod/npcs/barniel/drinktopside.wav
sound/scmod/npcs/barniel/hearsomething.wav
sound/scmod/npcs/barniel/hevno.wav
sound/scmod/npcs/barniel/hi.wav
sound/scmod/npcs/barniel/hitbad.wav
sound/scmod/npcs/barniel/hoyes.wav
sound/scmod/npcs/barniel/humm.wav
sound/scmod/npcs/barniel/imhit.wav
sound/scmod/npcs/barniel/movietv.wav
sound/scmod/npcs/barniel/nosir.wav
sound/scmod/npcs/barniel/notatall.wav
sound/scmod/npcs/barniel/openfire.wav
sound/scmod/npcs/barniel/rightway.wav
sound/scmod/npcs/barniel/seelater.wav
sound/scmod/npcs/barniel/seeya.wav
sound/scmod/npcs/barniel/seeyoulater.wav
sound/scmod/npcs/barniel/somethingmoves.wav
sound/scmod/npcs/barniel/stop1.wav
sound/scmod/npcs/barniel/teamup1.wav
sound/scmod/npcs/barniel/teamup2.wav
sound/scmod/npcs/barniel/thinking.wav
sound/scmod/npcs/barniel/waitin.wav
sound/scmod/npcs/barniel/whatsgoingon.wav
sound/scmod/npcs/barniel/yesbarn.wav
sound/scmod/npcs/barniel/yessir.wav
sound/scmod/npcs/barniel/youneedmedic.wav
sound/scmod/npcs/molepeople/alert.ogg
sound/scmod/npcs/molepeople/alert2.ogg
sound/scmod/npcs/molepeople/idle1.ogg
sound/scmod/npcs/molepeople/idle2.ogg
sound/scmod/npcs/molepeople/idle3.ogg
sound/scmod/npcs/molepeople/menkey.ogg
sound/scmod/npcs/molepeople/menkey2.ogg
sound/scmod/npcs/robosnark/sqk_blast1.ogg
sound/scmod/npcs/robosnark/sqk_deploy1.ogg
sound/scmod/npcs/robosnark/sqk_die1.ogg
sound/scmod/npcs/robosnark/sqk_hunt1.ogg
sound/scmod/npcs/robosnark/sqk_hunt2.ogg
sound/scmod/npcs/robosnark/sqk_hunt3.ogg
sound/scmod/weapons/ut99/357_shot1.wav
sound/scmod/weapons/ut99/5health.wav
sound/scmod/weapons/ut99/5healthres.wav
sound/scmod/weapons/ut99/hks2.wav
sound/scmod/weapons/ut99/smallmedkit1.wav
sound/shl/m41a_3round.wav
sound/unreal_vox/vox_dominating.ogg
sound/unreal_vox/vox_godlike.ogg
sound/unreal_vox/vox_ludicrouskill.ogg
sound/unreal_vox/vox_massacre.ogg
sound/unreal_vox/vox_monsterkill.ogg
sound/unreal_vox/vox_unstoppable.ogg
sound/unreal_vox/vox_wickedsick.ogg
sound/weapons/hydra/activate.wav
sound/weapons/hydra/deploy.wav
sound/weapons/m41a/boltpull.wav
sound/weapons/m41a/magin.wav
sound/weapons/m41a/magout.wav
sound/weapons/m41a/pumpback.wav
sound/weapons/m41a/pumpforth.wav
sound/weapons/m41a_lc/m41a_single.wav
sound/weapons/mgsm_clipin1.wav
sound/weapons/mgsm_clipin2.wav
sound/weapons/mgsm_clipout1.wav
sound/weapons/mgsm_clipout2.wav
sound/weapons/mgsm_draw.wav
sound/xad/oldcocking.wav
sound/xad/oldcocking2.wav
sound/xad/oldshot.wav
sound/xad/uclick.wav
sprites/chan_space/items/bat.spr
sprites/custom_weapons/cso/weapon_beamsword.txt
sprites/custom_weapons/cso/weapon_ethereal.txt
sprites/custom_weapons/cso/weapon_qbarrel.txt
sprites/devastator/1.spr
sprites/devastator/2.spr
sprites/devastator/3.spr
sprites/devastator/4.spr
sprites/gunmanchronicles/cust_2GaussPistolSniper.txt
sprites/gunmanchronicles/weapon_gausspistol.txt
sprites/gunmanchronicles/weapon_gcminigun.txt
sprites/ins2/cbn/weapon_ins2c96carb.txt
sprites/ins2/hdg/weapon_ins2c96.txt
sprites/poke646/checkpoint.spr
sprites/poke646/levelchange.spr
sprites/portal_house/hud_of/640hud7of.spr
sprites/portal_house/hud_of/ofch1.spr
sprites/quake1/hudgl.spr
sprites/scmod/aliens/chronosceptor.spr
sprites/scmod/aliens/weapon_minigun.txt
sprites/scmod/boderbot/weapon_hlhornetgun.txt
sprites/scmod/cso/weapon_m249.txt
sprites/scmod/cso/weapon_ofshockrifle.txt
sprites/scmod/cso/wpn_devastator.spr
sprites/scmod/phouse/640hudas1.spr
sprites/scmod/phouse/640hudas4.spr
sprites/scmod/phouse/weapon_m16.txt
sprites/scmod/superweapons/weapon_gluongun.txt
sprites/scmod/tfc/weapon_sporelauncher.txt
sprites/scmod/ut99//weapon_ofeagle.txt
sprites/scmod/ut99/reticle.spr
sprites/scmod/ut99/sniper.spr
sprites/scmod/ut99/weapon_biorifle.txt
sprites/scmod/ut99/weapon_clgauss.txt
sprites/scmod/ut99/weapon_csocrossbow.txt
sprites/scmod/ut99/weapon_cursed_e11.txt
sprites/scmod/ut99/weapon_egon.txt
sprites/scmod/ut99/weapon_elites.txt
sprites/scmod/ut99/weapon_gauss.txt
sprites/scmod/ut99/weapon_hlmp5.txt
sprites/scmod/ut99/weapon_hlnuked_rpg.txt
sprites/scmod/ut99/weapon_hlshotgun.txt
sprites/scmod/ut99/weapon_ofeagle.txt
sprites/scmod/ut99/weapon_plasmagun.txt
sprites/scmod/ut99/weapon_redeemer.txt
sprites/scmod/ut99/weapon_shuriken.txt
sprites/scmod/ut99/weapon_sniperrifle.txt
sprites/wpn/weapon_dualkriss.txt
sprites/wpn/weapon_hkmp5.txt
