// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

events/devastator/muzzle_dev1.txt
events/devastator/muzzle_dev2.txt
events/devastator/muzzle_dev3.txt
events/devastator/muzzle_dev4.txt
events/muzzle_m41a.txt
events/muzzle_sentry_uzi.txt
gfx/env/workshopbk.tga
gfx/env/workshopdn.tga
gfx/env/workshopft.tga
gfx/env/workshoplf.tga
gfx/env/workshoprt.tga
gfx/env/workshopup.tga
models/altoverride/p_deagle.mdl
models/altoverride/w_deagle.mdl
models/chan_space_escape/items/new_obs.mdl
models/gunmanchronicles/dmlammo.mdl
models/gunshop/aa_breakerboxgroup_10_tch_smesh.mdl
models/infected/cc_electrobox01.mdl
models/lastunic/props/rpgbox.mdl
models/peany/turrimedic.mdl
models/ragemap2018/explobox.mdl
models/rngstuff/kuilu/oldcomputer.mdl
models/sc_russian/electricalbox01.mdl
models/scmod/alab/sven_cleansuit.mdl
models/scmod/alab/svensci.mdl
models/scmod/alphaunit/main_portal.mdl
models/scmod/alphaunit/w_isotopebox_old.mdl
models/scmod/boderbot/3dsky/sky_mars_far.mdl
models/scmod/boderbot/3dsky/sky_viking.mdl
models/scmod/boderbot/agrunt_robo.mdl
models/scmod/boderbot/bean_sentry_mk2.mdl
models/scmod/boderbot/bvrobo.mdl
models/scmod/boderbot/cbarney.mdl
models/scmod/boderbot/flagship.mdl
models/scmod/boderbot/gvrobo.mdl
models/scmod/boderbot/hev_opfor.mdl
models/scmod/boderbot/houndeye_robot.mdl
models/scmod/boderbot/hwgrunt_space.mdl
models/scmod/boderbot/hwrobo.mdl
models/scmod/boderbot/items/w_weaponbox.mdl
models/scmod/boderbot/kvrobo.mdl
models/scmod/boderbot/massnbomb.mdl
models/scmod/boderbot/miniturret_360.mdl
models/scmod/boderbot/parabola.mdl
models/scmod/boderbot/props/boder_holo.mdl
models/scmod/boderbot/props/concrete_debris256pile001a.mdl
models/scmod/boderbot/props/exit_sign.mdl
models/scmod/boderbot/props/rengine.mdl
models/scmod/boderbot/props/ut2k4_powernode.mdl
models/scmod/boderbot/pvrobo.mdl
models/scmod/boderbot/richard_boderbot.mdl
models/scmod/boderbot/richard_boderbot_fly.mdl
models/scmod/boderbot/richard_boderplane.mdl
models/scmod/boderbot/robobug2.mdl
models/scmod/boderbot/robocontroller.mdl
models/scmod/boderbot/robogarg.mdl
models/scmod/boderbot/robogibs.mdl
models/scmod/boderbot/rolls.mdl
models/scmod/boderbot/rvrobo.mdl
models/scmod/boderbot/superrobo.mdl
models/scmod/boderbot/terminatroll.mdl
models/scmod/boderbot/tor_bot.mdl
models/scmod/boderbot/turret_square.mdl
models/scmod/boderbot/ut2k4_dropship.mdl
models/scmod/boderbot/vger.mdl
models/scmod/boderbot/vgergrunt.mdl
models/scmod/boderbot/vgerholo.mdl
models/scmod/boderbot/vgersentry.mdl
models/scmod/boderbot/weapons/hornet.mdl
models/scmod/boderbot/weapons/p_grenade.mdl
models/scmod/boderbot/weapons/p_kamikaze_bomb.mdl
models/scmod/boderbot/weapons/p_saw.mdl
models/scmod/boderbot/weapons/spore_bean.mdl
models/scmod/boderbot/weapons/v_grenade.mdl
models/scmod/boderbot/weapons/v_saw.mdl
models/scmod/boderbot/weapons/w_grenade.mdl
models/scmod/boderbot/weapons/w_saw.mdl
models/scmod/boderbot/zombie_hev.mdl
models/scmod/exodus/robocontroller.mdl
models/scmod/item_longfallboots.mdl
models/scmod/jed/tfc_otis.mdl
models/scmod/jed/tfc_pyro.mdl
models/scmod/npcs/barnotis/robootto.mdl
models/scmod/npcs/barnotis/solokiller.mdl
models/scmod/npcs/bgman/aperture_robo.mdl
models/scmod/npcs/hgrunt/gore.mdl
models/scmod/npcs/hgrunt/rum.mdl
models/scmod/npcs/op4/hbandrew.mdl
models/scmod/npcs/op4/hrothunder.mdl
models/scmod/npcs/op4/paladin.mdl
models/scmod/npcs/op4medic/g1l.mdl
models/scmod/npcs/pitdrone/alexcorruptor.mdl
models/scmod/npcs/rgrunt/60mbbot.mdl
models/scmod/npcs/rgrunt/aurora.mdl
models/scmod/npcs/rgrunt/cyborgblevo.mdl
models/scmod/npcs/rgrunt/evil.mdl
models/scmod/npcs/rgrunt/human.mdl
models/scmod/npcs/rgrunt/max_gltrempler.mdl
models/scmod/npcs/rgrunt/mroats.mdl
models/scmod/npcs/rgrunt/programzeta.mdl
models/scmod/npcs/rgrunt/root.mdl
models/scmod/npcs/rgrunt/tweak.mdl
models/scmod/npcs/rgrunt/zyl.mdl
models/scmod/opbt/w_dispenser.mdl
models/scmod/sledge/p_squeak.mdl
models/scmod/sledge/robonest.mdl
models/scmod/sledge/robosnark.mdl
models/scmod/sledge/v_squeak.mdl
models/scmod/spaceprisoner/robozombie.mdl
models/scmod/weapons/aliens/m41a/p_m16.mdl
models/scmod/weapons/aliens/m41a/v_m16a2.mdl
models/scmod/weapons/aliens/m41a/w_m16.mdl
models/scmod/weapons/aliens/smartgun/p_minigunidle.mdl
models/scmod/weapons/aliens/smartgun/p_minigunspin.mdl
models/scmod/weapons/aliens/smartgun/v_minigun.mdl
models/scmod/weapons/aliens/smartgun/w_minigun.mdl
models/scmod/weapons/tfc/glauncher/p_spore_launcher.mdl
models/scmod/weapons/tfc/glauncher/v_spore_launcher.mdl
models/scmod/weapons/tfc/glauncher/w_spore_launcher.mdl
models/scmod/weapons/ut99/pulsegun/v_egon.mdl
models/scmod/weapons/ut99/rocket/v_rpg.mdl
models/scmod/weapons/ut99/sniper/p_sniperrifle.mdl
models/scmod/weapons/ut99/sniper/v_sniperrifle.mdl
models/scmod/weapons/ut99/sniper/w_sniperrifle.mdl
models/scmod/weapons/ut99/ut2k4shock/v_gauss.mdl
models/scmod/weapons/ut99/w_battery.mdl
models/scmod/weapons/ut99/w_chainammo.mdl
models/scmod/weapons/ut99/w_medkit.mdl
models/scmod/weapons/ut99/w_rpgammo.mdl
models/scmod/weapons/ut99/w_shotbox.mdl
models/scmod/weapons/ut99/w_suit.mdl
models/scmod/weapons/ut99/w_weaponbox_sniper.mdl
models/scmod/zubben/barnspace.mdl
models/scmod/zubben/hgrunt.mdl
models/scmod/zubben/hgruntf.mdl
models/scmod/zubben/pirate.mdl
models/stream/rgrunt_blue.mdl
models/tucumanos/s-box.mdl
models/tucumanos/s-box2.mdl
models/turr/robodyguard.mdl
models/turr/turrgrunt.mdl
models/why/roboassassin.mdl
models/xad_zubben/v_deagle.mdl
richard_boderbot.wad
sound/custom_weapons/cso/m134ex-1.wav
sound/custom_weapons/cso/m134hero_spindown.wav
sound/custom_weapons/cso/m134hero_spinup.wav
sound/scmod/boderbot/boderbot.ogg
sound/scmod/boderbot/cards_snarkfun_fixed.ogg
sound/scmod/boderbot/cyborgofcoop_fournines.ogg
sound/scmod/boderbot/dialogs/boderboss/17boderbot_s2.ogg
sound/scmod/boderbot/dialogs/boderboss/19boderbot_s2.ogg
sound/scmod/boderbot/dialogs/boderboss/20boderbot2.ogg
sound/scmod/boderbot/dialogs/boderboss/21boderbot3.ogg
sound/scmod/boderbot/dialogs/boderboss/ally_cantbelieve5.ogg
sound/scmod/boderbot/dialogs/boderboss/ally_impossible.ogg
sound/scmod/boderbot/dialogs/boderboss/ally_killhim.ogg
sound/scmod/boderbot/dialogs/boderboss/boder_excellent.ogg
sound/scmod/boderbot/dialogs/boderboss/boder_extra1.ogg
sound/scmod/boderbot/dialogs/boderboss/boder_extra2.ogg
sound/scmod/boderbot/dialogs/boderboss/boder_extra3.ogg
sound/scmod/boderbot/dialogs/boderboss/boder_firstblood.ogg
sound/scmod/boderbot/dialogs/boderboss/boder_guinea.ogg
sound/scmod/boderbot/dialogs/boderboss/boder_prerolls.ogg
sound/scmod/boderbot/dialogs/boderboss/boder_reboot.ogg
sound/scmod/boderbot/dialogs/boderboss/boder_warnbeam.ogg
sound/scmod/boderbot/dialogs/boderboss/boder_youwounded.ogg
sound/scmod/boderbot/dialogs/boderboss/bodership1.ogg
sound/scmod/boderbot/dialogs/boderboss/bodership3.ogg
sound/scmod/boderbot/dialogs/boderboss/sniper_r1.ogg
sound/scmod/boderbot/dialogs/boderboss/taunt_boderplane.ogg
sound/scmod/boderbot/dialogs/boderboss/transform.ogg
sound/scmod/boderbot/dialogs/miniboss_taunt2.ogg
sound/scmod/boderbot/dialogs/miniboss_taunt5.ogg
sound/scmod/boderbot/dialogs/solokiller_say.ogg
sound/scmod/boderbot/dialogs/tremplerboss/9trempler.ogg
sound/scmod/boderbot/dialogs/vger_dead.ogg
sound/scmod/boderbot/dialogs/vger_lol.ogg
sound/scmod/boderbot/dialogs/vger_taunt5b.ogg
sound/scmod/boderbot/dialogs/vger_taunt6.ogg
sound/scmod/boderbot/dialogs/vgerboss/10vger.ogg
sound/scmod/boderbot/dialogs/vgerboss/11gore.ogg
sound/scmod/boderbot/dialogs/vgerboss/12vger_death.ogg
sound/scmod/boderbot/dialogs/vgerboss/13paladin.ogg
sound/scmod/boderbot/dialogs/vgerboss/vgerboss.ogg
sound/scmod/boderbot/dialogs/vgermobs/5gore.ogg
sound/scmod/boderbot/dialogs/vox/vox_1.ogg
sound/scmod/boderbot/dialogs/vox/vox_2.ogg
sound/scmod/boderbot/dialogs/vox/vox_3.ogg
sound/scmod/boderbot/dialogs/vox/vox_4.ogg
sound/scmod/boderbot/dialogs/vox/vox_5.ogg
sound/scmod/boderbot/dialogs/vox/vox_6.ogg
sound/scmod/boderbot/dialogs/vox/vox_7.ogg
sound/scmod/boderbot/dialogs/vox/vox_8.ogg
sound/scmod/boderbot/dialogs/vox/vox_9.ogg
sound/scmod/boderbot/grobyc_raptorska.ogg
sound/scmod/boderbot/lock_nectoulin.ogg
sound/scmod/boderbot/powerrangers_axial.ogg
sound/scmod/boderbot/powerrangers_strichnin.ogg
sound/scmod/boderbot/ridevalky_alibi_hiddencitizens.ogg
sound/scmod/boderbot/ridevalky_samuelkim.ogg
sound/scmod/boderbot/ridevalkyloki_samuelkim.ogg
sound/scmod/boderbot/svenofcoop_fournines.ogg
sound/scmod/boderbot/ze_space/cores.wav
sound/scmod/boderbot/ze_space/mg_alarms.wav
sound/scmod/boderbot/ze_space/mzbutton.wav
sound/scmod/boderbot/ze_space/mzsirens.wav
sound/scmod/boderbot/ze_space/surfacemetals.wav
sound/scmod/boderbot/ze_space/vacuums.wav
sound/scmod/fallback_ice/cyborgsaturn.ogg
sound/scmod/fallback_ice/cyborgsecond.ogg
sound/scmod/npcs/robosnark/sqk_blast1.ogg
sound/scmod/npcs/robosnark/sqk_deploy1.ogg
sound/scmod/npcs/robosnark/sqk_die1.ogg
sound/scmod/npcs/robosnark/sqk_hunt1.ogg
sound/scmod/npcs/robosnark/sqk_hunt2.ogg
sound/scmod/npcs/robosnark/sqk_hunt3.ogg
sound/scmod/rev/dialogs/rev/robolaugh.ogg
sound/scmod/weapons/ut99/357_shot1.wav
sound/scmod/weapons/ut99/5health.wav
sound/scmod/weapons/ut99/5healthres.wav
sound/scmod/weapons/ut99/hks2.wav
sound/scmod/weapons/ut99/smallmedkit1.wav
sound/shl/m41a_3round.wav
sound/unreal_vox/vox_combowhore.ogg
sound/unreal_vox/vox_headhunter.ogg
sound/unreal_vox/vox_headshot.ogg
sound/unreal_vox/vox_holyshit.ogg
sound/unreal_vox/vox_humiliation.ogg
sound/unreal_vox/vox_kamikaze.ogg
sound/unreal_vox/vox_mesacre.ogg
sound/unreal_vox/vox_overkill.ogg
sound/unreal_vox/vox_quadkill.ogg
sound/weapons/hydra/activate.wav
sound/weapons/hydra/deploy.wav
sound/weapons/m41a/boltpull.wav
sound/weapons/m41a/magin.wav
sound/weapons/m41a/magout.wav
sound/weapons/m41a/pumpback.wav
sound/weapons/m41a/pumpforth.wav
sound/weapons/m41a_lc/m41a_single.wav
sound/weapons/mgsm_clipin1.wav
sound/weapons/mgsm_clipin2.wav
sound/weapons/mgsm_clipout1.wav
sound/weapons/mgsm_clipout2.wav
sound/weapons/mgsm_draw.wav
sound/weapons/opbt/m134ex_spin.wav
sound/xad/oldcocking.wav
sound/xad/oldcocking2.wav
sound/xad/oldshot.wav
sound/xad/uclick.wav
sprites/custom_weapons/cso/weapon_beamsword.txt
sprites/custom_weapons/cso/weapon_ethereal.txt
sprites/custom_weapons/cso/weapon_qbarrel.txt
sprites/devastator/1.spr
sprites/devastator/2.spr
sprites/devastator/3.spr
sprites/devastator/4.spr
sprites/gunmanchronicles/cust_2GaussPistolSniper.txt
sprites/gunmanchronicles/weapon_gausspistol.txt
sprites/gunmanchronicles/weapon_gcminigun.txt
sprites/ins2/cbn/weapon_ins2c96carb.txt
sprites/ins2/hdg/weapon_ins2c96.txt
sprites/poke646/checkpoint.spr
sprites/scmod/aliens/chronosceptor.spr
sprites/scmod/aliens/weapon_minigun.txt
sprites/scmod/boderbot/weapon_hlhornetgun.txt
sprites/scmod/cso/weapon_m249.txt
sprites/scmod/cso/weapon_ofshockrifle.txt
sprites/scmod/cso/wpn_devastator.spr
sprites/scmod/item_longfallboots.spr
sprites/scmod/phouse/640hudas1.spr
sprites/scmod/phouse/640hudas4.spr
sprites/scmod/phouse/weapon_m16.txt
sprites/scmod/superweapons/weapon_gluongun.txt
sprites/scmod/ut99//weapon_ofeagle.txt
sprites/scmod/ut99/reticle.spr
sprites/scmod/ut99/sniper.spr
sprites/scmod/ut99/weapon_biorifle.txt
sprites/scmod/ut99/weapon_clgauss.txt
sprites/scmod/ut99/weapon_csocrossbow.txt
sprites/scmod/ut99/weapon_cursed_e11.txt
sprites/scmod/ut99/weapon_egon.txt
sprites/scmod/ut99/weapon_elites.txt
sprites/scmod/ut99/weapon_hlmp5.txt
sprites/scmod/ut99/weapon_hlnuked_rpg.txt
sprites/scmod/ut99/weapon_hlshotgun.txt
sprites/scmod/ut99/weapon_plasmagun.txt
sprites/scmod/ut99/weapon_redeemer.txt
sprites/scmod/ut99/weapon_shuriken.txt
sprites/scmod/ut99/weapon_sniperrifle.txt
sprites/wpn/weapon_dualkriss.txt
sprites/wpn/weapon_hkmp5.txt
