// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

de_rex.wad
do_map.wad
events/devastator/muzzle_dev1.txt
events/devastator/muzzle_dev2.txt
events/devastator/muzzle_dev3.txt
events/devastator/muzzle_dev4.txt
events/muzzle_m41a.txt
gfx/env/mars2bk.tga
gfx/env/mars2dn.tga
gfx/env/mars2ft.tga
gfx/env/mars2lf.tga
gfx/env/mars2rt.tga
gfx/env/mars2up.tga
hs4rb.wad
ma_quasar.wad
models/altoverride/p_deagle.mdl
models/altoverride/w_deagle.mdl
models/chan_space_escape/items/new_obs.mdl
models/gunmanchronicles/dmlammo.mdl
models/gunshop/aa_breakerboxgroup_10_tch_smesh.mdl
models/infected/cc_electrobox01.mdl
models/lastunic/props/rpgbox.mdl
models/rngstuff/kuilu/npcs/k_condor.mdl
models/rngstuff/kuilu/npcs/k_mutant_jackal.mdl
models/rngstuff/kuilu/npcs/k_slave.mdl
models/rngstuff/kuilu/npcs/k_slave_big.mdl
models/rngstuff/kuilu/npcs/k_squid_beak.mdl
models/rngstuff/kuilu/npcs/k_trooper.mdl
models/rngstuff/kuilu/npcs/k_trooper_beak.mdl
models/rngstuff/kuilu/npcs/k_trooper_bread.mdl
models/rngstuff/kuilu/npcs/k_trooper_metal.mdl
models/rngstuff/kuilu/npcs/k_zombie.mdl
models/rngstuff/kyper_kuutio/mr_zombie3.mdl
models/rngstuff/morass_beta/condor.mdl
models/rngstuff/morass_beta/de_worm.mdl
models/rngstuff/morass_beta/morassbeast.mdl
models/rngstuff/morass_beta/mutant_repeater.mdl
models/rngstuff/morass_beta/rtrooper.mdl
models/rngstuff/romutus/junkdrone.mdl
models/sc_russian/electricalbox01.mdl
models/scmod/alab/sven_cleansuit.mdl
models/scmod/alab/svensci.mdl
models/scmod/alphaunit/w_isotopebox_old.mdl
models/scmod/boderbot/3dsky/dome_shield.mdl
models/scmod/boderbot/3dsky/sence_space_fixed2.mdl
models/scmod/boderbot/3dsky/sky_mars_far.mdl
models/scmod/boderbot/3dsky/sky_milky.mdl
models/scmod/boderbot/3dsky/vikingship3.mdl
models/scmod/boderbot/agrunt_robo.mdl
models/scmod/boderbot/apache_pod.mdl
models/scmod/boderbot/cbarney.mdl
models/scmod/boderbot/controller_drone.mdl
models/scmod/boderbot/flagship.mdl
models/scmod/boderbot/guardian.mdl
models/scmod/boderbot/guardian2.mdl
models/scmod/boderbot/hev_hgrunt.mdl
models/scmod/boderbot/hev_opfor.mdl
models/scmod/boderbot/hevgeo.mdl
models/scmod/boderbot/hwgrunt_space.mdl
models/scmod/boderbot/items/w_weaponbox.mdl
models/scmod/boderbot/massnbomb.mdl
models/scmod/boderbot/medikit3.mdl
models/scmod/boderbot/microturret_360.mdl
models/scmod/boderbot/miniturret_360.mdl
models/scmod/boderbot/nexon_rgrunt.mdl
models/scmod/boderbot/nexon_rgrunt2.mdl
models/scmod/boderbot/props/boder_holo.mdl
models/scmod/boderbot/props/exit_sign.mdl
models/scmod/boderbot/props/sniper_space_dead.mdl
models/scmod/boderbot/props/ut2exit.mdl
models/scmod/boderbot/props/ut2k4_powernode.mdl
models/scmod/boderbot/props/w_circuits.mdl
models/scmod/boderbot/robobug2.mdl
models/scmod/boderbot/robogarg.mdl
models/scmod/boderbot/robogibs.mdl
models/scmod/boderbot/robosniper.mdl
models/scmod/boderbot/sniper_space.mdl
models/scmod/boderbot/turret_biglauncher.mdl
models/scmod/boderbot/turret_square.mdl
models/scmod/boderbot/vgergrunt.mdl
models/scmod/boderbot/vgersentry.mdl
models/scmod/boderbot/weapons/hornet.mdl
models/scmod/boderbot/weapons/p_grenade.mdl
models/scmod/boderbot/weapons/p_kamikaze_bomb.mdl
models/scmod/boderbot/weapons/p_saw.mdl
models/scmod/boderbot/weapons/spore_bean.mdl
models/scmod/boderbot/weapons/v_grenade.mdl
models/scmod/boderbot/weapons/v_saw.mdl
models/scmod/boderbot/weapons/w_grenade.mdl
models/scmod/boderbot/weapons/w_saw.mdl
models/scmod/boderbot/xvenwing.mdl
models/scmod/boderbot/zombie_hev.mdl
models/scmod/exodus/molepeople_gun.mdl
models/scmod/exodus/robocontroller.mdl
models/scmod/item_oxygen.mdl
models/scmod/jed/tfc_pyro.mdl
models/scmod/opbt/w_dispenser.mdl
models/scmod/sledge/p_squeak.mdl
models/scmod/sledge/robonest.mdl
models/scmod/sledge/robosnark.mdl
models/scmod/sledge/v_squeak.mdl
models/scmod/spaceprisoner/robozombie.mdl
models/scmod/weapons/aliens/m41a/p_m16.mdl
models/scmod/weapons/aliens/m41a/v_m16a2.mdl
models/scmod/weapons/aliens/m41a/w_m16.mdl
models/scmod/weapons/aliens/smartgun/p_minigunidle.mdl
models/scmod/weapons/aliens/smartgun/p_minigunspin.mdl
models/scmod/weapons/aliens/smartgun/v_minigun.mdl
models/scmod/weapons/aliens/smartgun/w_minigun.mdl
models/scmod/weapons/tfc/glauncher/p_spore_launcher.mdl
models/scmod/weapons/tfc/glauncher/v_spore_launcher.mdl
models/scmod/weapons/tfc/glauncher/w_spore_launcher.mdl
models/scmod/weapons/ut99/pulsegun/v_egon.mdl
models/scmod/weapons/ut99/rocket/v_rpg.mdl
models/scmod/weapons/ut99/sniper/p_sniperrifle.mdl
models/scmod/weapons/ut99/sniper/v_sniperrifle.mdl
models/scmod/weapons/ut99/sniper/w_sniperrifle.mdl
models/scmod/weapons/ut99/ut2k4shock/v_gauss.mdl
models/scmod/weapons/ut99/w_battery.mdl
models/scmod/weapons/ut99/w_chainammo.mdl
models/scmod/weapons/ut99/w_medkit.mdl
models/scmod/weapons/ut99/w_rpgammo.mdl
models/scmod/weapons/ut99/w_shotbox.mdl
models/scmod/weapons/ut99/w_suit.mdl
models/scmod/weapons/ut99/w_weaponbox_sniper.mdl
models/scmod/zubben/barnspace.mdl
models/scmod/zubben/hgrunt.mdl
models/scmod/zubben/hgruntf.mdl
models/scmod/zubben/molepeople.mdl
models/scmod/zubben/pirate.mdl
models/tucumanos/s-box.mdl
models/tucumanos/s-box2.mdl
models/xad_zubben/v_deagle.mdl
richard_boderbot.wad
sound/ambience/thunder.wav
sound/mustardf/factorysounds/drone_loop.wav
sound/rng/io/misc/pick_armor.ogg
sound/rng/io/npc/delugeman/de_man_die.ogg
sound/rng/io/npc/delugeman/de_man_die2.ogg
sound/rng/io/npc/delugeman/de_man_die3.ogg
sound/rng/io/npc/delugeman/de_man_pain.ogg
sound/rng/io/npc/delugeman/de_man_pain2.ogg
sound/rng/io/npc/delugeman/de_man_pain3.ogg
sound/rng/io/npc/trooper/troop_shoot.ogg
sound/rng/morass/sounds/npc/condor/condor_shoot.ogg
sound/rng/morass/sounds/npc/repeater/rep_shoot.ogg
sound/rng/morass/sounds/npc/rtrooper/rt_shoot.ogg
sound/rng/morass_beta/sounds/npc/condor/condor_attack.ogg
sound/rng/morass_beta/sounds/npc/condor/condor_die.ogg
sound/rng/morass_beta/sounds/npc/condor/condor_die2.ogg
sound/rng/morass_beta/sounds/npc/condor/condor_pain.ogg
sound/rng/morass_beta/sounds/npc/condor/condor_pain2.ogg
sound/rng/morass_beta/sounds/npc/condor/condor_speak.ogg
sound/rng/morass_beta/sounds/npc/condor/condor_speak2.ogg
sound/rng/morass_beta/sounds/npc/condor/condor_speak3.ogg
sound/scmod/boderbot/dialogs/boderboss/bodership1.ogg
sound/scmod/boderbot/dialogs/boderboss/bodership2.ogg
sound/scmod/boderbot/dialogs/boderboss/bodership3.ogg
sound/scmod/boderbot/dialogs/boderboss/bodership4.ogg
sound/scmod/boderbot/dialogs/boderboss/sniper_r1.ogg
sound/scmod/boderbot/dialogs/boderboss/sniper_r2.ogg
sound/scmod/boderbot/dialogs/boderboss/sniper_r3.ogg
sound/scmod/boderbot/dialogs/lastsven_r.ogg
sound/scmod/boderbot/dialogs/vox/vox_1.ogg
sound/scmod/boderbot/dialogs/vox/vox_2.ogg
sound/scmod/boderbot/dialogs/vox/vox_3.ogg
sound/scmod/boderbot/dialogs/vox/vox_4.ogg
sound/scmod/boderbot/dialogs/vox/vox_5.ogg
sound/scmod/boderbot/dialogs/vox/vox_6.ogg
sound/scmod/boderbot/dialogs/vox/vox_7.ogg
sound/scmod/boderbot/dialogs/vox/vox_8.ogg
sound/scmod/boderbot/dialogs/vox/vox_9.ogg
sound/scmod/boderbot/foregone_loudspeakerz.ogg
sound/scmod/boderbot/foregone_maynard.ogg
sound/scmod/boderbot/foregone_michellemay.ogg
sound/scmod/boderbot/interstellar_331erock.ogg
sound/scmod/boderbot/ze_space/ze_alert.ogg
sound/scmod/npcs/molepeople/alert.ogg
sound/scmod/npcs/molepeople/alert2.ogg
sound/scmod/npcs/molepeople/die.ogg
sound/scmod/npcs/molepeople/idle1.ogg
sound/scmod/npcs/molepeople/idle2.ogg
sound/scmod/npcs/molepeople/idle3.ogg
sound/scmod/npcs/molepeople/menkey.ogg
sound/scmod/npcs/molepeople/menkey2.ogg
sound/scmod/npcs/molepeople/pain.ogg
sound/scmod/npcs/molepeople/pain2.ogg
sound/scmod/npcs/robosnark/sqk_blast1.ogg
sound/scmod/npcs/robosnark/sqk_deploy1.ogg
sound/scmod/npcs/robosnark/sqk_die1.ogg
sound/scmod/npcs/robosnark/sqk_hunt1.ogg
sound/scmod/npcs/robosnark/sqk_hunt2.ogg
sound/scmod/npcs/robosnark/sqk_hunt3.ogg
sound/scmod/weapons/ut99/357_shot1.wav
sound/scmod/weapons/ut99/5health.wav
sound/scmod/weapons/ut99/5healthres.wav
sound/scmod/weapons/ut99/hks2.wav
sound/scmod/weapons/ut99/smallmedkit1.wav
sound/shl/m41a_3round.wav
sound/weapons/hydra/activate.wav
sound/weapons/hydra/deploy.wav
sound/weapons/m41a/boltpull.wav
sound/weapons/m41a/magin.wav
sound/weapons/m41a/magout.wav
sound/weapons/m41a/pumpback.wav
sound/weapons/m41a/pumpforth.wav
sound/weapons/m41a_lc/m41a_single.wav
sound/weapons/mgsm_clipin1.wav
sound/weapons/mgsm_clipin2.wav
sound/weapons/mgsm_clipout1.wav
sound/weapons/mgsm_clipout2.wav
sound/weapons/mgsm_draw.wav
sound/xad/oldcocking.wav
sound/xad/oldcocking2.wav
sound/xad/oldshot.wav
sound/xad/uclick.wav
sprites/custom_weapons/cso/weapon_beamsword.txt
sprites/custom_weapons/cso/weapon_ethereal.txt
sprites/custom_weapons/cso/weapon_qbarrel.txt
sprites/devastator/1.spr
sprites/devastator/2.spr
sprites/devastator/3.spr
sprites/devastator/4.spr
sprites/gunmanchronicles/cust_2GaussPistolSniper.txt
sprites/gunmanchronicles/weapon_gausspistol.txt
sprites/gunmanchronicles/weapon_gcminigun.txt
sprites/ins2/cbn/weapon_ins2c96carb.txt
sprites/ins2/hdg/weapon_ins2c96.txt
sprites/ragemap2022/erty_oxygen.spr
sprites/scmod/boderbot/weapon_hlhornetgun.txt
sprites/scmod/cso/weapon_m249.txt
sprites/scmod/cso/weapon_ofshockrifle.txt
sprites/scmod/cso/wpn_devastator.spr
sprites/scmod/phouse/640hudas1.spr
sprites/scmod/phouse/640hudas4.spr
sprites/scmod/phouse/weapon_m16.txt
sprites/scmod/superweapons/weapon_gluongun.txt
sprites/scmod/ut99//weapon_ofeagle.txt
sprites/scmod/ut99/reticle.spr
sprites/scmod/ut99/sniper.spr
sprites/scmod/ut99/weapon_biorifle.txt
sprites/scmod/ut99/weapon_clgauss.txt
sprites/scmod/ut99/weapon_csocrossbow.txt
sprites/scmod/ut99/weapon_cursed_e11.txt
sprites/scmod/ut99/weapon_elites.txt
sprites/scmod/ut99/weapon_hlmp5.txt
sprites/scmod/ut99/weapon_hlnuked_rpg.txt
sprites/scmod/ut99/weapon_hlshotgun.txt
sprites/scmod/ut99/weapon_ofeagle.txt
sprites/scmod/ut99/weapon_plasmagun.txt
sprites/scmod/ut99/weapon_redeemer.txt
sprites/scmod/ut99/weapon_shuriken.txt
sprites/scmod/ut99/weapon_sniperrifle.txt
sprites/wpn/weapon_dualkriss.txt
sprites/wpn/weapon_hkmp5.txt
