maps/richard_boderman.cfg
maps/richard_boderman.res
maps/richard_boderman_motd.txt
maps/richard_boderman_skl.cfg
models/richard_boderman/boderman.mdl
models/richard_boderman/bulb.mdl
models/richard_boderman/Hassassin.mdl
models/richard_boderman/palm1.mdl
models/richard_boderman/palm2.mdl
models/richard_boderman/palm3.mdl
models/richard_boderman/plant.mdl
models/richard_boderman/superrobo.mdl
sound/richard_boderman/boderman.txt
sound/richard_boderman/global.txt
sound/richard_boderman/hueytimer1.wav
sound/richard_boderman/hueytimer2.wav
sound/richard_boderman/hueytimer3.wav
sound/richard_boderman/superrobo.txt
sound/richard_boderman/wagner.mp3