maps/sc_activist2.cfg
maps/sc_activist2.res
models/sc_activist/Barney.mdl
models/sc_activist/bullsquid.mdl
models/sc_activist/bullsquid01.mdl
models/sc_activist/garg.mdl
models/sc_activist/houndeye.mdl
models/sc_activist/robohwgrunt.mdl
sound/sc_activist/ALARM.WAV
sound/sc_activist/boomer.wav
sound/sc_activist/button1.wav
sound/sc_activist/emdrill.wav
sound/sc_activist/rocket_groan1.wav
sound/sc_activist/sc_activist_2.wav
sound/sc_activist/sc_activist_7.wav