maps/sc_activist.cfg
maps/sc_activist.res
maps/sc_activist_motd.txt
models/sc_activist/Barney.mdl
models/sc_activist/houndeye.mdl
models/sc_activist/houndeyet.mdl
models/sc_activist/swat.mdl
sound/sc_activist/hungerhound.txt
sound/hungerhound/he_alert1.wav
sound/hungerhound/he_attack1.wav
sound/hungerhound/he_attack3.wav
sound/hungerhound/he_die1.wav
sound/hungerhound/he_die3.wav
sound/hungerhound/he_hunt1.wav
sound/hungerhound/he_hunt2.wav
sound/hungerhound/he_hunt4.wav
sound/hungerhound/he_idle1.wav
sound/hungerhound/he_pain4.wav
sound/sc_activist/boomer.wav
sound/sc_activist/clock-tic.wav
sound/sc_activist/elevbell1.wav
sound/sc_activist/industrial4.wav
sound/sc_activist/sc_activist_1.wav
sound/sc_activist/sc_activist_4.wav
sound/sc_activist/waterfall3.wav