// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

Buro.wad
gfx/detail/sc_buro_prologue/lght.tga
gfx/detail/sc_buro_prologue/Wa_flr2.tga
gfx/detail/sc_buro_prologue/Wa_flr2_2.tga
gfx/detail/sc_buro_prologue/Wa_wall2.tga
gfx/env/motor_nightbk.tga
gfx/env/motor_nightdn.tga
gfx/env/motor_nightft.tga
gfx/env/motor_nightlf.tga
gfx/env/motor_nightrt.tga
gfx/env/motor_nightup.tga
maps/sc_buro_prologue_demo_detail.txt
models/Buro/anlage.mdl
models/Buro/ashtray_standing.mdl
models/Buro/atm.mdl
models/Buro/aufsteller.mdl
models/Buro/aufsteller2.mdl
models/Buro/banktext.mdl
models/Buro/beamer.mdl
models/Buro/bench_locker.mdl
models/Buro/bicycle.mdl
models/Buro/blackhawk_gunship.mdl
models/Buro/blatt.mdl
models/Buro/businessman.mdl
models/Buro/businessman01.mdl
models/Buro/businessman02.mdl
models/Buro/car_dealers.mdl
models/Buro/car_police.mdl
models/Buro/car_police_glass.mdl
models/Buro/chair_office.mdl
models/Buro/coffee_maker.mdl
models/Buro/coffee_props-cup.mdl
models/Buro/coffee_props-sugar.mdl
models/Buro/couch_leather.mdl
models/Buro/decke.mdl
models/Buro/deskc.mdl
models/Buro/deskl.mdl
models/Buro/desktop.mdl
models/Buro/dumpster_lidclosed.mdl
models/Buro/filecabinet.mdl
models/Buro/filecabinet_4dr-group.mdl
models/Buro/fire_extinguisher.mdl
models/Buro/futon.mdl
models/Buro/galleyset1.mdl
models/Buro/gena_id.mdl
models/Buro/laptop.mdl
models/Buro/luggage_briefcase.mdl
models/Buro/paperbox_double.mdl
models/Buro/paperbox_single.mdl
models/Buro/phone_pay-US.mdl
models/Buro/plant_potted.mdl
models/Buro/rahmen.mdl
models/Buro/rahmen2.mdl
models/Buro/rahmen3.mdl
models/Buro/servtext.mdl
models/Buro/spot.mdl
models/Buro/stepvan.mdl
models/Buro/stepvan_back.mdl
models/Buro/tastatur.mdl
models/Buro/tree3.mdl
models/Buro/tree4.mdl
models/Buro/ueberweisung.mdl
models/Buro/warte.mdl
models/player/Police/Police.bmp
models/player/Police/Police.mdl
sound/buro/assault.mp3
sound/buro/bomb.wav
sound/buro/intro.mp3
sound/buro/office_ambience.wav
sound/buro/radio.wav
sound/buro/refrigerator_loop.wav
sound/buro/samp1.wav
sound/buro/street.mp3
sound/buro/working.wav
sprites/buro/grass_01.spr
sprites/buro/grass_03.spr
