maps/sc_castle.res
maps/sc_castle.bsp
maps/sc_castle.cfg
maps/sc_castle_skl.cfg
maps/sc_castle_motd.txt
maps/sc_castle_readme.txt
models/sc_castle/models.txt
models/sc_castle/w_suit.mdl
models/sc_castle/generic.mdl
models/sc_castle/generic01.mdl
models/sc_castle/generic02.mdl
models/sc_castle/credits.txt
sc_castle.wad