maps/sc_hammerhead4.cfg
maps/sc_hammerhead4.res
maps/sc_hammerhead4_motd.txt
maps/sc_hammerhead4_readme.txt
models/hammerhead/arc_fern.mdl
models/hammerhead/furniture/pissoir.mdl
models/hammerhead/furniture/toilette.mdl
models/hammerhead/furniture/washbowl.mdl
models/hammerhead/chubby.mdl
models/hammerhead/civilian.mdl
models/hammerhead/civilian3.mdl
models/hammerhead/civilian01.mdl
models/hammerhead/civilian02.mdl
models/hammerhead/civilian03.mdl
models/hammerhead/civilian04.mdl
models/hammerhead/civilian05.mdl
models/hammerhead/civilian06.mdl
models/hammerhead/civilian07.mdl
models/hammerhead/civiliant.mdl
sound/hammerhead/biggun1.wav
sound/hammerhead/biggun3.wav
sound/hammerhead/mgun_burst1.wav
sound/hammerhead/mine_deploy.wav
sound/hammerhead/mortar.wav
sound/hammerhead/mortarhit.wav
sound/hammerhead/rifle1.wav
sound/hammerhead/rifle2.wav
sound/hammerhead/turretrot2.wav
sound/hammerhead/warn3.wav
sprites/hammerhead/smoke.spr
sprites/hammerhead/muzzleflash3.spr
sprites/hammerhead/muzzleflash.spr
sprites/hammerhead/stmbal1.spr
sprites/hammerhead/ballsmoke.spr
hammerhead.wad
