// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/night2bk.tga
gfx/env/night2dn.tga
gfx/env/night2ft.tga
gfx/env/night2lf.tga
gfx/env/night2rt.tga
gfx/env/night2up.tga
maps/sc_propanic_part_1_detail.txt
models/DGF_Healthstation.mdl
models/not_precached2.mdl
models/p_froster.mdl
models/p_nailgun.mdl
models/p_pulserifle.mdl
models/p_taucannon.mdl
models/trempler/agrunt.mdl
models/trempler/apache.mdl
models/trempler/barney.mdl
models/trempler/barneyevil.mdl
models/trempler/baum_01.mdl
models/trempler/Bloodsucker_A.mdl
models/trempler/bluepanther/pit_drone.mdl
models/trempler/bullsquid.mdl
models/trempler/bush_japan_fern_01.mdl
models/trempler/controller.mdl
models/trempler/grenade.mdl
models/trempler/headcrab.mdl
models/trempler/hgrunt1.mdl
models/trempler/hornet.mdl
models/trempler/houndeye.mdl
models/trempler/hwgrunt.mdl
models/trempler/industry/ventilation2.mdl
models/trempler/industry2/tool_box.mdl
models/trempler/islave.mdl
models/trempler/leech.mdl
models/trempler/npc_officer.mdl
models/trempler/npc_scientist.mdl
models/trempler/p_2uzis.mdl
models/trempler/p_2uzis_gold.mdl
models/trempler/p_crowbar.mdl
models/trempler/p_m16.mdl
models/trempler/p_pipe_wrench.mdl
models/trempler/p_rpg.mdl
models/trempler/p_shotgun.mdl
models/trempler/p_uzi.mdl
models/trempler/p_uzi_gold.mdl
models/trempler/prokeyred.mdl
models/trempler/prokeyyellow.mdl
models/trempler/roach.mdl
models/trempler/rpgrocket.mdl
models/trempler/scanner/eye_scanner.mdl
models/trempler/scientist.mdl
models/trempler/scientist1.mdl
models/trempler/scientist2.mdl
models/trempler/sentry.mdl
models/trempler/sentryt.mdl
models/trempler/shelve/metallschrank.mdl
models/trempler/soldier_clon_heavy.mdl
models/trempler/spider.mdl
models/trempler/spore_ammo.mdl
models/trempler/tor.mdl
models/trempler/v_crowbar.mdl
models/trempler/v_gauss.mdl
models/trempler/v_m16a2.mdl
models/trempler/v_pipe_wrench.mdl
models/trempler/v_rpg.mdl
models/trempler/v_shotgun.mdl
models/trempler/v_uzi.mdl
models/trempler/W/backpack.mdl
models/trempler/w_2uzis.mdl
models/trempler/w_2uzis_gold.mdl
models/trempler/w_battery.mdl
models/trempler/w_batteryt.mdl
models/trempler/w_crowbar.mdl
models/trempler/w_m16.mdl
models/trempler/w_medkit.mdl
models/trempler/w_rpg.mdl
models/trempler/w_shotgun.mdl
models/trempler/w_uzi.mdl
models/trempler/w_uzi_gold.mdl
models/trempler/zombie.mdl
models/trempler/zombie_soldier.mdl
models/v_froster.mdl
models/v_nailgun.mdl
models/v_pulserifle.mdl
models/v_taucannon.mdl
models/w_rg6_grenade.mdl
sound/apache/ap_rotor1xx.wav
sound/apache/ap_rotor2xx.wav
sound/apache/ap_rotor3xx.wav
sound/apache/ap_rotor4xx.wav
sound/buzzer_hrap.wav
sound/controller/con_alert1xx.wav
sound/controller/con_alert2xx.wav
sound/controller/con_alert3xx.wav
sound/controller/con_attack1xx.wav
sound/controller/con_attack2xx.wav
sound/controller/con_attack3xx.wav
sound/controller/con_die1xx.wav
sound/controller/con_die2xx.wav
sound/controller/con_idle1xx.wav
sound/controller/con_idle2xx.wav
sound/controller/con_idle3xx.wav
sound/controller/con_idle4xx.wav
sound/controller/con_pain1xx.wav
sound/controller/con_pain2xx.wav
sound/controller/con_pain3xx.wav
sound/Customx/fluorescent.wav
sound/debris/bustglass1xx.wav
sound/debris/bustglass2xx.wav
sound/debris/bustglass3xx.wav
sound/debris/bustmetal1xx.wav
sound/debris/bustmetal2xx.wav
sound/debris/metal1xx.wav
sound/debris/metal2xx.wav
sound/debris/metal3xx.wav
sound/debris/metal4xx.wav
sound/player/pl_asf1xx.wav
sound/player/pl_asf2xx.wav
sound/player/pl_asf3xx.wav
sound/player/pl_asf4xx.wav
sound/player/pl_beton1xx.wav
sound/player/pl_beton2xx.wav
sound/player/pl_beton3xx.wav
sound/player/pl_beton4xx.wav
sound/player/pl_dirt1xx.wav
sound/player/pl_dirt2xx.wav
sound/player/pl_dirt3xx.wav
sound/player/pl_dirt4xx.wav
sound/player/pl_duct1xx.wav
sound/player/pl_duct2xx.wav
sound/player/pl_duct3xx.wav
sound/player/pl_duct4xx.wav
sound/player/pl_fallpain1xx.wav
sound/player/pl_fallpain2xx.wav
sound/player/pl_fallpain3xx.wav
sound/player/pl_jump1xx.wav
sound/player/pl_jump2xx.wav
sound/player/pl_jumpland2xx.wav
sound/player/pl_ladder1xx.wav
sound/player/pl_ladder2xx.wav
sound/player/pl_ladder3xx.wav
sound/player/pl_ladder4xx.wav
sound/player/pl_metal1xx.wav
sound/player/pl_metal2xx.wav
sound/player/pl_metal3xx.wav
sound/player/pl_metal4xx.wav
sound/player/pl_pain2xx.wav
sound/player/pl_pain4xx.wav
sound/player/pl_pain5xx.wav
sound/player/pl_pain6xx.wav
sound/player/pl_pain7xx.wav
sound/player/pl_step1xx.wav
sound/player/pl_step2xx.wav
sound/player/pl_step3xx.wav
sound/player/pl_step4xx.wav
sound/rm/rat/rat_alert1.ogg
sound/rm/rat/rat_die1.ogg
sound/rm/rat/rat_die2.ogg
sound/rm/rat/rat_idle1.ogg
sound/rm/rat/rat_idle2.ogg
sound/rm/rat/rat_jump1.ogg
sound/rm/rat/rat_pain1.ogg
sound/rm/rat/rat_pain2.ogg
sound/roach/rch_diexx.wav
sound/roach/rch_smashxx.wav
sound/roach/rch_walkxx.wav
sound/trempler/buzzer_boom_quake.wav
sound/trempler/buzzer_wind0.wav
sound/trempler/carforest1.wav
sound/trempler/enginewarn1.wav
sound/trempler/enginewarn2.wav
sound/trempler/enginewarn3.wav
sound/trempler/h4.wav
sound/trempler/introtext.ogg
sound/trempler/jd_atmosphere01.wav
sound/trempler/jd_atmosphere02.wav
sound/trempler/jd_atmosphere03.wav
sound/trempler/jd_atmosphere04.wav
sound/trempler/jd_atmosphere05.wav
sound/trempler/jd_atmosphere06.wav
sound/trempler/millitarywarning.wav
sound/trempler/propanic_massacre.wav
sound/trempler/scary_wind1.wav
sound/trempler/sickness2.wav
sound/trempler/team_alert.wav
sound/trempler/teleporter_blast.wav
sound/turret/tu_fire1xx.wav
sound/weapons/ak-101/boltpull_stalker.wav
sound/weapons/ak-101/gp25_reload_stalker.wav
sound/weapons/ak-101/magin_stalker.wav
sound/weapons/ak-101/magout_stalker.wav
sound/weapons/aks_fire1.wav
sound/weapons/aks_fire2.wav
sound/weapons/aks_fire3.wav
sound/weapons/awp_boltdown.wav
sound/weapons/beamrifle_fire1.wav
sound/weapons/beamrifle_fire2.wav
sound/weapons/BFG_fire.wav
sound/weapons/bfg_fire_sunofgod.wav
sound/weapons/bfg_spin.wav
sound/weapons/chainsaw_running_idle.wav
sound/weapons/chainsaw_start.wav
sound/weapons/dbarrel1xx.wav
sound/weapons/explode3xx.wav
sound/weapons/explode4xx.wav
sound/weapons/explode5xx.wav
sound/weapons/froster_firegrenade.wav
sound/weapons/froster_reload.wav
sound/weapons/gauss2xx.wav
sound/weapons/gauss_hitxx.wav
sound/weapons/glauncher2xx.wav
sound/weapons/glauncherxx.wav
sound/weapons/gluongun_fire.wav
sound/weapons/gluongun_reload.wav
sound/weapons/grenade_hit1xx.wav
sound/weapons/grenade_hit2xx.wav
sound/weapons/grenade_hit3xx.wav
sound/weapons/hiss1.wav
sound/weapons/laser_node_power_off.wav
sound/weapons/m16_3roundxx.wav
sound/weapons/m16_singlexx.wav
sound/weapons/nailgun_reload.wav
sound/weapons/photongun_fire.wav
sound/weapons/photongun_fire2.wav
sound/weapons/plasmarifle_reload.wav
sound/weapons/powerdown.wav
sound/weapons/psp_blast.wav
sound/weapons/psp_fire.wav
sound/weapons/pulserifle_fidget.wav
sound/weapons/pulserifle_reload.wav
sound/weapons/pwrench_big_hitbod1xx.wav
sound/weapons/pwrench_hit1xx.wav
sound/weapons/pwrench_hit2xx.wav
sound/weapons/pwrench_hitbod1xx.wav
sound/weapons/pwrench_hitbod2xx.wav
sound/weapons/pwrench_hitbod3xx.wav
sound/weapons/pwrench_miss1xx.wav
sound/weapons/pwrench_miss2xx.wav
sound/weapons/ric1xx.wav
sound/weapons/ric2xx.wav
sound/weapons/ric3xx.wav
sound/weapons/ric4xx.wav
sound/weapons/ric5xx.wav
sound/weapons/rocket1xx.wav
sound/weapons/rocketfire1xx.wav
sound/weapons/rpg7_reload.wav
sound/weapons/sbarrel1xx.wav
sound/weapons/shock_hitwall.wav
sound/weapons/skorpion/Skr_Cock.wav
sound/weapons/skorpion/Skr_Magin.wav
sound/weapons/skorpion/Skr_Magout.wav
sound/weapons/smartgun_fire2.wav
sound/weapons/smartgun_lgtngball_fly.wav
sound/weapons/taucannon_reload.wav
sound/zombie/zo_attack1x.wav
sound/zombie/zo_attack2x.wav
sprites/acid_drip.spr
sprites/acid_puff2.spr
sprites/anim_spr4.spr
sprites/anim_spr7.spr
sprites/animsparkx.spr
sprites/bluemuzzle.spr
sprites/bluetrail.spr
sprites/egonbeamx.spr
sprites/exp_blue.spr
sprites/exp_green.spr
sprites/exp_red.spr
sprites/glow07x.spr
sprites/greenglowa.spr
sprites/greenprojectile.spr
sprites/greentrail.spr
sprites/iexplox.spr
sprites/laserflarex.spr
sprites/lens_flare4.spr
sprites/proj1.spr
sprites/tjhud1.spr
sprites/tjhud2.spr
sprites/tjhud3.spr
sprites/tjhud4.spr
sprites/trempler/640_pain.spr
sprites/trempler/640hud7.spr
sprites/trempler/640hud8.spr
sprites/trempler/640hud9.spr
sprites/trempler/aexplo.spr
sprites/trempler/b_beam.spr
sprites/trempler/b_empty.spr
sprites/trempler/b_full.spr
sprites/trempler/ballsmoke.spr
sprites/trempler/bexplo.spr
sprites/trempler/blood.spr
sprites/trempler/blooddrop.spr
sprites/trempler/bloodspray.spr
sprites/trempler/cexplo.spr
sprites/trempler/fast_wallpuff1.spr
sprites/trempler/hotglow.spr
sprites/trempler/laserbeam.spr
sprites/trempler/muz4.spr
sprites/trempler/muzzleflash1.spr
sprites/trempler/muzzleflash2.spr
sprites/trempler/muzzleflash3.spr
sprites/trempler/plasma.spr
sprites/trempler/plasmaend.spr
sprites/trempler/richo2.spr
sprites/trempler/shockwave.spr
sprites/trempler/spark1.spr
sprites/trempler/Spark3.spr
sprites/trempler/stmbal1.spr
sprites/trempler/tele1.spr
sprites/trempler/xsmoke1.spr
sprites/trempler/xspark1.spr
sprites/trempler/zerogxplode.spr
sprites/uexplo.spr
sprites/was1.spr
sprites/was2.spr
sprites/was3.spr
sprites/was4.spr
sprites/weapon_custom/weapon_custom_boomstick.txt
sprites/weapon_custom/weapon_custom_rapegun.txt
sprites/weapon_custom/weapon_custom_rapegun2.txt
sprites/weapon_custom/weapon_custom_supershot.txt
