maps/sc_psyko.cfg
maps/sc_psyko.txt
maps/sc_psyko_motd.txt
maps/sc_psyko.gmr
models/sc_psyko/arc_fern.mdl
models/sc_psyko/blueslime.mdl
models/sc_psyko/greenhoundeye.mdl
models/sc_psyko/lightgreenslime.mdl
models/sc_psyko/orangeslime.mdl
models/sc_psyko/pigdrone.mdl
models/sc_psyko/pinkslime.mdl
models/sc_psyko/redbabygarg.mdl
models/sc_psyko/redbabygargt.mdl
models/sc_psyko/redslime.mdl
models/sc_psyko/tormaster.mdl
models/sc_psyko/turquoiseslave.mdl
models/sc_psyko/turquoiseslave01.mdl
models/sc_psyko/turquoiseslave02.mdl
models/sc_psyko/turquoisetrooper.mdl
models/sc_psyko/turquoisetrooper01.mdl
models/sc_psyko/yellowcontroller.mdl
models/sc_psyko/yellowcontrollert.mdl
models/sc_psyko/yellowslave.mdl
models/sc_psyko/yellowslave01.mdl
models/sc_psyko/yellowslave02.mdl
models/sc_psyko/yellowslime.mdl
sound/sc_psyko/bling.wav
sound/sc_psyko/boing1.wav
sound/sc_psyko/boing2.wav
sound/sc_psyko/dangerous.mp3
sound/sc_psyko/done.wav
sound/sc_psyko/pig.wav
sound/sc_psyko/plop.wav
sound/sc_psyko/puff.wav
sound/sc_psyko/slime_attack1.wav
sound/sc_psyko/slime_attack2.wav
sound/sc_psyko/slime_pain1.wav
sound/sc_psyko/slime_pain2.wav
sound/sc_psyko/theme1.mp3
sound/sc_psyko/theme2.mp3
sound/sc_psyko/think.mp3
sound/sc_psyko/tympani.wav
sound/sc_psyko/slime.txt
sound/sc_psyko/tor.txt
maps/sc_psyko.res
