maps/sc_royals1.cfg
maps/sc_royals1.res
maps/sc_royals1.txt
maps/sc_royals1_motd.txt
models/sc_royals/crazybarney.mdl
models/sc_royals/headcrabp.mdl
models/sc_royals/houndeyep.mdl
models/sc_royals/islavep.mdl
models/sc_royals/palm1a.mdl
models/sc_royals/palm2.mdl
models/sc_royals/sc_royals_model1.mdl
models/sc_royals/sc_royals_model2.mdl
models/sc_royals/sc_royals_model3.mdl
sound/sc_royals1/madbarney.txt
sound/sc_royals/laugh4.wav
sound/sc_royals/laugh5.wav
sound/sc_royals/imsorry.wav
sound/sc_royals/damn.wav
sound/sc_royals/yoga.wav
sound/sc_royals/thatsit.wav
sound/sc_royals/gogogo.wav