maps/sc_royals3.cfg
maps/sc_royals3.res
maps/sc_royals3.txt
maps/sc_royals3_motd.txt
models/sc_royals/arc_fern.mdl
models/sc_royals/crazybarney.mdl
models/sc_royals/headcrabp.mdl
models/sc_royals/islavep.mdl
models/sc_royals/palm1a.mdl
models/sc_royals/palm1b.mdl
models/sc_royals/palm2.mdl
models/sc_royals/rockgibsgold.mdl
models/sc_royals/sc_royals_model1.mdl
models/sc_royals/sc_royals_model2.mdl
models/sc_royals/sc_royals_model3.mdl
models/sc_royals/Torp.mdl
sound/sc_royals3/madbarney.txt
sound/sc_royals/laugh4.wav
sound/sc_royals/laugh5.wav
sound/sc_royals/imsorry.wav
sound/sc_royals/damn.wav
sound/sc_royals/yoga.wav
sound/sc_royals/thatsit.wav
sound/sc_royals/gogogo.wav