models/turr/turstatue.mdl
models/turr/piranha.mdl
models/turr/intruder.mdl
sound/tur/alec.wav
sound/tur/dylan.wav
sound/tur/oddity.wav
sound/tur/transformation.wav
sound/tur/hongkong.wav
gfx/env/fire-storm256_bk.tga
gfx/env/fire-storm256_dn.tga
gfx/env/fire-storm256_ft.tga
gfx/env/fire-storm256_lf.tga
gfx/env/fire-storm256_rt.tga
gfx/env/fire-storm256_up.tga
models/player/Vorinc/Vorinc.mdl
models/player/turr/turr.mdl
models/player/shadowslidje/shadowslidje.mdl
maps/secretcityx.res
maps/secretcityx_motd.txt
maps/secretcityx.cfg