// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

events/snglrt/anvil1.txt
events/snglrt/anvil2.txt
events/snglrt/dev1.txt
events/snglrt/frdm2_a.txt
events/snglrt/frdm2_b.txt
events/snglrt/frdm_a.txt
events/snglrt/frdm_b.txt
events/snglrt/hblaster.txt
events/snglrt/obsidian1.txt
events/snglrt/obsidian2.txt
events/snglrt/pt808_a.txt
events/snglrt/pt808_b.txt
events/snglrt/pt808_c.txt
events/snglrt/raptor.txt
events/snglrt/sbc.txt
events/snglrt/scho_a.txt
events/snglrt/scho_b.txt
events/snglrt/xl2_a.txt
events/snglrt/xl2_b.txt
events/snglrt/xl2_c.txt
events/snglrt/xl2_d.txt
events/snglrt/xl2b_a.txt
events/snglrt/xl2b_b.txt
events/snglrt/xl2b_c.txt
events/snglrt/xl2b_d.txt
events/snglrt/xl4_a.txt
events/snglrt/xl4_b.txt
events/snglrt/xl4_c.txt
events/snglrt/xl4_d.txt
models/sc_snipersux/bed_01.mdl
models/sc_snipersux/couch_leather-black.mdl
models/sc_snipersux/dns_sink.mdl
models/sc_snipersux/sniper.mdl
models/singularity/c_weps/ammo/arrows.mdl
models/singularity/c_weps/ammo/bullets.mdl
models/singularity/c_weps/ammo/cannon_balls.mdl
models/singularity/c_weps/ammo/darkmatter.mdl
models/singularity/c_weps/ammo/grenades.mdl
models/singularity/c_weps/ammo/ion.mdl
models/singularity/c_weps/ammo/nails.mdl
models/singularity/c_weps/ammo/plasma.mdl
models/singularity/c_weps/ammo/rockets.mdl
models/singularity/c_weps/ammo/shells.mdl
models/singularity/c_weps/ammo/sniper.mdl
models/singularity/c_weps/amr/p_amr.mdl
models/singularity/c_weps/amr/v_amr.mdl
models/singularity/c_weps/anvil/p_anvil.mdl
models/singularity/c_weps/anvil/v_anvil.mdl
models/singularity/c_weps/balista/p_balista.mdl
models/singularity/c_weps/balista/v_balista.mdl
models/singularity/c_weps/bonecrk/p_bonecracker.mdl
models/singularity/c_weps/bonecrk/v_bonecracker.mdl
models/singularity/c_weps/bonecrk/w_bonecracker.mdl
models/singularity/c_weps/commando/p_commando.mdl
models/singularity/c_weps/commando/v_commando.mdl
models/singularity/c_weps/dev/p_devastator.mdl
models/singularity/c_weps/dev/v_devastator.mdl
models/singularity/c_weps/dstinger/p_dstinger.mdl
models/singularity/c_weps/dstinger/v_dstinger.mdl
models/singularity/c_weps/freedom/p_freedom.mdl
models/singularity/c_weps/freedom/v_freedom.mdl
models/singularity/c_weps/frostbite/p_frostbite.mdl
models/singularity/c_weps/frostbite/v_frostbite.mdl
models/singularity/c_weps/hyper_blaster/p_hblaster.mdl
models/singularity/c_weps/hyper_blaster/v_hblaster.mdl
models/singularity/c_weps/ion_cannon/p_ion.mdl
models/singularity/c_weps/ion_cannon/v_ion.mdl
models/singularity/c_weps/kz_annihilator/p_kzannihilator.mdl
models/singularity/c_weps/kz_annihilator/v_kzannihilator.mdl
models/singularity/c_weps/kz_purifier/p_kzpurifier.mdl
models/singularity/c_weps/kz_purifier/v_kzpurifier.mdl
models/singularity/c_weps/misc/artilleryball.mdl
models/singularity/c_weps/misc/cannonball.mdl
models/singularity/c_weps/misc/crimson_nail.mdl
models/singularity/c_weps/misc/frost_nail.mdl
models/singularity/c_weps/misc/iron_shell.mdl
models/singularity/c_weps/misc/laser_stick_grn.mdl
models/singularity/c_weps/misc/laser_stick_prpl.mdl
models/singularity/c_weps/misc/laser_stick_red.mdl
models/singularity/c_weps/misc/srs_blk_nade.mdl
models/singularity/c_weps/misc/srs_nade.mdl
models/singularity/c_weps/misc/srs_prpl_nade.mdl
models/singularity/c_weps/misc/srs_rkt.mdl
models/singularity/c_weps/misc/tiberium_nail.mdl
models/singularity/c_weps/misc/titanium_bolt.mdl
models/singularity/c_weps/misc/toxic_nail.mdl
models/singularity/c_weps/mprl/p_mprl.mdl
models/singularity/c_weps/mprl/v_mprl.mdl
models/singularity/c_weps/obsidian/p_obsidian.mdl
models/singularity/c_weps/obsidian/v_obsidian.mdl
models/singularity/c_weps/pt808/p_pt808.mdl
models/singularity/c_weps/pt808/v_pt808.mdl
models/singularity/c_weps/raptor/p_raptor.mdl
models/singularity/c_weps/raptor/v_raptor.mdl
models/singularity/c_weps/sbc/p_cannon.mdl
models/singularity/c_weps/sbc/v_cannon.mdl
models/singularity/c_weps/schofield/p_schofield.mdl
models/singularity/c_weps/schofield/v_schofield.mdl
models/singularity/c_weps/w_mdls/null.mdl
models/singularity/c_weps/w_mdls/w_devastator.mdl
models/singularity/c_weps/w_mdls/w_freedom.mdl
models/singularity/c_weps/w_mdls/w_hblaster.mdl
models/singularity/c_weps/w_mdls/w_mprl.mdl
models/singularity/c_weps/w_mdls/w_pt808.mdl
models/singularity/c_weps/w_mdls/w_xl2.mdl
models/singularity/c_weps/xl2/p_xl2.mdl
models/singularity/c_weps/xl2/v_xl2.mdl
models/singularity/icons/mk_logo_blue.mdl
models/singularity/misc/armor_red.mdl
models/singularity/misc/health_heart.mdl
sound/oghs/cs06/a!.wav
sound/oghs/cs06/ahhhh.wav
sound/oghs/cs06/alab.wav
sound/oghs/cs06/au.wav
sound/oghs/cs06/ay.wav
sound/oghs/cs06/aynob.wav
sound/oghs/cs06/badbone.wav
sound/oghs/cs06/bell.wav
sound/oghs/cs06/boing.wav
sound/oghs/cs06/cries.wav
sound/oghs/cs06/crit.wav
sound/oghs/cs06/csm.wav
sound/oghs/cs06/cum.wav
sound/oghs/cs06/dies.wav
sound/oghs/cs06/dross.wav
sound/oghs/cs06/fack2.wav
sound/oghs/cs06/fart.wav
sound/oghs/cs06/gay.wav
sound/oghs/cs06/memori.wav
sound/oghs/cs06/noaab.wav
sound/oghs/cs06/nooo.wav
sound/oghs/cs06/omg.wav
sound/oghs/cs06/oogh.wav
sound/oghs/cs06/pipe.wav
sound/oghs/cs06/pui.wav
sound/oghs/cs06/qpasob.wav
sound/oghs/cs06/rushittingme.wav
sound/oghs/cs06/slip.wav
sound/oghs/cs06/soyun.wav
sound/oghs/cs06/tmr.wav
sound/oghs/cs06/tmr2.wav
sound/oghs/cs06/woah.wav
sound/oghs/cs06/zurdos.wav
sound/oghs/cs06/zzz.wav
sound/oghs/misc/cp02_03.mp3
sound/singularity/c_wep/ammo/arrows.wav
sound/singularity/c_wep/ammo/bullets.wav
sound/singularity/c_wep/ammo/cannon.wav
sound/singularity/c_wep/ammo/darkmatter.wav
sound/singularity/c_wep/ammo/grenades.wav
sound/singularity/c_wep/ammo/nails.wav
sound/singularity/c_wep/ammo/pku_ammo1.wav
sound/singularity/c_wep/ammo/pku_ammo5.wav
sound/singularity/c_wep/ammo/plasma.wav
sound/singularity/c_wep/ammo/rockets.wav
sound/singularity/c_wep/ammo/shells.wav
sound/singularity/c_wep/ammo/sniper.wav
sound/singularity/c_wep/amr/igi_psgs1.wav
sound/singularity/c_wep/amr/ss_snpr1.wav
sound/singularity/c_wep/amr/ss_snpr2.wav
sound/singularity/c_wep/amr/ss_snpr3.wav
sound/singularity/c_wep/amr/wlf_stn1.wav
sound/singularity/c_wep/anv/1shot.wav
sound/singularity/c_wep/anv/2shots.wav
sound/singularity/c_wep/anv/dragon_shot.wav
sound/singularity/c_wep/bal/bal_sht3.wav
sound/singularity/c_wep/bal/f_hit1.wav
sound/singularity/c_wep/bal/f_hit2.wav
sound/singularity/c_wep/bone/saw_flesh.wav
sound/singularity/c_wep/bone/saw_fly_flesh.wav
sound/singularity/c_wep/bone/saw_long.wav
sound/singularity/c_wep/bone/saw_short.wav
sound/singularity/c_wep/bone/saw_stop.wav
sound/singularity/c_wep/com/ar2_fire.wav
sound/singularity/c_wep/com/cm_b1.wav
sound/singularity/c_wep/com/cm_g1.wav
sound/singularity/c_wep/com/cm_s1.wav
sound/singularity/c_wep/dev/dev_crack.wav
sound/singularity/c_wep/dev/dev_hit.wav
sound/singularity/c_wep/dev/dev_meltdown.wav
sound/singularity/c_wep/dev/dev_prism.wav
sound/singularity/c_wep/dev/dev_rel2.wav
sound/singularity/c_wep/dev/dev_rel3.wav
sound/singularity/c_wep/dstngr/nail_hit_flesh.wav
sound/singularity/c_wep/dstngr/nail_hit_wall.wav
sound/singularity/c_wep/dstngr/sting01.wav
sound/singularity/c_wep/dstngr/sting02.wav
sound/singularity/c_wep/dstngr/sting03.wav
sound/singularity/c_wep/dstngr/tib_hit.wav
sound/singularity/c_wep/dstngr/tibrifle.wav
sound/singularity/c_wep/dstngr/tox_hlth01.wav
sound/singularity/c_wep/ehve/roach_blast.wav
sound/singularity/c_wep/frdm/fire.wav
sound/singularity/c_wep/frdm/rotd.wav
sound/singularity/c_wep/frdm/rotu.wav
sound/singularity/c_wep/frdm/shotty.wav
sound/singularity/c_wep/frst/ghst1.wav
sound/singularity/c_wep/frst/silenced.wav
sound/singularity/c_wep/frst/snipe.wav
sound/singularity/c_wep/hblst/hb_beam_shot.wav
sound/singularity/c_wep/hblst/hb_nova_hit.wav
sound/singularity/c_wep/hblst/hb_plsm.wav
sound/singularity/c_wep/hblst/hb_plsm_blast.wav
sound/singularity/c_wep/hblst/hb_plsm_chrg.wav
sound/singularity/c_wep/hblst/hb_plsm_nova_fly01.wav
sound/singularity/c_wep/ion/lg_fire_loop.wav
sound/singularity/c_wep/ion/lg_fire_start.wav
sound/singularity/c_wep/ion/lg_hit1.wav
sound/singularity/c_wep/ion/lg_hit2.wav
sound/singularity/c_wep/ion/lg_hit3.wav
sound/singularity/c_wep/k_annih/bigshot.wav
sound/singularity/c_wep/k_annih/eng_charge.wav
sound/singularity/c_wep/k_annih/nova.wav
sound/singularity/c_wep/k_annih/r_snipe.wav
sound/singularity/c_wep/k_annih/shockwave.wav
sound/singularity/c_wep/k_purifier/k_flesh.wav
sound/singularity/c_wep/k_purifier/k_spcl.wav
sound/singularity/c_wep/k_purifier/slsh03.wav
sound/singularity/c_wep/k_purifier/slsh04.wav
sound/singularity/c_wep/k_purifier/vcut.wav
sound/singularity/c_wep/misc/bounce/g_bounce1.wav
sound/singularity/c_wep/misc/bounce/g_bounce2.wav
sound/singularity/c_wep/misc/bounce/g_bounce3.wav
sound/singularity/c_wep/misc/bounce/g_bounce4.wav
sound/singularity/c_wep/misc/bounce/g_bounce5.wav
sound/singularity/c_wep/misc/bounce/grenade_hit1.wav
sound/singularity/c_wep/misc/bounce/grenade_hit2.wav
sound/singularity/c_wep/misc/bounce/grenade_hit3.wav
sound/singularity/c_wep/misc/enrg_hit.wav
sound/singularity/c_wep/misc/exp1.wav
sound/singularity/c_wep/misc/exp2.wav
sound/singularity/c_wep/misc/exp3.wav
sound/singularity/c_wep/misc/exp5.wav
sound/singularity/c_wep/misc/implosion.wav
sound/singularity/c_wep/misc/item_respawn.wav
sound/singularity/c_wep/misc/noammo.wav
sound/singularity/c_wep/misc/ss2_nade.wav
sound/singularity/c_wep/misc/wpn_pku.wav
sound/singularity/c_wep/mprl/bombpop.wav
sound/singularity/c_wep/mprl/rkt_bounce.wav
sound/singularity/c_wep/mprl/rkt_hit.wav
sound/singularity/c_wep/mprl/rl_shoot3.wav
sound/singularity/c_wep/mprl/rl_shoot4.wav
sound/singularity/c_wep/obs/burn1.wav
sound/singularity/c_wep/obs/burn2.wav
sound/singularity/c_wep/obs/obs_sg.wav
sound/singularity/c_wep/obs/plsm_nade.wav
sound/singularity/c_wep/pt808/pt_charge.wav
sound/singularity/c_wep/pt808/pt_overcharge.wav
sound/singularity/c_wep/pt808/pt_shot.wav
sound/singularity/c_wep/pt808/pt_xpl.wav
sound/singularity/c_wep/rptr/r_blt.wav
sound/singularity/c_wep/rptr/r_focus_shot.wav
sound/singularity/c_wep/rptr/r_shot.wav
sound/singularity/c_wep/rptr/r_zoom.wav
sound/singularity/c_wep/sbc/srs_boom.wav
sound/singularity/c_wep/sbc/srs_bounce.wav
sound/singularity/c_wep/sbc/srs_cancel.wav
sound/singularity/c_wep/sbc/srs_fire2.wav
sound/singularity/c_wep/sbc/srs_prep.wav
sound/singularity/c_wep/scho/scho_dual.wav
sound/singularity/c_wep/scho/scho_fire.wav
sound/singularity/c_wep/scho/scho_rel_dual.wav
sound/singularity/c_wep/xl2/xl2_destroyer.wav
sound/singularity/c_wep/xl2/xl4_shot.wav
sound/singularity/misc/cp_nod_reinf.mp3
sound/singularity/misc/teleport.wav
sound/singularity/npc/csgo_deag_shot.wav
sound/singularity/npc/dusk_shotgun_shot.wav
sound/singularity/npc/dusk_super_shotgun_shot.wav
sound/singularity/npc/hgrunt_3shot.wav
sound/singularity/npc/hl2_flesh_hit1.wav
sound/singularity/npc/hl2_flesh_hit2.wav
sound/singularity/npc/hl2_flesh_hit3.wav
sound/singularity/npc/igi2_dragunov_shot.wav
sound/singularity/npc/igi2_g36_shot.wav
sound/singularity/npc/quake3_grenade_shot.wav
sound/singularity/npc/quake4_plasma_shot.wav
sound/singularity/npc/starcraft_ghost_rifle.wav
sound/singularity/npc/tu_fire1.wav
sound/singularity/npc_bull/bc_die1.wav
sound/singularity/npc_bull/bc_die2.wav
sound/singularity/npc_bull/bc_die3.wav
sound/singularity/npc_bull/bc_idle1.wav
sound/singularity/npc_bull/bc_idle2.wav
sound/singularity/npc_bull/bc_idle3.wav
sound/singularity/npc_bull/bc_idle4.wav
sound/singularity/npc_bull/bc_idle5.wav
sound/singularity/npc_pitcrab/hc_alert1.wav
sound/singularity/npc_pitcrab/hc_alert2.wav
sound/singularity/npc_pitcrab/hc_attack1.wav
sound/singularity/npc_pitcrab/hc_attack2.wav
sound/singularity/npc_pitcrab/hc_attack3.wav
sound/singularity/npc_pitcrab/hc_die1.wav
sound/singularity/npc_pitcrab/hc_die2.wav
sound/singularity/npc_pitcrab/hc_headbite.wav
sound/singularity/npc_pitcrab/hc_idle1.wav
sound/singularity/npc_pitcrab/hc_idle2.wav
sound/singularity/npc_pitcrab/hc_idle3.wav
sound/singularity/npc_pitcrab/hc_idle4.wav
sound/singularity/npc_pitcrab/hc_idle5.wav
sound/singularity/npc_pitcrab/hc_pain1.wav
sound/singularity/npc_pitcrab/hc_pain2.wav
sound/singularity/npc_pitcrab/hc_pain3.wav
sound/singularity/npc_pitdrone/pit_drone_alert1.wav
sound/singularity/npc_pitdrone/pit_drone_alert2.wav
sound/singularity/npc_pitdrone/pit_drone_alert3.wav
sound/singularity/npc_pitdrone/pit_drone_attack_spike1.wav
sound/singularity/npc_pitdrone/pit_drone_attack_spike2.wav
sound/singularity/npc_pitdrone/pit_drone_die1.wav
sound/singularity/npc_pitdrone/pit_drone_die2.wav
sound/singularity/npc_pitdrone/pit_drone_die3.wav
sound/singularity/npc_pitdrone/pit_drone_idle1.wav
sound/singularity/npc_pitdrone/pit_drone_idle2.wav
sound/singularity/npc_pitdrone/pit_drone_idle3.wav
sound/singularity/npc_pitdrone/pit_drone_melee_attack1.wav
sound/singularity/npc_pitdrone/pit_drone_melee_attack2.wav
sound/singularity/null.wav
sound/singularity/pku/health.wav
sound/singularity/pku/superarmor2.wav
sound/singularity/pku/superhealth.wav
sound/weapons/357_close.wav
sound/weapons/357_hammerpull.wav
sound/weapons/357_open.wav
sound/weapons/357_reload.wav
sound/weapons/357_shellin.wav
sound/weapons/357_shellsdrop.wav
sound/weapons/crossbow_bolt.wav
sound/weapons/crossbow_draw.wav
sound/weapons/crossbow_fidget.wav
sound/weapons/crossbow_maghold.wav
sound/weapons/crossbow_magin.wav
sound/weapons/crossbow_magout.wav
sound/weapons/crossbow_magready.wav
sound/weapons/crossbow_pull.wav
sound/weapons/fidget_2.wav
sound/weapons/fidget_3.wav
sound/weapons/fidget_4.wav
sound/weapons/fidget_6.wav
sound/weapons/glock_clipin.wav
sound/weapons/glock_clipout.wav
sound/weapons/glock_empty.wav
sound/weapons/glock_slideback.wav
sound/weapons/glock_slideforward.wav
sound/weapons/glock_sliderelease.wav
sound/weapons/grenade_throw.wav
sound/weapons/hks_clic1.wav
sound/weapons/m41a_grenade.wav
sound/weapons/m4_boltpull.wav
sound/weapons/m4_clipin.wav
sound/weapons/m4_clipmiddle.wav
sound/weapons/m4_clipout.wav
sound/weapons/m4_cliptap.wav
sound/weapons/mp5_clipinsert1.wav
sound/weapons/mp5_cliprelease1.wav
sound/weapons/mp5_grenadelauncher_1.wav
sound/weapons/mp5_grenadelauncher_2.wav
sound/weapons/mp5_m203_grenade_drop.wav
sound/weapons/mp5_m203_grenade_insert.wav
sound/weapons/spas12_foley.wav
sound/weapons/weapon_catch.wav
sound/weapons/weapon_draw.wav
sound/weapons/weapon_holster.wav
sprites/singularity/c_wep/weapon_amr.txt
sprites/singularity/c_wep/weapon_anvil.txt
sprites/singularity/c_wep/weapon_balista.txt
sprites/singularity/c_wep/weapon_bonecracker.txt
sprites/singularity/c_wep/weapon_commando.txt
sprites/singularity/c_wep/weapon_devastator.txt
sprites/singularity/c_wep/weapon_duality_stinger.txt
sprites/singularity/c_wep/weapon_freedom_machine.txt
sprites/singularity/c_wep/weapon_frostbite.txt
sprites/singularity/c_wep/weapon_hyper_blaster.txt
sprites/singularity/c_wep/weapon_ion_cannon.txt
sprites/singularity/c_wep/weapon_kz_annihilator.txt
sprites/singularity/c_wep/weapon_kz_purifier.txt
sprites/singularity/c_wep/weapon_mprl.txt
sprites/singularity/c_wep/weapon_obsidian.txt
sprites/singularity/c_wep/weapon_pt808.txt
sprites/singularity/c_wep/weapon_raptor.txt
sprites/singularity/c_wep/weapon_sbc.txt
sprites/singularity/c_wep/weapon_schofield.txt
sprites/singularity/c_wep/weapon_xl2.txt
sprites/singularity/fx/b-tele_prpl_bl.spr
sprites/singularity/fx/b-tele_prpl_pk.spr
sprites/singularity/fx/energy_sphere.spr
sprites/singularity/fx/hotglow_crimson.spr
sprites/singularity/fx/hotglow_prpl.spr
sprites/singularity/fx/kz_nova_xpl.spr
sprites/singularity/fx/laser_crshr_cy.spr
sprites/singularity/fx/laser_crshr_wht.spr
sprites/singularity/fx/obsidianflame2.spr
sprites/singularity/fx/strchs_sr_exp.spr
sprites/singularity/fx/strchs_sr_star.spr
sprites/singularity/kezcrosshairs.spr
sprites/singularity/kezsniper2.spr
sprites/singularity/muz/devastator_muz.spr
sprites/singularity/muz/energy_line.spr
sprites/singularity/muz/energy_ring.spr
sprites/singularity/muz/obsidian_muz.spr
sprites/singularity/muz/plasma_muzzle.spr
sprites/singularity/muz/srs_muzzle1.spr
sprites/singularity/muz/xl2_muzzle.spr
sprites/singularity/prtl/kz_exit1.spr
sprites/singularity/snglrt_ammo.spr
sprites/singularity/snglrt_wep_hud_off.spr
sprites/singularity/snglrt_wep_hud_on.spr
sprites/singularity/xpl/spore_exp_01_rd.spr
sprites/singularity/xpl/spore_exp_c_01_rd.spr
sprites/singularity/xpl/zxlp_blue.spr
sprites/singularity/xpl/zxlp_crimson.spr
sprites/singularity/xpl/zxlp_purple.spr
sprites/singularity/xpl/zxpl_green.spr
