decals.wad
gfx/env/grassybk.tga
gfx/env/grassydn.tga
gfx/env/grassyft.tga
gfx/env/grassylf.tga
gfx/env/grassyrt.tga
gfx/env/grassyup.tga
halflife.wad
jailbreak2.wad
liquids.wad
megamonstermassacre.wad
models/svencooprpg2/dragon.mdl
models/svencooprpg2/grylion.mdl
models/svencooprpg2/hydra.mdl
models/svencooprpg2/p_flintlock.mdl
models/svencooprpg2/p_hb1.mdl
models/svencooprpg2/p_hb2.mdl
models/svencooprpg2/p_hb3.mdl
models/svencooprpg2/p_heal.mdl
models/svencooprpg2/p_longbow.mdl
models/svencooprpg2/p_sarticulus.mdl
models/svencooprpg2/p_spell2.mdl
models/svencooprpg2/p_spell3.mdl
models/svencooprpg2/p_warhammer.mdl
models/svencooprpg2/p_xbow.mdl
models/svencooprpg2/v_flintlock.mdl
models/svencooprpg2/v_hb1.mdl
models/svencooprpg2/v_hb2.mdl
models/svencooprpg2/v_hb3.mdl
models/svencooprpg2/v_heal.mdl
models/svencooprpg2/v_longbow.mdl
models/svencooprpg2/v_sarticulus.mdl
models/svencooprpg2/v_spell1.mdl
models/svencooprpg2/v_spell2.mdl
models/svencooprpg2/v_spell3.mdl
models/svencooprpg2/v_warhammer.mdl
models/svencooprpg2/v_xbow.mdl
models/svencooprpg2/w_warhammer.mdl
models/w_crossbow.mdl
scrpg2.wad
sound/ambience/the_horror2.wav
sound/bullchicken/bc_attack1.wav
sound/bullchicken/bc_die3.wav
sound/gonarch/gon_sack2.wav
sound/ichy/ichy_die2.wav
sound/svencooprpg2/grylion.wav
sound/tentacle/te_death2.wav
sound/x/x_attack3.wav
sound/x/x_laugh1.wav
sprites/b-tele1.spr
sprites/c-tele1.spr
sprites/fire.spr
sprites/lgtning.spr
sprites/xsmoke1.spr
sprites/xspark1.spr
xeno.wad
