decals.wad
gfx/env/grassybk.tga
gfx/env/grassydn.tga
gfx/env/grassyft.tga
gfx/env/grassylf.tga
gfx/env/grassyrt.tga
gfx/env/grassyup.tga
halflife.wad
jailbreak2.wad
liquids.wad
megamonstermassacre.wad
models/bskull_template1.mdl
models/skeleton.mdl
models/svencooprpg2/cattail.mdl
models/svencooprpg2/dragon.mdl
models/svencooprpg2/ghost1.mdl
models/svencooprpg2/heretic.mdl
models/svencooprpg2/mage.mdl
models/svencooprpg2/monster.mdl
models/svencooprpg2/mushroom.mdl
models/svencooprpg2/mushroom2.mdl
models/svencooprpg2/p_flintlock.mdl
models/svencooprpg2/p_hb1.mdl
models/svencooprpg2/p_hb2.mdl
models/svencooprpg2/p_hb3.mdl
models/svencooprpg2/p_heal.mdl
models/svencooprpg2/p_longbow.mdl
models/svencooprpg2/p_spell2.mdl
models/svencooprpg2/p_spell3.mdl
models/svencooprpg2/p_warhammer.mdl
models/svencooprpg2/p_xbow.mdl
models/svencooprpg2/priest.mdl
models/svencooprpg2/rat.mdl
models/svencooprpg2/sheep.mdl
models/svencooprpg2/v_flintlock.mdl
models/svencooprpg2/v_hb1.mdl
models/svencooprpg2/v_hb2.mdl
models/svencooprpg2/v_hb3.mdl
models/svencooprpg2/v_heal.mdl
models/svencooprpg2/v_longbow.mdl
models/svencooprpg2/v_spell1.mdl
models/svencooprpg2/v_spell2.mdl
models/svencooprpg2/v_spell3.mdl
models/svencooprpg2/v_warhammer.mdl
models/svencooprpg2/v_xbow.mdl
models/svencooprpg2/w_sword.mdl
models/svencooprpg2/w_warhammer.mdl
models/svencooprpg2/zombie.mdl
models/w_crossbow.mdl
scrpg2.wad
sound/ambience/alien_powernode.wav
sound/ambience/alien_twow.wav
sound/ambience/alienvalve1.wav
sound/ambience/cricket.wav
sound/ambience/crickets.wav
sound/ambience/des_wind3.wav
sound/ambience/disgusting.wav
sound/ambience/drips.wav
sound/ambience/waterfall3.wav
sound/aslave/slv_word2.wav
sound/aslave/slv_word3.wav
sound/debris/beamstart3.wav
sound/debris/beamstart7.wav
sound/debris/beamstart8.wav
sound/debris/bustflesh1.wav
sound/debris/metal3.wav
sound/gman/gman_noreg.wav
sound/weapons/mortar.wav
sound/x/x_attack1.wav
sound/x/x_laugh1.wav
sound/x/x_pain1.wav
sprites/b-tele1.spr
sprites/fire.spr
sprites/glow01.spr
sprites/tele1.spr
xeno.wad
