decals.wad
gfx.wad
gfx/env/morningbk.tga
gfx/env/morningdn.tga
gfx/env/morningft.tga
gfx/env/morninglf.tga
gfx/env/morningrt.tga
gfx/env/morningup.tga
halflife.wad
liquids.wad
models/rip.mdl
models/svencooprpg2/mushroom.mdl
models/svencooprpg2/mushroom2.mdl
models/svencooprpg2/p_sword.mdl
models/svencooprpg2/v_sword.mdl
models/svencooprpg2/w_sword.mdl
scrpg2.wad
sound/ambience/burning3.wav
sound/ambience/rocketrumble1.wav
sound/x/x_die1.wav
sound/x/x_laugh1.wav
spraypaint.wad
sprites/fire.spr
xeno.wad
