gfx/env/nightbk.tga
gfx/env/nightdn.tga
gfx/env/nightft.tga
gfx/env/nightlf.tga
gfx/env/nightrt.tga
gfx/env/nightup.tga
halflife.wad
liquids.wad
maps/the-climb2.cfg
maps/the-climb2_motd.txt
sound/ambience/burning1.wav
sound/ambience/flies.wav
sound/ambience/water_flowing1.wav
sound/ambience/waterfall3.wav
sound/debris/beamstart14.wav
sound/debris/bustconcrete1.wav
sound/scientist/scream1.wav
sound/scientist/scream2.wav
sound/scientist/scream20.wav
sound/scientist/scream24.wav
sound/scientist/scream5.wav
sound/tfc/ambience/goal_1.wav
sound/theclimb2/creak.wav
sound/theclimb2/cricket.wav
sound/theclimb2/cricket2.wav
sound/theclimb2/erriewind.wav
sound/theclimb2/jungle_ambience.wav
sound/theclimb2/light_hum.wav
sound/theclimb2/waterrun.wav
sprites/d-tele1.spr
sprites/e-tele1.spr
sprites/fire.spr
sprites/moths.spr
sprites/xsmoke1.spr
tfc.wad
tfc2.wad
xeno.wad
