maps/vger.cfg
maps/vger.res
maps/vger_motd.txt
maps/vger_readme.txt
maps/vger_skl.cfg
models/vger/demonotis.mdl
models/vger/demonotis01.mdl
models/vger/demonotis02.mdl
models/vger/demonotis03.mdl
models/vger/gvrobo.mdl
models/vger/pvrobo.mdl
models/vger/p_357.mdl
models/vger/rvrobo.mdl
models/vger/vgergrunt.mdl
models/vger/v_357.mdl
models/vger/w_357.mdl
sound/vger/all.wav
sound/vger/beer.wav
sound/vger/bleeeat.wav
sound/vger/capture.wav
sound/vger/goodjob.wav
sound/vger/heknows.wav
sound/vger/help.wav
sound/vger/personnel.wav
sound/vger/sniper.wav
sound/vger/theend.wav
sound/vger/yessir.wav
sprites/vger/turretinfo.spr
vger.wad
