//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/zm_nuke.html
sprites/flare1.spr
gfx/env/desertbk.tga
gfx/env/desertdn.tga
gfx/env/desertft.tga
gfx/env/desertlf.tga
gfx/env/desertrt.tga
gfx/env/desertup.tga
maps/zm_nuke.bsp
